# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-08 15:51
from __future__ import unicode_literals

from django.db import migrations


def create_modules_and_permissions(apps, schema_editor):
    Module = apps.get_model('rbac', 'Module')
    RBACPermission = apps.get_model('rbac', 'RBACPermission')

    modules_permissions = {
        'UnitySetup': ['View UnitySetup', 'Manage UnitySetup'],
        'Dashboard': ['View Dashboard', 'Manage Dashboard'],
        'Onboarding': ['View Onboarding', 'Manage Onboarding', 'Discovery Admin'],
        'UnityCollector': ['View UnityCollector', 'Manage UnityCollector', 'Register UnityCollector'],
        'Monitoring': ['View Monitoring', 'Manage Monitoring'],
        'Activity Log': ['View Activity Log', 'Download Activity Log'],
        'Network Topology': ['View Network Topology'],
        'Private Cloud': ['View Private Cloud', 'Manage Private Cloud', 'Remote Management'],
        'Public Cloud': ['View Public Cloud', 'Manage Public Cloud', 'Remote Management'],
        'Datacenter': ['View Datacenter', 'Manage Datacenter', 'Remote Management'],
        'Services': ['View Services', 'Manage Services'],
        'UnityConnect': ['View UnityConnect', 'Manage UnityConnect'],
        'AIML Event Management': ['View AIML Event Management', 'Manage AIML Event Management'],
        'DevOps Automation': [
            'View DevOps Automation', 'Manage DevOps Automation', 'View Jobs', 'Manage Jobs',
            'Execute Jobs', 'View Workflow', 'Manage Workflow', 'Execute Workflow', 'View Scripts', 'Manage Scripts'
        ],
        'Service Catalog': ['View Service Catalog', 'Manage Service Catalog', 'Order Catalog'],
        'Sustainability': ['View Sustainability'],
        'Cost Analysis': ['View Cost Analysis', 'Manage Cost Analysis', 'Cost Calculator'],
        'Unity Report': ['View Unity Report', 'Manage Unity Report'],
        'Ticket Management': ['View Tickets', 'Manage Tickets'],
        'Maintenance': ['View Maintenance', 'Manage Maintenance'],
        'User Management': ['View Users', 'Manage Users', 'Create Users'],
        'Notifications': ['View Notifications', 'Manage Notifications'],
        'Credentials': ['View Credentials', 'Manage Credentials'],
        'Integrations': ['View Integrations', 'Manage Integrations', 'Add Integrations', 'Sync Integrations'],
    }

    for module_name, permissions in modules_permissions.items():
        module = Module.objects.create(name=module_name)
        for perm_name in permissions:
            RBACPermission.objects.create(name=perm_name, module=module)


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_modules_and_permissions),
    ]
