# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-08 16:15
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def create_default_permission_sets_and_roles(apps, schema_editor):
    Module = apps.get_model('rbac', 'Module')
    RBACPermission = apps.get_model('rbac', 'RBACPermission')
    RBACPermissionSet = apps.get_model('rbac', 'RBACPermissionSet')
    RBACRole = apps.get_model('rbac', 'RBACRole')

    # Create PermissionSet for 'Administrator'
    all_permissions = RBACPermission.objects.filter(module__is_msp=False)
    admin_permission_set = RBACPermissionSet.objects.create(
        name='Administrator Permission Set',
        description='All Permissions for Administrator Role',
        is_active=True,
        is_default=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    admin_permission_set.rbac_permissions.set(all_permissions)

    # Create Role for 'Administrator'
    administrator_role = RBACRole.objects.create(
        name='Administrator',
        description='Administrator Role',
        is_active=True,
        is_default=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    administrator_role.permissions.add(admin_permission_set)

    # Create PermissionSet for 'Dashboard user'
    dashboard_module = Module.objects.get(name='Dashboard')
    dashboard_permissions = RBACPermission.objects.filter(module=dashboard_module)
    dashboard_permission_set = RBACPermissionSet.objects.create(
        name='Dashboard Permission Set',
        description='Dashboard Permissions for Dashboard User Role',
        is_active=True,
        is_default=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    dashboard_permission_set.rbac_permissions.set(dashboard_permissions)

    # Create Role for 'Dashboard user'
    dashboard_user_role = RBACRole.objects.create(
        name='Dashboard user',
        description='Dashboard User Role',
        is_active=True,
        is_default=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    dashboard_user_role.permissions.add(dashboard_permission_set)

    # Create PermissionSet for 'Global Read-Only'
    view_permissions = RBACPermission.objects.filter(name__icontains='View')
    readonly_permission_set = RBACPermissionSet.objects.create(
        name='Global Read-Only Permission Set',
        description='View-only Permissions for Global Read-Only Role',
        is_active=True,
        is_default=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    readonly_permission_set.rbac_permissions.set(view_permissions)

    # Create Role for 'Global Read-Only'
    global_read_only_role = RBACRole.objects.create(
        name='Global Read-Only',
        description='Global Read-Only Role',
        is_active=True,
        is_default=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    global_read_only_role.permissions.add(readonly_permission_set)


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20240808_0851'),
    ]

    operations = [
        migrations.RunPython(create_default_permission_sets_and_roles)
    ]
