# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-04 09:32
from __future__ import unicode_literals

from django.db import migrations


def create_and_update_module_permissions(apps, schema_editor):
    Module = apps.get_model('rbac', 'Module')
    RBACPermission = apps.get_model('rbac', 'RBACPermission')
    RBACPermissionSet = apps.get_model('rbac', 'RBACPermissionSet')

    network_config_module = Module.objects.create(name="Network Configuration")

    view_permission = RBACPermission.objects.create(
        name="View Network Configuration",
        module=network_config_module
    )
    manage_permission = RBACPermission.objects.create(
        name="Manage Network Configuration",
        module=network_config_module
    )

    administrator = RBACPermissionSet.objects.get(name="Administrator Permission Set", is_default=True)
    administrator.rbac_permissions.add(view_permission, manage_permission)

    global_read_only = RBACPermissionSet.objects.get(name="Global Read-Only Permission Set", is_default=True)
    global_read_only.rbac_permissions.add(view_permission)

    devops_module = Module.objects.get(name="DevOps Automation")
    if devops_module:
        permissions_to_update = {
            "View Jobs": "View Tasks",
            "Manage Jobs": "Manage Tasks",
            "Execute Jobs": "Execute Tasks"
        }
        for old_name, new_name in permissions_to_update.items():
            permission = RBACPermission.objects.get(name=old_name, module=devops_module)
            permission.name = new_name
            permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20240808_0915'),
    ]

    operations = [
        migrations.RunPython(create_and_update_module_permissions)
    ]
