# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-06 14:01
from __future__ import unicode_literals

from django.db import migrations


def add_cost_calculator_permission(apps, schema_editor):
    RBACPermission = apps.get_model('rbac', 'RBACPermission')
    RBACPermissionSet = apps.get_model('rbac', 'RBACPermissionSet')

    cost_calculator_permission = RBACPermission.objects.get(name="Cost Calculator")
    global_read_only = RBACPermissionSet.objects.get(name="Global Read-Only Permission Set", is_default=True)
    global_read_only.rbac_permissions.add(cost_calculator_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_add_network_configuration_module'),
    ]

    operations = [
        migrations.RunPython(add_cost_calculator_permission)
    ]
