# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-08 07:26
from __future__ import unicode_literals

from django.db import migrations


def add_connections_module(apps, schema_editor):
    Module = apps.get_model('rbac', 'Module')
    RBACPermission = apps.get_model('rbac', 'RBACPermission')
    RBACPermissionSet = apps.get_model('rbac', 'RBACPermissionSet')

    network_config_module = Module.objects.create(name="Connections")

    view_permission = RBACPermission.objects.create(
        name="View Connections",
        module=network_config_module
    )
    manage_permission = RBACPermission.objects.create(
        name="Manage Connections",
        module=network_config_module
    )

    administrator = RBACPermissionSet.objects.get(name="Administrator Permission Set", is_default=True)
    administrator.rbac_permissions.add(view_permission, manage_permission)

    global_read_only = RBACPermissionSet.objects.get(name="Global Read-Only Permission Set", is_default=True)
    global_read_only.rbac_permissions.add(view_permission)
    

class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_add_cost_calculator_permission'),
    ]

    operations = [
        migrations.RunPython(add_connections_module)
    ]
