# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-12 11:11
from __future__ import unicode_literals

import app.common.func
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0039_auto_20250808_0212'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0006_add_connections_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACEntityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=app.common.func.generate_uuid, editable=False, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('entity_selection', models.CharField(choices=[('all', 'All'), ('custom', 'Custom')], db_index=True, default='all', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_types', models.ManyToManyField(blank=True, related_name='rbac_object_group_content_types', to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_object_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_object_groups', to='organization.Organization')),
            ],
            options={
                'verbose_name': 'RBAC Entity Group',
            },
        ),
        migrations.CreateModel(
            name='RBACEntityObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_model_group_objects', to='rbac.RBACEntityGroup')),
            ],
            options={
                'verbose_name': 'RBAC Entity Object',
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'RBAC Module'},
        ),
        migrations.AlterModelOptions(
            name='rbacpermission',
            options={'verbose_name': 'RBAC Permission'},
        ),
        migrations.AlterModelOptions(
            name='rbacpermissionset',
            options={'verbose_name': 'RBAC Permission Set'},
        ),
        migrations.AlterModelOptions(
            name='rbacrole',
            options={'verbose_name': 'RBAC Role'},
        ),
        migrations.AlterModelOptions(
            name='rbacusergroup',
            options={'verbose_name': 'RBAC User Group'},
        ),
        migrations.AlterField(
            model_name='module',
            name='is_msp',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='rbacpermission',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_permission_modules', to='rbac.Module'),
        ),
        migrations.AlterField(
            model_name='rbacpermission',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_set_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_permissions_sets', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='rbac_permissions',
            field=models.ManyToManyField(blank=True, related_name='rbac_permission_set_permissions', to='rbac.RBACPermission'),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rbacpermissionset',
            name='uuid',
            field=models.UUIDField(db_index=True, default=app.common.func.generate_uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_role_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rbacrole',
            name='uuid',
            field=models.UUIDField(db_index=True, default=app.common.func.generate_uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_user_group_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_user_groups', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='uuid',
            field=models.UUIDField(db_index=True, default=app.common.func.generate_uuid, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='rbacpermissionset',
            name='entity_groups',
            field=models.ManyToManyField(blank=True, related_name='rbac_permission_set_entity_groups', to='rbac.RBACEntityGroup'),
        ),
    ]
