# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.common.func
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_user', models.CharField(max_length=128)),
                ('modified_user', models.CharField(max_length=128)),
                ('salesforce_id',
                 models.CharField(max_length=128, null=True, unique=True, verbose_name='Salesforce ID')),
                ('organization_type', models.CharField(
                    choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('PARTNER', 'PARTNER'),
                             ('DEMO', 'DEMO')], default='EXTERNAL', max_length=64)),
                ('customer_type',
                 models.CharField(choices=[('UL', 'UL'), ('EXT', 'EXT')], default='EXT', max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Organization Name')),
                ('address1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, default='San Francisco', max_length=128, null=True)),
                ('state', models.CharField(blank=True, default='California', max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='United States', max_length=128, verbose_name='Country')),
                ('domain', models.CharField(blank=True, max_length=128, null=True, verbose_name='Domain')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_street', models.CharField(blank=True, max_length=128, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=128, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=128, null=True)),
                ('billing_postalcode', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=128, null=True)),
                ('sf_createdby_id', models.CharField(blank=True, max_length=128, null=True)),
                ('sf_lastmodifiedby_id', models.CharField(blank=True, max_length=128, null=True)),
                ('sf_created_date', models.DateTimeField(blank=True, null=True)),
                ('sf_lastmodified_date', models.DateTimeField(blank=True, null=True)),
                ('sf_system_modstamp', models.DateTimeField(blank=True, null=True)),
                ('ulid', models.IntegerField(null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vpn_status', models.BooleanField(default=False)),
                ('onboarding_status', models.PositiveIntegerField(default=0)),
                ('is_management_enabled', models.BooleanField(default=True)),
                ('default_snmp_community', models.CharField(blank=True, max_length=128, null=True)),
                ('default_snmp_version',
                 models.CharField(choices=[('1', '1'), ('2c', '2c'), ('3', '3')], default='2c', max_length=10)),
                ('uuid',
                 models.UUIDField(blank=True, default=app.common.func.generate_uuid, null=True, verbose_name='UUID')),
                ('billing_enabled', models.BooleanField(default=False)),
                ('storage', models.CharField(blank=True, max_length=255, null=True)),
                ('_logo', models.TextField(blank=True, db_column='logo')),
            ],
            options={
                'db_table': 'organization',
                'verbose_name_plural': 'Organizations',
                'permissions': (('view', 'Can View organization'),),
            },
        ),
        migrations.CreateModel(
            name='OrganizationOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'organizationowner',
                'verbose_name_plural': 'OrganizationOwners',
                'permissions': (('view', 'Can View organization owner'),),
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='template_file', max_length=128)),
                ('value', models.CharField(default='ul_template.html', max_length=256)),
            ],
            options={
                'db_table': 'organizationprofile',
                'verbose_name_plural': 'OrganizationProfiles',
            },
        ),
        migrations.CreateModel(
            name='OrganizationStorageInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('storage_type',
                 models.CharField(choices=[('SAN', 'SAN'), ('DISK', 'DISK')], default='DISK', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UnityModules',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserPinnedOrganizationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'db_table': 'user_organization_map',
            },
        ),
    ]
