# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0002_auto_20210416_0415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacenter', '0002_auto_20210416_0415'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpinnedorganizationmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationstorageinventory',
            name='datacenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Datacenter'),
        ),
        migrations.AddField(
            model_name='organizationstorageinventory',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationprofiles',
            name='org',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Organization', verbose_name='Organization ID'),
        ),
        migrations.AddField(
            model_name='organizationowner',
            name='organization',
            field=models.OneToOneField(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE,
                                       related_name='Org_Owner', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationowner',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE,
                                       related_name='Org_Owner_ID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='datacenters',
            field=models.ManyToManyField(through='inventory.CustomerDatacenterMview', to='datacenter.Datacenter'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_org',
            field=models.ForeignKey(blank=True, db_column='parent_org_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='organization.Organization',
                                    verbose_name='Parent ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='unity_modules',
            field=models.ManyToManyField(to='organization.UnityModules'),
        ),
        migrations.AlterUniqueTogether(
            name='userpinnedorganizationmap',
            unique_together=set([('user', 'pinned_organization')]),
        ),
    ]
