# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-26 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210416_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='monitor_by',
            field=models.CharField(choices=[('observium', 'Observium'), ('zabbix', 'Zabbix')], default='INTERNAL', max_length=64),
        ),
    ]
