# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-10-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationmonitoringconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='monitor_by',
            field=models.CharField(choices=[('observium', 'Observium'), ('zabbix', 'Zabbix')], default='observium', max_length=64),
        ),
    ]
