# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-15 10:36
from __future__ import unicode_literals

from django.db import migrations


def update_monitor_config_mapping(apps, schema_editor):
    _config = {
        u'bms': 1,
        u'database': 2,
        u'firewall': 1,
        u'hypervisor': 1,
        u'load_balancer': 1,
        u'mac_device': 1,
        u'pdu': 1,
        u'storage': 1,
        u'switch': 1,
        u'vm': 1
    }

    Organization = apps.get_model('organization', 'Organization')
    OrganizationMonitoringConfig = apps.get_model('organization', 'OrganizationMonitoringConfig')
    for org in Organization.objects.all():
        try:
            OrganizationMonitoringConfig.objects.get(org=org)
            print("Org Monitor Config already exist for {}".format(org.name))
        except OrganizationMonitoringConfig.DoesNotExist:
            OrganizationMonitoringConfig.objects.create(_config=_config, org=org)
            print("Created Org Monitor Config for {}".format(org.name))


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20211027_0710'),
    ]

    operations = [
        migrations.RunPython(update_monitor_config_mapping),
    ]
