# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20211215_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='advanced_discovery',
            field=models.BooleanField(default=False),
        ),
    ]
