# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-05-05 12:35
from __future__ import unicode_literals

from django.db import migrations


def add_sustainability_module(apps, schema_editor):
    UnityModules = apps.get_model('organization', 'UnityModules')
    UnityModules.objects.get_or_create(module_name="Sustainability")


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_advanced_discovery'),
    ]

    operations = [
        migrations.RunPython(add_sustainability_module),
    ]
