# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-10 11:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20220505_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notify_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
