# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-14 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20221110_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='notify_alerts',
            new_name='alerts_notification_enabled',
        ),
    ]
