# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-17 08:09
from __future__ import unicode_literals

import app.Utils.utility
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20221114_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationGroup',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                )),
                ('uuid', models.UUIDField(
                    default=app.Utils.utility.generate_uuid, unique=True
                )),
                ('group_name', models.CharField(
                    max_length=128
                )),
                ('users', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(),
                    blank=True,
                    default=list,
                    size=None
                )),
                ('is_enabled', models.BooleanField(
                    default=True
                )),
                ('alert_type', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        blank=True,
                        max_length=20,
                        null=True
                    ),
                    size=None
                )),
                ('mode', models.CharField(
                    choices=[('email', 'email')],
                    default='email',
                    max_length=45,
                    null=True
                )),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(
                blank=True,
                default=app.Utils.utility.generate_uuid,
                null=True,
                verbose_name='UUID'
            ),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notification_group',
                to='organization.Organization'
            ),
        ),
    ]
