# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-20 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0011_auto_20230217_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertnotificationgroup',
            name='users',
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='alertnotificationgroup_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
