# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-28 06:35
from __future__ import unicode_literals

from django.db import migrations


def update_unity_module(apps, schema_editor):
    UnityModules = apps.get_model('organization', 'UnityModules')
    try:
        notification_module = UnityModules.objects.get(module_name="Notification setup")
        notification_module.module_name = "Notification Setup"
        notification_module.save()
    except UnityModules.DoesNotExist:
        UnityModules.objects.create(module_name="Notification Setup")


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20230220_1021'),
    ]

    operations = [
        migrations.RunPython(update_unity_module, migrations.RunPython.noop),
    ]
