# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-14 18:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20230227_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='mode2',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('email', 'email'),
                        ('sms', 'sms')
                    ],
                    max_length=45
                ),
                default=['email'],
                size=None
            ),
        ),
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='mode',
            field=models.CharField(choices=[('email', 'email'), ('sms', 'sms')], default='email', max_length=45, null=True),
        ),
    ]
