# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-14 18:03
from __future__ import unicode_literals

from django.db import migrations


def update_alert_mode(apps, schema_editor):
    AlertNotificationGroup = apps.get_model('organization', 'AlertNotificationGroup')
    for alert in AlertNotificationGroup.objects.all():
        alert.mode2 = [alert.mode]
        alert.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20230314_1103'),
    ]

    operations = [
        migrations.RunPython(update_alert_mode, migrations.RunPython.noop),
    ]
