# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-14 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20230314_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertnotificationgroup',
            name='mode',
        ),
    ]
