# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-14 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_remove_alertnotificationgroup_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertnotificationgroup',
            old_name='mode2',
            new_name='mode',
        ),
    ]
