# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-12 06:55
from __future__ import unicode_literals

from django.db import migrations

def add_credentials_module(apps, schema_editor):
    UnityModules = apps.get_model('organization', 'UnityModules')
    UnityModules.objects.get_or_create(module_name="Credentials")


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20230314_1145'),
    ]

    operations = [
        migrations.RunPython(add_credentials_module),
    ]
