# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-08 09:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0018_auto_20230711_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_ticketing_enabled', models.BooleanField(default=False)),
                ('auto_remediation_enabled', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_ticketing_severity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'All'), (1, 'Critical'), (2, 'Warning'), (3, 'Information')]), blank=True, null=True, size=None)),
                ('auto_ticketing_delay', models.IntegerField(default=70)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketing_system', to='contenttypes.ContentType')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
