# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-12 06:55
from __future__ import unicode_literals

from django.db import migrations

def add_devops_automation_module(apps, schema_editor):
    UnityModules = apps.get_model('organization', 'UnityModules')
    UnityModules.objects.get_or_create(module_name="Devops Automation")


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20230711_2355'),
    ]

    operations = [
        migrations.RunPython(add_devops_automation_module),
    ]
