# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-10 10:39
from __future__ import unicode_literals

import app.Utils.utility
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_organizationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='uuid',
            field=models.UUIDField(default=app.Utils.utility.generate_uuid, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='auto_ticketing_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Warning'), (3, 'Information')]), blank=True, null=True, size=None),
        ),
    ]
