# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-10 11:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_auto_20230810_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='auto_ticketing_severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
