# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-16 16:47
from __future__ import unicode_literals

from django.db import migrations


def add_organization_settings(apps, schema_editor):
    Organization = apps.get_model('organization', 'Organization')
    OrganizationSettings = apps.get_model('organization', 'OrganizationSettings')

    for org in Organization.objects.all():
        try:
            OrganizationSettings.objects.get(organization=org)
        except OrganizationSettings.DoesNotExist:
            OrganizationSettings.objects.create(organization=org)
            

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_auto_20230810_0411'),
    ]

    operations = [
        migrations.RunPython(add_organization_settings),
    ]
