# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-23 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20230822_1315'),
        ('organization', '0022_auto_20230816_0947'),
    ]

    operations = [
    ]
