# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-22 12:57
from __future__ import unicode_literals

from django.db import migrations


def change_organization_config_key(apps, schema_editor):
    OrganizationMonitoringConfig = apps.get_model('organization', 'OrganizationMonitoringConfig')

    for org_config in OrganizationMonitoringConfig.objects.all():
        bms  = org_config._config.pop('bms')
        if bms:
            org_config._config['baremetal'] = bms
            org_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20230816_0947'),
    ]

    operations = [
        migrations.RunPython(change_organization_config_key),
    ]
