# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-23 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_auto_20230822_0557'),
        ('organization', '0023_merge_20230822_2323'),
    ]

    operations = [
    ]
