# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-09-28 06:57
from __future__ import unicode_literals

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def change_unity_report_module(apps, schema_editor):
    UnityModules = apps.get_model('organization', 'UnityModules')
    Organization = apps.get_model('organization', 'Organization')
    unity_report, flag = UnityModules.objects.get_or_create(module_name="UnityReport")
    try:
        reports = UnityModules.objects.get(module_name="Reports")
        inventory = UnityModules.objects.get(module_name="Inventory")
        for org in Organization.objects.all():
            if reports in org.unity_modules.all():
                org.unity_modules.add(unity_report)
        reports.delete()
        inventory.delete()
    except ObjectDoesNotExist as e:
        pass
        # for org in Organization.objects.all():
        #     if reports in org.unity_modules.all():
        #         org.unity_modules.add(unity_report)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_merge_20230823_0444'),
    ]

    operations = [
        migrations.RunPython(change_unity_report_module),
    ]
