# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-09-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_merge_20230823_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='msp_client',
            field=models.BooleanField(default=False),
        ),
    ]
