# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import mtp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_organization_msp_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(11, 'Europe'), (22, 'US')], default=22),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(blank=True, default=mtp.utils.generate_multidb_org_uuid, null=True, verbose_name='UUID'),
        ),
    ]
