# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-16 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtp', '0004_mtpgroup'),
        ('organization', '0026_auto_20231014_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mtp_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mtp.MtpGroup'),
        ),
    ]
