# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_organization_mtp_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_tenant_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mtp_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mtp.MtpGroup'),
        ),
    ]
