# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_auto_20231020_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='lat',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='organization',
            name='long',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Longitude'),
        ),
    ]
