# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-22 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20230927_2357'),
        ('organization', '0029_auto_20231020_1310'),
    ]

    operations = [
    ]
