# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-26 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_merge_20231022_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationsettings',
            options={'ordering': ['id']},
        ),
    ]
