# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20231026_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True, verbose_name='Email'),
        ),
    ]
