# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-11-30 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_auto_20231030_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='monitor_by',
        ),
    ]
