# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-01-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_remove_organization_monitor_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='multidb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(11, 'Europe'), (22, 'US')]),
        ),
    ]
