# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-07-18 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20240107_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='finops_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
