# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-07-23 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_organization_finops_enabled'),
        ('organization', '0035_organizationsettings_attach_rca_to_ticket'),
    ]

    operations = [
    ]
