# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-07-31 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_merge_20250723_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cmdb_reports_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
