# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-08 08:31
from __future__ import unicode_literals

import commonservices.rule_builder
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0037_organization_cmdb_reports_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='alert_notification_group_created_by',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='custom_filter_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='filter_rule_meta',
            field=commonservices.rule_builder.RuleField(null=True),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='filter_type',
            field=models.CharField(db_index=True, default='all', max_length=16),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='alert_notification_group_updated_by',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='webhook_url',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='alert_type',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[('critical', 'Critical'), ('information', 'Information'), ('warning', 'Warning')],
                    max_length=32,
                    null=True
                ),
                size=None
            ),
        ),
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='group_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='mode',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('ms_teams', 'MS Teams')], db_index=True, default='email', max_length=16),
        ),
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='alertnotificationgroup_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
