# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-08 09:12
from __future__ import unicode_literals

from django.db import migrations


def convert_array_to_char(apps, schema_editor):
    AlertNotificationGroup = apps.get_model('organization', 'AlertNotificationGroup')
    for group in AlertNotificationGroup.objects.all():
        group.mode = 'email'
        group.save()


def replace_info_with_information(apps, schema_editor):
    AlertNotificationGroup = apps.get_model('organization', 'AlertNotificationGroup')
    for group in AlertNotificationGroup.objects.all():
        if group.alert_type:
            updated_alert_type = ['information' if a == 'info' else a for a in group.alert_type]
            if updated_alert_type != group.alert_type:
                group.alert_type = updated_alert_type
                group.save(update_fields=['alert_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_auto_20250808_0131'),
    ]

    operations = [
        migrations.RunPython(convert_array_to_char),
        migrations.RunPython(replace_info_with_information),
    ]
