# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_auto_20250808_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
