# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0040_organization_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_rag_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
