# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-08 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0040_organization_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='ticket_subject_format',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
