# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-09 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0041_organizationsettings_ticket_subject_format'),
        ('organization', '0041_organization_is_rag_enabled'),
    ]

    operations = [
    ]
