# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-01-08 08:13
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_community(apps, schema_editor):
    organization = apps.get_model("organization", "organization")
    for row in organization.objects.all():
            row._default_snmp_community = row.default_snmp_community
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0042_merge_20251009_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='_default_snmp_community',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_community),
        migrations.RemoveField(
            model_name='organization',
            name='default_snmp_community',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='_default_snmp_community',
            new_name='default_snmp_community',
        )
    ]
