# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-02-23 14:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_auto_20260112_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='alert_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('information', 'Information'), ('warning', 'Warning')], max_length=32, null=True), size=None),
        ),
    ]
