# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-02-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_organization__default_snmp_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='webhook_url',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
