# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-02-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0044_auto_20260205_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='webhook_url',
            field=models.TextField(blank=True, db_index=True, max_length=512, null=True),
        ),
    ]
