# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-02-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0045_auto_20260226_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='module',
            field=models.CharField(choices=[('aiml', 'AIML'), ('deprecation', 'Deprecation'), ('devops_automation', 'DevOps Automation')], db_index=True, default='aiml', max_length=32),
        ),
        migrations.AddField(
            model_name='alertnotificationgroup',
            name='notify',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
