# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-02-27 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0047_auto_20260227_0131'),
        ('organization', '0045_auto_20260225_0153'),
    ]

    operations = [
    ]
