# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-03-03 13:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0048_merge_20260227_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotificationgroup',
            name='alert_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('information', 'Information'), ('warning', 'Warning'), ('end_of_life', 'End of Life'), ('end_of_support', 'End of Support'), ('success', 'Success'), ('failed', 'Failed')], max_length=32, null=True), size=None),
        ),
    ]
