# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-06-04 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0049_auto_20260303_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='auto_publish_condition_to_kb',
            field=models.BooleanField(default=False),
        ),
    ]
