# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-06-10 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0050_organization_is_lumi_org'),
        ('organization', '0050_organizationsettings_auto_publish_condition_to_kb'),
    ]

    operations = [
    ]
