# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-07-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0051_merge_20260610_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='is_pro_ai_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
