export const PublicCloud = ['Azure', 'AWS', 'OCI', 'GCP'];
export const PrivateCloud = [
  'OpenStack',
  'VMware',
  'United Private Cloud vCenter',
  'ESXi',
  'Custom',
  'vCloud Director',
  'Proxmox',
  'G3 KVM',
  'Hyperv',
  'Nutanix',
];
export const AllCloud = PublicCloud.concat(PrivateCloud);
export const Status = ['Up', 'Down', 'Unknown'];

// export const Status = [
//     "AVAILABLE",
//     "NA",
// ];

// export const PublicCloudStatus = [
//     "running",
//     "stopped",
// ];

// Static attribute catalogs for reusable report filter builders.
// The values here are backend-facing filter/operator names used in saved report_meta payloads.
export const Devices = [
  'Switch',
  'Firewalls',
  'Load Balancers',
  'Hypervisor',
  'Baremetal',
  'Virtual Machines',
  'Macdevice',
  'Containers',
  'Storage',
  'S3',
  'Mobile Device',
  'Databases',
];
export const OtherDevices = Devices.concat('Other Device');
export const AgentInstalled = ['Yes', 'No', 'Not Applicable'];
export const Monitoring = ['Enable', 'Disable', 'Not configured'];
export const OSType = ['Linux', 'Windows', 'Mac', 'ESxi'];
export const DiscoveryMethod = ['API', 'SNMP', 'SSH', 'WMI'];
export const Regions = [
  'us-east-1',
  'us-west-1',
  'us-west-2',
  'eu-west-1',
  'eu-central-1',
  'ap-southeast-1',
  'ap-southeast-2',
  'ap-northeast-2',
  'ap-northeast-1',
  'ap-south-1',
  'sa-east-1',
  'eastus',
  'eastus2',
  'southcentralus',
  'westus2',
  'westus3',
  'australiaeast',
  'southeastasia',
  'northeurope',
  'swedencentral',
  'uksouth',
  'westeurope',
  'centralus',
  'southafricanorth',
  'centralindia',
  'eastasia',
  'japaneast',
  'koreacentral',
  'canadacentral',
  'francecentral',
  'germanywestcentral',
  'italynorth',
  'norwayeast',
  'polandcentral',
  'spaincentral',
  'switzerlandnorth',
  'mexicocentral',
  'uaenorth',
  'brazilsouth',
  'israelcentral',
  'qatarcentral',
  'centralusstage',
  'eastusstage',
  'eastus2stage',
  'northcentralusstage',
  'southcentralusstage',
  'westusstage',
  'westus2stage',
  'asia',
  'asiapacific',
  'australia',
  'brazil',
  'canada',
  'europe',
  'france',
  'germany',
  'global',
  'india',
  'israel',
  'italy',
  'japan',
  'korea',
  'newzealand',
  'norway',
  'poland',
  'qatar',
  'singapore',
  'southafrica',
  'sweden',
  'switzerland',
  'uae',
  'uk',
  'unitedstates',
  'unitedstateseuap',
  'eastasiastage',
  'southeastasiastage',
  'brazilus',
  'eastusstg',
  'northcentralus',
  'westus',
  'japanwest',
  'jioindiawest',
  'centraluseuap',
  'eastus2euap',
  'westcentralus',
  'southafricawest',
  'australiacentral',
  'australiacentral2',
  'australiasoutheast',
  'jioindiacentral',
  'koreasouth',
  'southindia',
  'westindia',
  'canadaeast',
  'francesouth',
  'germanynorth',
  'norwaywest',
  'switzerlandwest',
  'ukwest',
  'uaecentral',
  'brazilsoutheast',
  'us-west2',
  'us-west1',
  'us-east1',
  'us-east4',
  'us-central1',
  'asia-east1',
  'asia-east2',
  'asia-northeast1',
  'asia-northeast2',
  'asia-south1',
  'asia-southeast1',
  'australia-southeast1',
  'europe-north1',
  'europe-west1',
  'europe-west2',
  'europe-west3',
  'europe-west4',
  'europe-west6',
  'northamerica-northeast1',
  'southamerica-east1',
  'ap-sydney-1',
  'ap-melbourne-1',
  'sa-saopaulo-1',
  'sa-vinhedo-1',
  'ca-montreal-1',
  'ca-toronto-1',
  'sa-santiago-1',
  'eu-frankfurt-1',
  'ap-hyderabad-1',
  'ap-mumbai-1',
  'ap-osaka-1',
  'ap-tokyo-1',
  'eu-amsterdam-1',
  'me-jeddah-1',
  'ap-seoul-1',
  'ap-chuncheon-1',
  'eu-zurich-1',
  'me-dubai-1',
  'uk-london-1',
  'uk-cardiff-1',
  'us-ashburn-1',
  'us-phoenix-1',
  'us-sanjose-1',
];
export const Services = [
  'EC2',
  'CloudTrail',
  'Elasticsearch',
  'IAM',
  'ACM',
  'RDS',
  'S3',
  'Redshift',
  'SSM',
  'ElasticLoadBalancing',
  'AutoScaling',
  'DynamoDB',
  'CodeBuild',
  'WAF',
  'WAFRegional',
  'CloudFront',
  'Lambda',
  'NetworkFirewall',
  'ElasticBeanstalk',
  'WAFv2',
  'XRay',
  'Shield',
  'ShieldRegional',
  'Config',
  'ApiGateway',
  'ApiGatewayV2',
  'CodePipeline',
  'ServiceCatalog',
  'SQS',
  'KMS',
  'QLDB',
  'SNS',
  'Backup',
  'ECR',
  'ECS',
  'EFS',
  'OpenSearch',
  'Kinesis',
  'GuardDuty',
  'EMR',
  'SageMaker',
  'Route53Resolver',
  'DMS',
  'MSK',
  'StepFunctions',
  'WorkSpaces',
  'ElasticLoadBalancingV2',
  'Batch',
  'AccessAnalyzer',
  'Athena',
  'Detective',
  'GlobalAccelerator',
  'AppConfig',
  'AppSync',
  'DataSync',
  'EKS',
  'Glue',
  'ServiceDiscovery',
  'SES',
  'Route53',
  'IoTEvents',
  'ImageBuilder',
  'Route53RecoveryReadiness',
  'RUM',
  'Events',
  'Lightsail',
  'FIS',
  'AmazonMQ',
  'Cloud9',
  'EventSchemas',
  'FraudDetector',
  'IoT',
  'IoTAnalytics',
  'MediaPackage',
  'ResilienceHub',
  'Transfer',
  'IoTTwinMaker',
  'CodeDeploy',
  'IoTSiteWise',
  'IVS',
  'KinesisAnalyticsV2',
  'DeviceFarm',
  'Lex',
  'CodeGuruReviewer',
  'RoboMaker',
  'LookoutMetrics',
  'KinesisVideo',
  'AppStream',
  'LookoutVision',
  'Route53RecoveryControl',
  'HealthLake',
  'Pinpoint',
  'CustomerProfiles',
  'Connect',
  'AppFlow',
  'AuditManager',
  'GroundStation',
  'IoTWireless',
  'NetworkManager',
  'Panorama',
  'Cassandra',
  'Signer',
  'Amplify',
  'AppMesh',
  'AppRunner',
  'CodeArtifact',
  'Evidently',
  'Forecast',
  'KinesisFirehose',
  'GreengrassV2',
  'MediaConnect',
  'MediaTailor',
  'Personalize',
  'ACMPCA',
  'Kendra',
  'Logs',
  'InspectorV2',
  'APS',
  'CodeGuruProfiler',
  'KafkaConnect',
  'Cognito',
  'Grafana',
  'QuickSight',
  'CloudWatch',
  'SecretsManager',
  'CloudFormation',
  'Budgets',
  'AppIntegrations',
  'ResourceExplorer2',
  'M2',
  'Operations',
  'Remediations',
  'Event Grid Filters',
  'Check Policy Restrictions',
  'Policy Tracked Resources',
  'Policy Metadata',
  'Identities',
  'User Assigned Identities',
  'Managed Clusters/Event Grid Filters',
  'Fleet Memberships',
  'Fleets',
  'Fleets/Members',
  'Fleets/Update Runs',
  'Fleets/Update Strategies',
  'Locations',
  'Locations/Notify Network Security Perimeter Updates Available',
  'Locations/Operationresults',
  'Locations/Operations',
  'Locations/Orchestrators',
  'Locations/Kubernetes Versions',
  'Locations/Node Image Versions',
  'Locations/Usages',
  'Locations/Os Options',
  'Locations/Safeguards Versions',
  'Locations/Guardrails Versions',
  'Locations/Trusted Access Roles',
  'Locations/Mesh Revision Profiles',
  'Managed Clusters',
  'Managedclustersnapshots',
  'Snapshots',
  'Usage Aggregates',
  'Rate Card',
  'Suppressions',
  'Configurations',
  'Metadata',
  'Recommendations',
  'Generate Recommendations',
  'Advisor Score',
  'Predict',
  'Domain Names',
  'Check Domain Name Availability',
  'Domain Names/Slots',
  'Domain Names/Slots/Roles',
  'Domain Names/Slots/Roles/Metric Definitions',
  'Domain Names/Slots/Roles/Metrics',
  'Virtual Machines',
  'Capabilities',
  'Domain Names/Capabilities',
  'Domain Names/Service Certificates',
  'Quotas',
  'Virtual Machines/Diagnostic Settings',
  'Virtual Machines/Metric Definitions',
  'Virtual Machines/Metrics',
  'Resource Types',
  'Move Subscription Resources',
  'Validate Subscription Move Availability',
  'Operation Statuses',
  'Operating Systems',
  'Operating System Families',
  'Storage Accounts',
  'Check Storage Account Availability',
  'Storage Accounts/Services',
  'Storage Accounts/Services/Diagnostic Settings',
  'Storage Accounts/Services/Metrics',
  'Storage Accounts/Metric Definitions',
  'Storage Accounts/Metrics',
  'Policy States',
  'Storage Accounts/File Services',
  'Storage Accounts/Queue Services',
  'Disks',
  'Images',
  'Vm Images',
  'Storage Accounts/Vm Images',
  'Public Images',
  'Os Images',
  'Os Platform Images',
  'Virtual Machines/Extensions',
  'Virtual Machine Scale Sets',
  'Virtual Machine Scale Sets/Extensions',
  'Virtual Machine Scale Sets/Virtual Machines',
  'Virtual Machine Scale Sets/Virtual Machines/Extensions',
  'Virtual Machine Scale Sets/Network Interfaces',
  'Virtual Machine Scale Sets/Virtual Machines/Network Interfaces',
  'Virtual Machine Scale Sets/Public Ipaddresses',
  'Locations/Vm Sizes',
  'Locations/Run Commands',
  'Locations/Virtual Machines',
  'Locations/Virtual Machine Scale Sets',
  'Locations/Publishers',
  'Virtual Machine Scale Sets/Applications',
  'Virtual Machines/Vmapplications',
  'Locations/Edge Zones',
  'Locations/Edge Zones/Vmimages',
  'Locations/Edge Zones/Publishers',
  'Restore Point Collections',
  'Restore Point Collections/Restore Points',
  'Proximity Placement Groups',
  'Ssh Public Keys',
  'Capacity Reservation Groups',
  'Capacity Reservation Groups/Capacity Reservations',
  'Locations/Spot Eviction Rates',
  'Locations/Spot Price History',
  'Locations/Recommendations',
  'Locations/Shared Galleries',
  'Locations/Community Galleries',
  'Shared Vmimages/Versions',
  'Locations/Artifact Publishers',
  'Locations/Capsoperations',
  'Galleries',
  'Galleries/Images',
  'Galleries/Images/Versions',
  'Locations/Galleries',
  'Payload Groups',
  'Galleries/Applications',
  'Galleries/Applications/Versions',
  'Locations/Diskoperations',
  'Disk Encryption Sets',
  'Restore Point Collections/Restore Points/Disk Restore Points',
  'Virtual Machine Scale Sets/Disks',
  'Cloud Services',
  'Cloud Services/Roles',
  'Cloud Services/Role Instances',
  'Locations/Csoperations',
  'Locations/Cloud Service Os Versions',
  'Locations/Cloud Service Os Families',
  'Cloud Services/Network Interfaces',
  'Cloud Services/Role Instances/Network Interfaces',
  'Cloud Services/Public Ipaddresses',
  'Storage Accounts/Blob Services',
  'Locations/Log Analytics',
  'Host Groups',
  'Host Groups/Hosts',
  'Components',
  'Components/Query',
  'Components/Metadata',
  'Components/Metrics',
  'Components/Events',
  'Components/Syntheticmonitorlocations',
  'Components/Analytics Items',
  'Components/Webtests',
  'Components/Work Item Configs',
  'Components/My Favorites',
  'Components/Operations',
  'Components/Export Configuration',
  'Components/Purge',
  'Components/Api',
  'Components/Aggregate',
  'Components/Metric Definitions',
  'Components/Extend Queries',
  'Components/Api Keys',
  'Components/My Analytics Items',
  'Components/Favorites',
  'Components/Annotations',
  'Components/Proactive Detection Configs',
  'Components/Move',
  'Components/Current Billing Features',
  'Components/Quota Status',
  'Components/Feature Capabilities',
  'Components/Get Available Billing Features',
  'Webtests',
  'Webtests/Get Test Result File',
  'Scheduledqueryrules',
  'Components/Pricing Plans',
  'Migrate To New Pricing Model',
  'Rollback To Legacy Pricing Model',
  'List Migrationdate',
  'Logprofiles',
  'Migratealertrules',
  'Metricalerts',
  'Alertrules',
  'Autoscalesettings',
  'Eventtypes',
  'Diagnostic Settings',
  'Diagnostic Settings Categories',
  'Extended Diagnostic Settings',
  'Metric Definitions',
  'Log Definitions',
  'Event Categories',
  'Metrics',
  'Metricbatch',
  'Metric Namespaces',
  'Notificationstatus',
  'Createnotifications',
  'Tenantactiongroups',
  'Actiongroups',
  'Activity Log Alerts',
  'Metricbaselines',
  'Workbooks',
  'My Workbooks',
  'Logs',
  'Transactions',
  'Topology',
  'Generate Live Token',
  'Monitored Objects',
  'Data Collection Rules',
  'Data Collection Rule Associations',
  'Data Collection Endpoints',
  'Private Link Scopes',
  'Private Link Scopes/Private Endpoint Connections',
  'Private Link Scopes/Private Endpoint Connection Proxies',
  'Private Link Scopes/Scoped Resources',
  'Locations/Diagnostic Operations',
  'Workspaces',
  'Querypacks',
  'Locations/Operation Statuses',
  'Workspaces/Scoped Private Link Proxies',
  'Workspaces/Api',
  'Workspaces/Query',
  'Workspaces/Metadata',
  'Workspaces/Purge',
  'Workspaces/Operations',
  'Workspaces/Data Sources',
  'Workspaces/Linked Storage Accounts',
  'Workspaces/Tables',
  'Workspaces/Storage Insight Configs',
  'Storage Insight Configs',
  'Workspaces/Linked Services',
  'Link Targets',
  'Deleted Workspaces',
  'Clusters',
  'Workspaces/Data Exports',
  'Vaults',
  'Locations/Backup Status',
  'Locations/Check Name Availability',
  'Locations/Allocated Stamp',
  'Locations/Allocate Stamp',
  'Locations/Backup Validate Features',
  'Locations/Backup Pre Validate Protection',
  'Locations/Backup Crr Jobs',
  'Locations/Backup Crr Job',
  'Locations/Backup Aad Properties',
  'Locations/Backup Cross Region Restore',
  'Locations/Backup Crr Operation Results',
  'Locations/Backup Crr Operations Status',
  'Backup Protected Items',
  'Replication Eligibility Results',
  'Locations/Capabilities',
  'Availability Statuses',
  'Child Availability Statuses',
  'Child Resources',
  'Events',
  'Emergingissues',
  'Security Statuses',
  'Tasks',
  'Secure Scores',
  'Secure Score Controls',
  'Secure Score Control Definitions',
  'Connectors',
  'Regulatory Compliance Standards',
  'Regulatory Compliance Standards/Regulatory Compliance Controls',
  'Regulatory Compliance Standards/Regulatory Compliance Controls/Regulatory Compliance Assessments',
  'Alerts',
  'Alerts Suppression Rules',
  'Auto Dismiss Alerts Rules',
  'Data Collection Agents',
  'Pricings',
  'Pricings/Security Operators',
  'Auto Provisioning Settings',
  'Mde Onboardings',
  'Vm Scanners',
  'Compliances',
  'Security Contacts',
  'Workspace Settings',
  'Compliance Results',
  'Policies',
  'Assessments',
  'Governance Rules',
  'Sub Assessments',
  'Security Solutions',
  'Locations/Security Solutions',
  'Discovered Security Solutions',
  'Locations/Discovered Security Solutions',
  'Allowed Connections',
  'Locations/Allowed Connections',
  'Topologies',
  'Locations/Topologies',
  'Security Solutions Reference Data',
  'Locations/Security Solutions Reference Data',
  'Jit Policies',
  'Jit Network Access Policies',
  'Locations/Jit Network Access Policies',
  'Security Statuses Summaries',
  'Application Whitelistings',
  'Locations/Alerts',
  'Locations/Tasks',
  'External Security Solutions',
  'Locations/External Security Solutions',
  'Information Protection Policies',
  'Advanced Threat Protection Settings',
  'Sql Vulnerability Assessments',
  'Device Security Groups',
  'Iot Security Solutions',
  'Iot Security Solutions/Analytics Models',
  'Iot Security Solutions/Iot Alert Types',
  'Iot Security Solutions/Iot Alerts',
  'Iot Security Solutions/Iot Recommendation Types',
  'Iot Security Solutions/Iot Recommendations',
  'Iot Security Solutions/Analytics Models/Aggregated Recommendations',
  'Settings',
  'Server Vulnerability Assessments',
  'Server Vulnerability Assessments Settings',
  'Adaptive Network Hardenings',
  'Automations',
  'Defender For Storage Settings',
  'Data Scanners',
  'Security Connectors',
  'Security Connectors/Devops',
  'Custom Recommendations',
  'Custom Assessment Automations',
  'Security Standards',
  'Standards',
  'Standard Assignments',
  'Assignments',
  'Sensitivity Settings',
  'Query',
  'Applications',
  'Api Collections',
  'Health Reports',
  'Aggregations',
  'Integrations',
  'Storage Accounts/Encryption Scopes',
  'Deleted Accounts',
  'Locations/Deleted Accounts',
  'Storage Tasks',
  'Locations/Asyncoperations',
  'Storage Accounts/List Account Sas',
  'Storage Accounts/List Service Sas',
  'Storage Accounts/Table Services',
  'Usages',
  'Check Name Availability',
  'Assessment Metadata',
  'Virtual Network Gateways',
  'Local Network Gateways',
  'Connections',
  'Application Gateways',
  'Express Route Circuits',
  'Express Route Service Providers',
  'Application Gateway Available Waf Rule Sets',
  'Application Gateway Available Ssl Options',
  'Application Gateway Available Request Headers',
  'Application Gateway Available Response Headers',
  'Route Filters',
  'Bgp Service Communities',
  'Vpn Sites',
  'Vpn Server Configurations',
  'Virtual Hubs',
  'Vpn Gateways',
  'P2S Vpn Gateways',
  'Express Route Gateways',
  'Express Route Ports Locations',
  'Express Route Ports',
  'Security Partner Providers',
  'Azure Firewalls',
  'Azure Firewall Fqdn Tags',
  'Application Gateway Web Application Firewall Policies',
  'Locations/Application Gateway Waf Dynamic Manifests',
  'Virtual Wans',
  'Bastion Hosts',
  'Query Express Route Ports Bandwidth',
  'Trafficmanagerprofiles',
  'Trafficmanagerprofiles/Heat Maps',
  'Trafficmanagerprofiles/Azureendpoints',
  'Trafficmanagerprofiles/Externalendpoints',
  'Trafficmanagerprofiles/Nestedendpoints',
  'Check Traffic Manager Name Availability',
  'Traffic Manager User Metrics Keys',
  'Traffic Manager Geographic Hierarchies',
  'Locations/Hybrid Edge Zone',
  'Firewall Policies',
  'Ip Groups',
  'Azure Web Categories',
  'Locations/Nfv Operations',
  'Locations/Nfv Operation Results',
  'Virtual Routers',
  'Network Virtual Appliances',
  'Network Virtual Appliance Skus',
  'Frontdoor Operation Results',
  'Check Frontdoor Name Availability',
  'Frontdoors',
  'Frontdoors/Frontend Endpoints',
  'Frontdoors/Frontend Endpoints/Custom Https Configuration',
  'Frontdoor Web Application Firewall Policies',
  'Frontdoor Web Application Firewall Managed Rule Sets',
  'Network Experiment Profiles',
  'Network Managers',
  'Network Manager Connections',
  'Locations/Query Network Security Perimeter',
  'Virtual Networks/List Network Manager Effective Security Admin Rules',
  'Network Group Memberships',
  'Locations/Commit Internal Azure Network Manager Configuration',
  'Locations/Internal Azure Virtual Network Manager Operation',
  'Dnszones',
  'Dns Operation Results',
  'Dns Operation Statuses',
  'Get Dns Resource Reference',
  'Internal Notify',
  'Dnszones/A',
  'Dnszones/Aaaa',
  'Dnszones/Cname',
  'Dnszones/Txt',
  'Dnszones/Srv',
  'Dnszones/Soa',
  'Dnszones/Ns',
  'Dnszones/Caa',
  'Dnszones/Ds',
  'Dnszones/Tlsa',
  'Dnszones/Naptr',
  'Dnszones/Recordsets',
  'Dnszones/All',
  'Dnszones/Dnssec Configs',
  'Dns Resolvers',
  'Dns Resolvers/Outbound Endpoints',
  'Dns Forwarding Rulesets',
  'Dns Forwarding Rulesets/Forwarding Rules',
  'Dns Forwarding Rulesets/Virtual Network Links',
  'Virtual Networks/List Dns Resolvers',
  'Virtual Networks/List Dns Forwarding Rulesets',
  'Locations/Dns Resolver Operation Results',
  'Locations/Dns Resolver Operation Statuses',
  'Locations/Dns Resolver Policy Operation Results',
  'Locations/Dns Resolver Policy Operation Statuses',
  'Private Dns Zones',
  'Private Dns Zones/Virtual Network Links',
  'Private Dns Operation Results',
  'Private Dns Operation Statuses',
  'Private Dns Zones Internal',
  'Private Dns Zones/A',
  'Private Dns Zones/Aaaa',
  'Private Dns Zones/Cname',
  'Private Dns Zones/Ptr',
  'Private Dns Zones/Mx',
  'Private Dns Zones/Txt',
  'Private Dns Zones/Srv',
  'Private Dns Zones/Soa',
  'Private Dns Zones/All',
  'Virtual Networks/Private Dns Zone Links',
  'Virtual Networks/Tagged Traffic Consumers',
  'Nat Gateways',
  'Internal Public Ip Addresses',
  'Custom Ip Prefixes',
  'Dscp Configurations',
  'Private Endpoints',
  'Private Endpoints/Private Link Service Proxies',
  'Private Endpoint Redirect Maps',
  'Load Balancers',
  'Network Security Groups',
  'Application Security Groups',
  'Service Endpoint Policies',
  'Network Intent Policies',
  'Route Tables',
  'Public Ipprefixes',
  'Network Watchers',
  'Network Watchers/Flow Logs',
  'Network Watchers/Ping Meshes',
  'Locations/Check Dns Name Availability',
  'Locations/Set Load Balancer Frontend Public Ip Addresses',
  'Cloud Service Slots',
  'Locations/Virtual Network Available Endpoint Services',
  'Locations/Available Delegations',
  'Locations/Service Tags',
  'Locations/Available Private Endpoint Types',
  'Locations/Available Service Aliases',
  'Dnszones/Mx',
  'Locations/Batch Notify Private Endpoints For Resource Move',
  'Locations/Supported Virtual Machine Sizes',
  'Locations/Set Azure Network Manager Configuration',
  'Locations/Publish Resources',
  'Locations/Get Azure Network Manager Configuration',
  'Locations/Check Accelerated Networking Support',
  'Locations/Validate Resource Ownership',
  'Locations/Set Resource Ownership',
  'Locations/Effective Resource Ownership',
  'Virtual Network Taps',
  'Private Link Services',
  'Locations/Private Link Services',
  'Ddos Protection Plans',
  'Network Profiles',
  'Locations/Bare Metal Tenants',
  'Ip Allocations',
  'Locations/Service Tag Details',
  'Locations/Data Tasks',
  'Locations/Database Azure Async Operation',
  'Locations/Database Operation Results',
  'Locations/Database Encryption Protector Revalidate Operation Results',
  'Locations/Database Encryption Protector Revert Azure Async Operation',
  'Locations/Database Encryption Protector Revert Operation Results',
  'Locations/Server Key Azure Async Operation',
  'Locations/Server Key Operation Results',
  'Servers/Keys',
  'Servers/Encryption Protector',
  'Locations/Encryption Protector Operation Results',
  'Locations/Encryption Protector Azure Async Operation',
  'Locations/External Policy Based Authorizations Azure Asyc Operation',
  'Locations/External Policy Based Authorizations Operation Results',
  'Locations/Refresh External Governance Status Operation Results',
  'Locations/Refresh External Governance Status Azure Async Operation',
  'Locations/Refresh External Governance Status Mioperation Results',
  'Locations/Refresh External Governance Status Miazure Async Operation',
  'Locations/Managed Instance Key Azure Async Operation',
  'Locations/Managed Instance Key Operation Results',
  'Locations/Managed Instance Encryption Protector Operation Results',
  'Locations/Managed Instance Encryption Protector Azure Async Operation',
  'Locations/Transparent Data Encryption Azure Async Operation',
  'Locations/Transparent Data Encryption Operation Results',
  'Locations/Managedtransparent Data Encryption Azure Async Operation',
  'Locations/Managedtransparent Data Encryption Operation Results',
  'Servers/Tde Certificates',
  'Locations/Tde Cert Azure Async Operation',
  'Locations/Tde Cert Operation Results',
  'Locations/Server Azure Async Operation',
  'Locations/Server Operation Results',
  'Servers',
  'Servers/Databases',
  'Servers/Service Objectives',
  'Servers/Communication Links',
  'Servers/Administrators',
  'Locations/Server Administrator Azure Async Operation',
  'Locations/Server Administrator Operation Results',
  'Servers/Restorable Dropped Databases',
  'Servers/Recoverable Databases',
  'Servers/Databases/Geo Backup Policies',
  'Servers/Import',
  'Servers/Import Export Operation Results',
  'Servers/Operation Results',
  'Servers/Databases/Backup Long Term Retention Policies',
  'Servers/Vulnerability Assessments',
  'Locations/Auto Approved Private Link Services',
  'Servers/Automatic Tuning',
  'Servers/Databases/Automatic Tuning',
  'Servers/Databases/Transparent Data Encryption',
  'Servers/Databases/Ledger Digest Uploads',
  'Locations/Ledger Digest Uploads Azure Async Operation',
  'Locations/Ledger Digest Uploads Operation Results',
  'Servers/Recommended Elastic Pools',
  'Servers/Databases/Data Masking Policies',
  'Servers/Databases/Data Masking Policies/Rules',
  'Servers/Databases/Security Alert Policies',
  'Servers/Security Alert Policies',
  'Servers/Advanced Threat Protection Settings',
  'Managed Instances/Databases/Advanced Threat Protection Settings',
  'Managed Instances/Advanced Threat Protection Settings',
  'Servers/Databases/Auditing Settings',
  'Servers/Auditing Settings',
  'Servers/Extended Auditing Settings',
  'Servers/Dev Ops Auditing Settings',
  'Locations/Auditing Settings Azure Async Operation',
  'Locations/Auditing Settings Operation Results',
  'Locations/Extended Auditing Settings Azure Async Operation',
  'Locations/Extended Auditing Settings Operation Results',
  'Locations/Dev Ops Auditing Settings Operation Results',
  'Locations/Dev Ops Auditing Settings Azure Async Operation',
  'Locations/Elastic Pool Azure Async Operation',
  'Locations/Elastic Pool Operation Results',
  'Servers/Elasticpools',
  'Servers/Job Accounts',
  'Servers/Job Agents',
  'Locations/Job Agent Operation Results',
  'Locations/Job Agent Azure Async Operation',
  'Servers/Job Agents/Private Endpoints',
  'Locations/Job Agent Private Endpoint Azure Async Operation',
  'Servers/Job Agents/Jobs',
  'Servers/Job Agents/Jobs/Steps',
  'Servers/Job Agents/Jobs/Executions',
  'Servers/Disaster Recovery Configuration',
  'Servers/Dns Aliases',
  'Locations/Dns Alias Async Operation',
  'Locations/Dns Alias Operation Results',
  'Servers/Failover Groups',
  'Locations/Failover Group Azure Async Operation',
  'Locations/Failover Group Operation Results',
  'Locations/Firewall Rules Operation Results',
  'Locations/Firewall Rules Azure Async Operation',
  'Locations/Ipv6Firewall Rules Operation Results',
  'Locations/Ipv6Firewall Rules Azure Async Operation',
  'Locations/Delete Virtual Network Or Subnets',
  'Servers/Virtual Network Rules',
  'Locations/Virtual Network Rules Operation Results',
  'Locations/Virtual Network Rules Azure Async Operation',
  'Locations/Delete Virtual Network Or Subnets Operation Results',
  'Locations/Delete Virtual Network Or Subnets Azure Async Operation',
  'Locations/Database Restore Azure Async Operation',
  'Servers/Usages',
  'Servers/Databases/Metric Definitions',
  'Servers/Databases/Metrics',
  'Servers/Aggregated Database Metrics',
  'Servers/Elasticpools/Metrics',
  'Servers/Elasticpools/Metricdefinitions',
  'Servers/Databases/Top Queries',
  'Servers/Advisors',
  'Servers/Elastic Pools/Advisors',
  'Servers/Databases/Advisors',
  'Servers/Databases/Extensions',
  'Servers/Elastic Pool Estimates',
  'Servers/Databases/Audit Records',
  'Servers/Databases/Vulnerability Assessment Scans',
  'Servers/Databases/Workload Groups',
  'Servers/Databases/Vulnerability Assessments',
  'Servers/Database Security Policies',
  'Servers/Databases/Vulnerability Assessment Settings',
  'Servers/Databases/Vulnerability Assessment',
  'Locations/Vulnerability Assessment Scan Azure Async Operation',
  'Locations/Vulnerability Assessment Scan Operation Results',
  'Servers/Databases/Sqlvulnerabilityassessments',
  'Servers/Sqlvulnerabilityassessments',
  'Locations/Sql Vulnerability Assessment Operation Results',
  'Servers/Databases/Recommended Sensitivity Labels',
  'Servers/Databases/Sync Groups',
  'Servers/Databases/Sync Groups/Sync Members',
  'Servers/Sync Agents',
  'Instance Pools',
  'Locations/Import Export Operation Results',
  'Locations/Import Export Azure Async Operation',
  'Locations/Instance Pool Operation Results',
  'Locations/Instance Pool Azure Async Operation',
  'Managed Instances',
  'Managed Instances/Administrators',
  'Managed Instances/Databases',
  'Managed Instances/Recoverable Databases',
  'Managed Instances/Metrics',
  'Managed Instances/Metric Definitions',
  'Managed Instances/Databases/Backup Long Term Retention Policies',
  'Managed Instances/Sql Agent',
  'Managed Instances/Start Stop Schedules',
  'Locations/Managed Instance Private Endpoint Connection Proxy Operation Results',
  'Locations/Managed Instance Private Endpoint Connection Operation Results',
  'Locations/Managed Instance Private Endpoint Connection Azure Async Operation',
  'Locations/Long Term Retention Managed Instances',
  'Locations/Long Term Retention Managed Instance Backups',
  'Locations/Managed Instance Long Term Retention Policy Operation Results',
  'Locations/Managed Instance Long Term Retention Policy Azure Async Operation',
  'Locations/Long Term Retention Managed Instance Backup Operation Results',
  'Locations/Long Term Retention Managed Instance Backup Azure Async Operation',
  'Locations/Managed Database Azure Async Operation',
  'Locations/Managed Database Operation Results',
  'Locations/Managed Database Restore Azure Async Operation',
  'Locations/Managed Database Restore Operation Results',
  'Locations/Managed Database Complete Restore Azure Async Operation',
  'Locations/Managed Database Complete Restore Operation Results',
  'Locations/Managed Server Security Alert Policies Azure Async Operation',
  'Locations/Stop Managed Instance Azure Async Operation',
  'Locations/Stop Managed Instance Operation Results',
  'Locations/Start Managed Instance Azure Async Operation',
  'Locations/Start Managed Instance Operation Results',
  'Managed Instances/Tde Certificates',
  'Locations/Managed Instance Tde Cert Azure Async Operation',
  'Locations/Managed Instance Tde Cert Operation Results',
  'Locations/Managed Server Security Alert Policies Operation Results',
  'Locations/Security Alert Policies Azure Async Operation',
  'Locations/Security Alert Policies Operation Results',
  'Locations/Advanced Threat Protection Azure Async Operation',
  'Locations/Managed Instance Advanced Threat Protection Azure Async Operation',
  'Locations/Managed Instance Advanced Threat Protection Operation Results',
  'Managed Instances/Dns Aliases',
  'Locations/Managed Dns Alias Async Operation',
  'Locations/Managed Dns Alias Operation Results',
  'Virtual Clusters',
  'Locations/Virtual Cluster Azure Async Operation',
  'Locations/Virtual Cluster Operation Results',
  'Locations/Update Managed Instance Dns Servers Azure Async Operation',
  'Locations/Update Managed Instance Dns Servers Operation Results',
  'Locations/Managed Instance Azure Async Operation',
  'Locations/Managed Instance Operation Results',
  'Managed Instances/Vulnerability Assessments',
  'Locations/Server Trust Certificates Operation Results',
  'Locations/Server Trust Certificates Azure Async Operation',
  'Locations/Administrator Azure Async Operation',
  'Locations/Administrator Operation Results',
  'Locations/Sync Group Operation Results',
  'Locations/Sync Group Azure Async Operation',
  'Locations/Sync Member Operation Results',
  'Locations/Sync Agent Operation Results',
  'Locations/Sync Database Ids',
  'Locations/Long Term Retention Servers',
  'Locations/Long Term Retention Backups',
  'Locations/Long Term Retention Policy Azure Async Operation',
  'Locations/Long Term Retention Backup Operation Results',
  'Locations/Long Term Retention Backup Azure Async Operation',
  'Locations/Change Long Term Retention Backup Access Tier Operation Results',
  'Locations/Change Long Term Retention Backup Access Tier Azure Async Operation',
  'Locations/Short Term Retention Policy Operation Results',
  'Locations/Short Term Retention Policy Azure Async Operation',
  'Locations/Managed Short Term Retention Policy Operation Results',
  'Locations/Managed Short Term Retention Policy Azure Async Operation',
  'Locations/Instance Failover Groups',
  'Locations/Instance Failover Group Azure Async Operation',
  'Locations/Instance Failover Group Operation Results',
  'Locations/Private Endpoint Connection Proxy Operation Results',
  'Locations/Private Endpoint Connection Proxy Azure Async Operation',
  'Locations/Private Endpoint Connection Operation Results',
  'Locations/Outbound Firewall Rules Azure Async Operation',
  'Locations/Outbound Firewall Rules Operation Results',
  'Locations/Private Endpoint Connection Azure Async Operation',
  'Locations/Notify Azure Async Operation',
  'Locations/Server Trust Groups',
  'Locations/Server Trust Group Operation Results',
  'Locations/Server Trust Group Azure Async Operation',
  'Locations/Managed Database Move Operation Results',
  'Servers/Connection Policies',
  'Locations/Connection Policies Azure Async Operation',
  'Locations/Replication Links Azure Async Operation',
  'Locations/Replication Links Operation Results',
  'Locations/Managed Instance Dtc Azure Async Operation',
  'Managed Instances/Databases/Ledger Digest Uploads',
  'Locations/Managed Ledger Digest Uploads Operation Results',
  'Locations/Managed Ledger Digest Uploads Azure Async Operation',
  'Locations/Server Configuration Option Azure Async Operation',
  'Servers/Failover Groups/Try Planned Before Forced Failover',
  'Resource Providers',
  'Resources',
  'Reservation Orders',
  'Reservation Orders/Reservations',
  'Listbenefits',
  'Reservations',
  'Reservation Orders/Reservations/Revisions',
  'Catalogs',
  'Applied Reservations',
  'Check Offers',
  'Check Scopes',
  'Calculate Price',
  'Calculate Exchange',
  'Exchange',
  'Reservation Orders/Return',
  'Reservation Orders/Split',
  'Reservation Orders/Merge',
  'Reservation Orders/Swap',
  'Validate Reservation Order',
  'Reservation Orders/Available Scopes',
  'Reservation Orders/Reservations/Available Scopes',
  'Commercial Reservation Orders',
  'Locations/Distributed Availability Groups Azure Async Operation',
  'Own Reservations',
  'Alerts Summary',
  'Smart Groups',
  'Smart Detector Alert Rules',
  'Migrate From Smart Detection',
  'Action Rules',
  'Alerts Meta Data',
  'Prometheus Rule Groups',
  'Alert Rule Recommendations',
  'Tenant Activity Log Alerts',
  'Reviewsnotifications',
  'Migrateprojects',
  'Assessment Projects',
  'Move Collections',
  'Locations/Rms Operation Results',
  'Modernize Projects',
  'Locations/Event Subscriptions',
  'Event Subscriptions',
  'Topics',
  'Domains',
  'Domains/Topics',
  'Topic Types',
  'Locations/Operations Status',
  'Locations/Topic Types',
  'Extension Topics',
  'Operation Results',
  'Operations Status',
  'System Topics',
  'System Topics/Event Subscriptions',
  'Partner Registrations',
  'Partner Configurations',
  'Verified Partners',
  'Namespaces',
  'Partner Namespaces',
  'Place Purchase Order',
  'Partner Namespaces/Event Channels',
  'Partner Namespaces/Channels',
  'Partner Destinations',
  'Organizations',
  'Registered Subscriptions',
  'Monitors',
  'Monitors/Tag Rules',
  'Get Marketplace Saa Sresource Details',
  'Monitors/List Hosts',
  'Monitors/List Monitored Resources',
  'Monitors/List App Services',
  'Network Settings',
  'Domain Services',
  'Domain Services/Oucontainer',
  'Azure Admetrics',
  'Private Link For Azure Ad',
  'Tenants',
  'Support Providers',
  'Services',
  'Addsservices',
  'Configuration',
  'Agents',
  'Aadsupportcases',
  'Reports',
  'Servicehealthmetrics',
  'Anonymousapiusers',
  'Farm Beats Extension Definitions',
  'Farm Beats Solution Definitions',
  'Service',
  'Deleted Services',
  'Locations/Deleted Services',
  'Validate Service Name',
  'Check Service Name Availability',
  'Report Feedback',
  'Check Feedback Required',
  'Partner Topics/Event Subscriptions',
  'Service/Event Grid Filters',
  'Api Collections Meta',
  'Api Collections Meta/Api Collection Meta Details',
  'Managed Environments',
  'Managed Environments/Certificates',
  'Managed Environments/Managed Certificates',
  'Container Apps',
  'Container Apps/Private Endpoint Connection Proxies',
  'Managed Environments/Private Endpoint Connection Proxies',
  'Jobs',
  'Locations/Managed Environment Operation Results',
  'Locations/Managed Environment Operation Statuses',
  'Locations/Containerapp Operation Results',
  'Locations/Containerapp Operation Statuses',
  'Locations/Containerappsjob Operation Results',
  'Locations/Containerappsjob Operation Statuses',
  'Locations/Source Control Operation Results',
  'Locations/Source Control Operation Statuses',
  'Connected Environments',
  'Locations/Connected Environment Operation Results',
  'Locations/Connected Environment Operation Statuses',
  'Locations/Managed Certificate Operation Statuses',
  'Locations/Billing Meters',
  'Locations/Available Managed Environments Workload Profile Types',
  'Get Custom Domain Verification Id',
  'Builders',
  'Builders/Builds',
  'Managed Environments/Dot Net Components',
  'Managed Environments/Java Components',
  'Managed Environments/Dapr Components',
  'Locations/Os Versions',
  'Reports/Snapshots',
  'Onboard',
  'Trigger Evaluation',
  'Reports/Webhooks',
  'Reports/Evidences',
  'Get Collection Count',
  'Get Overview Status',
  'Reports/Scoping Configurations',
  'Configuration Stores',
  'Configuration Stores/Key Values',
  'Configuration Stores/Event Grid Filters',
  'Deleted Configuration Stores',
  'Locations/Deleted Configuration Stores',
  'Configuration Stores/Replicas',
  'Configuration Stores/Snapshots',
  'Get Domain Ownership Identifier',
  'Spring/Operation Results',
  'Spring/Operation Statuses',
  'Spring/Apps',
  'Spring/Apps/Operation Results',
  'Spring/Apps/Operation Statuses',
  'Spring/Apps/Deployments/Operation Results',
  'Spring/Apps/Deployments/Operation Statuses',
  'Spring/Config Servers',
  'Spring/Config Servers/Operation Results',
  'Spring/Config Servers/Operation Statuses',
  'Spring/Eureka Servers',
  'Spring/Eureka Servers/Operation Results',
  'Spring/Eureka Servers/Operation Statuses',
  'Spring/Apps/Domains',
  'Spring/Apps/Domains/Operation Results',
  'Spring/Apps/Domains/Operation Statuses',
  'Runtime Versions',
  'Locations/Operation Status',
  'Arc Nw Load Balancers',
  'Attestation Providers',
  'Default Providers',
  'Role Assignment Schedule Requests',
  'Role Eligibility Schedule Requests',
  'Role Assignment Schedules',
  'Role Eligibility Schedules',
  'Role Assignment Schedule Instances',
  'Role Eligibility Schedule Instances',
  'Role Management Policies',
  'Role Management Policy Assignments',
  'Eligible Child Resources',
  'Role Management Alerts',
  'Role Management Alert Configurations',
  'Role Management Alert Definitions',
  'Role Management Alert Operations',
  'Role Assignments',
  'Role Definitions',
  'Classic Administrators',
  'Permissions',
  'Deny Assignments',
  'Locks',
  'Policy Definitions/Versions',
  'Policy Set Definitions',
  'Policy Set Definitions/Versions',
  'Policy Assignments',
  'Policy Exemptions',
  'List Policy Definition Versions',
  'List Policy Set Definition Versions',
  'Data Aliases',
  'Data Policy Manifests',
  'Provider Operations',
  'Elevate Access',
  'Check Access',
  'Batch Resource Check Access',
  'Find Orphan Role Assignments',
  'Role Assignments Usage Metrics',
  'Access Review Schedule Definitions',
  'Access Review Schedule Settings',
  'Access Review History Definitions',
  'Private Link Associations',
  'Spring',
  'Operation Status',
  'Configuration Profile Assignments',
  'Configuration Profiles',
  'Configuration Profiles/Versions',
  'Best Practices',
  'Best Practices/Versions',
  'Service Principals',
  'Automation Accounts',
  'Deleted Automation Accounts',
  'Automation Accounts/Runbooks',
  'Automation Accounts/Configurations',
  'Automation Accounts/Webhooks',
  'Automation Accounts/Software Update Configurations',
  'Automation Accounts/Software Update Configuration Machine Runs',
  'Automation Accounts/Jobs',
  'Automation Accounts/Private Link Resources',
  'Automation Accounts/Private Endpoint Connections',
  'Automation Accounts/Private Endpoint Connection Proxies',
  'Automation Accounts/Hybrid Runbook Worker Groups',
  'Automation Accounts/Hybrid Runbook Worker Groups/Hybrid Runbook Workers',
  'Automation Accounts/Agent Registration Information',
  'Workspaces/Eventgridfilters',
  'Locations/Check Quota Availability',
  'Locations/Check Trial Availability',
  'Private Clouds',
  'Private Clouds/Addons',
  'Private Clouds/Authorizations',
  'Private Clouds/Cloud Links',
  'Private Clouds/Clusters',
  'Private Clouds/Clusters/Datastores',
  'Private Clouds/Clusters/Virtual Machines',
  'Private Clouds/Event Grid Filters',
  'Private Clouds/Global Reach Connections',
  'Private Clouds/Hcx Enterprise Sites',
  'Private Clouds/Script Executions',
  'Private Clouds/Script Packages',
  'Private Clouds/Script Packages/Script Cmdlets',
  'Private Clouds/Workload Networks',
  'Private Clouds/Workload Networks/Dhcp Configurations',
  'Private Clouds/Workload Networks/Dns Services',
  'Private Clouds/Workload Networks/Dns Zones',
  'Private Clouds/Workload Networks/Gateways',
  'Private Clouds/Workload Networks/Port Mirroring Profiles',
  'Private Clouds/Workload Networks/Public Ips',
  'Private Clouds/Workload Networks/Segments',
  'Private Clouds/Workload Networks/Virtual Machines',
  'Private Clouds/Workload Networks/Vm Groups',
  'Guest Usages',
  'B2C Directories',
  'B2Ctenants',
  'Data Controllers',
  'Sql Managed Instances',
  'Enable Private Link Network Access',
  'Data Controllers/Active Directory Connectors',
  'Sql Server Instances/Databases',
  'Sql Managed Instances/Failover Groups',
  'Sql Server Instances/Availability Groups',
  'Sql Server Licenses',
  'Azure Large Instances',
  'Azure Large Storage Instances',
  'Accounts',
  'Locations/Quotas',
  'Scanning Accounts',
  'Catalogs/Products',
  'Catalogs/Products/Devicegroups',
  'Catalogs/Certificates',
  'Catalogs/Images',
  'Catalogs/Products/Devicegroups/Deployments',
  'Registrations',
  'Registrations/Products',
  'Registrations/Customer Subscriptions',
  'Cloud Manifest Files',
  'Linked Subscriptions',
  'Generate Deployment License',
  'Gallery Images',
  'Network Interfaces',
  'Virtual Networks',
  'Virtual Hard Disks',
  'Clusters/Arc Settings',
  'Clusters/Arc Settings/Extensions',
  'Virtual Machines/Hybrididentitymetadata',
  'Clusters/Publishers',
  'Clusters/Offers',
  'Clusters/Publishers/Offers',
  'Marketplace Gallery Images',
  'Storage Containers',
  'Clusters/Updates',
  'Clusters/Updates/Update Runs',
  'Clusters/Update Summaries',
  'Virtual Machine Instances',
  'Clusters/Deployment Settings',
  'Edge Devices',
  'Logical Networks',
  'Clusters/Security Settings',
  'Vmware Applications',
  'Bare Metal Connections',
  'Sql Server Instances',
  'Utilization',
  'Bare Metal Instances',
  'Batch Accounts',
  'Batch Accounts/Pools',
  'Batch Accounts/Detectors',
  'Batch Accounts/Certificates',
  'Batch Accounts/Operation Results',
  'Batch Accounts/Pool Operation Results',
  'Batch Accounts/Certificate Operation Results',
  'Batch Accounts/Private Endpoint Connection Proxy Results',
  'Batch Accounts/Private Endpoint Connection Results',
  'Locations/Account Operation Results',
  'Locations/Virtual Machine Skus',
  'Locations/Cloud Service Skus',
  'Billing Periods',
  'Invoices',
  'Enrollment Accounts',
  'Permission Requests',
  'Billing Accounts/Permission Requests',
  'Billing Accounts/Associated Tenants',
  'Billing Role Definitions',
  'Billing Role Assignments',
  'Create Billing Role Assignment',
  'Billing Accounts/Sign Agreement',
  'Billing Accounts/Preview Agreements',
  'Billing Accounts/Billing Profiles/Create Billing Role Assignment',
  'Billing Accounts/Billing Profiles/Invoice Sections/Create Billing Role Assignment',
  'Billing Accounts/Customers/Create Billing Role Assignment',
  'Billing Permissions',
  'Billing Accounts/Billing Role Definitions',
  'Billing Accounts/Billing Role Assignments',
  'Billing Accounts/Billing Permissions',
  'Billing Accounts',
  'Billing Accounts/Billing Profiles Summaries',
  'Billing Accounts/Billing Profiles/Billing Role Definitions',
  'Billing Accounts/Billing Profiles/Billing Role Assignments',
  'Billing Accounts/Billing Profiles/Billing Permissions',
  'Billing Accounts/Customers',
  'Billing Accounts/Billing Profiles/Customers',
  'Billing Accounts/Billing Profiles/Instructions',
  'Billing Accounts/Customers/Billing Subscriptions',
  'Billing Accounts/Customers/Products',
  'Billing Accounts/Customers/Transactions',
  'Billing Accounts/Invoice Sections',
  'Billing Accounts/Billing Profiles/Invoice Sections',
  'Billing Accounts/Billing Profiles/Invoice Sections/Billing Role Assignments',
  'Billing Accounts/Billing Profiles/Invoice Sections/Billing Permissions',
  'Billing Accounts/Customers/Billing Role Definitions',
  'Billing Accounts/Billing Profiles/Customers/Billing Role Definitions',
  'Billing Accounts/Customers/Billing Role Assignments',
  'Billing Accounts/Billing Profiles/Customers/Billing Role Assignments',
  'Billing Accounts/Customers/Billing Permissions',
  'Billing Accounts/Billing Profiles/Customers/Billing Permissions',
  'Billing Accounts/Invoice Sections/Elevate',
  'Billing Accounts/Create Invoice Section Operations',
  'Billing Accounts/Patch Operations',
  'Billing Accounts/Invoice Sections/Patch Operations',
  'Billing Accounts/Invoice Sections/Product Move Operations',
  'Billing Accounts/Invoice Sections/Billing Subscription Move Operations',
  'Departments',
  'Billing Accounts/Departments',
  'Billing Accounts/Billing Profiles/Departments',
  'Billing Accounts/Notification Contacts',
  'Billing Accounts/Billing Profiles/Notification Contacts',
  'Billing Accounts/Departments/Billing Role Definitions',
  'Billing Accounts/Departments/Billing Role Assignments',
  'Billing Accounts/Billing Profiles/Departments/Billing Role Assignments',
  'Billing Accounts/Departments/Billing Permissions',
  'Billing Accounts/Billing Profiles/Departments/Billing Permissions',
  'Billing Accounts/Enrollment Accounts',
  'Billing Accounts/Departments/Enrollment Accounts',
  'Billing Accounts/Billing Profiles/Enrollment Accounts',
  'Billing Accounts/Billing Profiles/Departments/Enrollment Accounts',
  'Billing Accounts/Enrollment Accounts/Billing Role Definitions',
  'Billing Accounts/Enrollment Accounts/Billing Role Assignments',
  'Billing Accounts/Enrollment Accounts/Billing Permissions',
  'Billing Accounts/Billing Profiles/Enrollment Accounts/Billing Permissions',
  'Billing Accounts/Enrollment Accounts/Billing Subscriptions',
  'Billing Accounts/Departments/Billing Subscriptions',
  'Billing Accounts/Billing Profiles/Payment Methods',
  'Billing Accounts/Available Balance',
  'Billing Accounts/Billing Profiles/Available Balance',
  'Billing Accounts/Invoices',
  'Billing Accounts/Billing Profiles/Invoices',
  'Billing Accounts/Transactions',
  'Billing Accounts/Billing Profiles/Transactions',
  'Billing Accounts/Invoice Sections/Transactions',
  'Billing Accounts/Billing Profiles/Invoice Sections/Transactions',
  'Billing Accounts/Billing Profiles/Invoices/Transactions',
  'Billing Accounts/Invoices/Transactions',
  'Billing Accounts/Invoices/Summary',
  'Billing Accounts/Billing Profiles/Invoice Sections/Validate Delete Invoice Section Eligibility',
  'Billing Accounts/Invoices/Transaction Summary',
  'Billing Accounts/Billing Subscriptions',
  'Billing Accounts/Billing Subscription Aliases',
  'Billing Accounts/Billing Subscriptions/Invoices',
  'Billing Accounts/Billing Subscriptions/Policies',
  'Billing Accounts/Billing Profiles/Billing Subscriptions',
  'Billing Accounts/Billing Profiles/Departments/Billing Subscriptions',
  'Billing Accounts/Billing Profiles/Enrollment Accounts/Billing Subscriptions',
  'Billing Accounts/Invoice Sections/Billing Subscriptions',
  'Billing Accounts/Billing Profiles/Invoice Sections/Billing Subscriptions',
  'Billing Accounts/Invoice Sections/Products',
  'Billing Accounts/Billing Profiles/Invoice Sections/Products',
  'Billing Accounts/Invoice Sections/Products/Update Auto Renew',
  'Billing Accounts/Billing Profiles/Invoice Sections/Products/Update Auto Renew',
  'Billing Accounts/Billing Profiles/Products',
  'Billing Accounts/Products',
  'Billing Accounts/Invoice Sections/Initiate Transfer',
  'Billing Accounts/Billing Profiles/Invoice Sections/Initiate Transfer',
  'Billing Accounts/Invoice Sections/Transfers',
  'Billing Accounts/Billing Profiles/Invoice Sections/Transfers',
  'Transfers/Accept Transfer',
  'Transfers',
  'Transfers/Decline Transfer',
  'Transfers/Validate Transfer',
  'Billing Accounts/Customers/Initiate Transfer',
  'Billing Accounts/Customers/Transfers',
  'Billing Accounts/Customers/Transfer Supported Accounts',
  'Billing Property',
  'Billing Accounts/Billing Profiles',
  'Billing Accounts/Billing Profiles/Policies',
  'Billing Accounts/Customers/Policies',
  'Billing Accounts/Billing Profiles/Invoices/Pricesheet',
  'Billing Accounts/Billing Profiles/Pricesheet',
  'Billing Accounts/Invoice Sections/Products/Transfer',
  'Billing Accounts/Invoice Sections/Product Transfers Results',
  'Billing Accounts/Agreements',
  'Billing Accounts/Line Of Credit',
  'Billing Accounts/Payment Methods',
  'Payment Methods',
  'Billing Accounts/Billing Profiles/Payment Method Links',
  'Billing Accounts/Payable Overage',
  'Billing Accounts/Pay Now',
  'Billing Accounts/Reservation Orders',
  'Billing Accounts/Reservation Orders/Reservations',
  'Billing Accounts/Reservations',
  'Billing Accounts/Billing Profiles/Reservations',
  'Billing Accounts/Billing Profiles/Validate Detach Payment Method Eligibility',
  'Validate Address',
  'Promotions',
  'Promotions/Checkeligibility',
  'Billing Accounts/Billing Subscriptions/Elevate Role',
  'Billing Accounts/Applied Reservation Orders',
  'Promotional Credits',
  'Billing Accounts/Promotional Credits',
  'Billing Accounts/Savings Plan Orders/Savings Plans',
  'Billing Accounts/Savings Plan Orders',
  'Billing Accounts/Savings Plans',
  'Billing Accounts/Alerts',
  'Billing Accounts/Billing Profiles/Alerts',
  'Billing Accounts/Incentive Schedules',
  'Billing Accounts/Incentive Schedules/Milestones',
  'Transfers/Operation Status',
  'Billing Accounts/Operation Results',
  'Pools',
  'Billing Accounts/Billing Profiles/Invoices/Operation Results',
  'Billing Accounts/Billing Profiles/Pricesheet Download Operations',
  'Billing Accounts/Billing Subscriptions/Operation Results',
  'Billing Accounts/Billing Subscriptions/Invoices/Operation Results',
  'Billing Accounts/Enrollment Accounts/Activation Status',
  'Billing Accounts/Invoices/Operation Results',
  'Promotional Credits/Operation Results',
  'Billing Accounts/Addresses',
  'Savings Plan Orders',
  'Savings Plan Orders/Savings Plans',
  'Savings Plan Orders/Return',
  'Validate',
  'Calculate Migration Cost',
  'Savings Plan Order Aliases',
  'Reservation Order Aliases',
  'Savings Plans',
  'Incentive Schedules',
  'Maccs',
  'Maccs/Contributors',
  'List Seller Resources',
  'Credits',
  'Accounts/Skus',
  'Accounts/Usages',
  'Blueprints',
  'Blueprints/Artifacts',
  'Blueprints/Versions',
  'Billing Accounts/Policies',
  'Blueprint Assignments/Assignment Operations',
  'Bot Services',
  'Bot Services/Channels',
  'Bot Services/Connections',
  'List Auth Service Providers',
  'List Qn Amaker Endpoint Keys',
  'Host Settings',
  'Bot Services/Private Endpoint Connection Proxies',
  'Bot Services/Private Endpoint Connections',
  'Bot Services/Private Link Resources',
  'Redis',
  'Redis/Private Endpoint Connection Proxies',
  'Redis/Private Endpoint Connection Proxies/Validate',
  'Redis/Private Endpoint Connections',
  'Redis/Private Link Resources',
  'Redis Enterprise',
  'Redis Enterprise/Private Endpoint Connection Proxies',
  'Redis Enterprise/Private Endpoint Connection Proxies/Validate',
  'Redis Enterprise/Private Endpoint Connection Proxies/Operationresults',
  'Redis Enterprise/Private Endpoint Connections',
  'Redis Enterprise/Private Endpoint Connections/Operationresults',
  'Redis Enterprise/Private Link Resources',
  'Redis Enterprise/Databases',
  'Redis/Event Grid Filters',
  'Carbon Emission Reports',
  'Query Carbon Emission Data Available Date Range',
  'Profiles',
  'Profiles/Endpoints',
  'Profiles/Endpoints/Origins',
  'Profiles/Endpoints/Customdomains',
  'Operationresults/Profileresults',
  'Operationresults/Profileresults/Endpointresults',
  'Operationresults/Profileresults/Endpointresults/Originresults',
  'Operationresults/Profileresults/Endpointresults/Origingroupresults',
  'Operationresults/Profileresults/Endpointresults/Customdomainresults',
  'Check Endpoint Name Availability',
  'Check Resource Usage',
  'Validate Probe',
  'Can Migrate',
  'Migrate',
  'Edgenodes',
  'Cdn Web Application Firewall Policies',
  'Operationresults/Cdnwebapplicationfirewallpolicyresults',
  'Cdn Web Application Firewall Managed Rule Sets',
  'Profiles/Afdendpoints',
  'Profiles/Afdendpoints/Routes',
  'Profiles/Customdomains',
  'Profiles/Origingroups',
  'Profiles/Origingroups/Origins',
  'Profiles/Rulesets',
  'Profiles/Rulesets/Rules',
  'Profiles/Secrets',
  'Validate Secret',
  'Blueprint Assignments',
  'Operationresults/Profileresults/Afdendpointresults',
  'Operationresults/Profileresults/Afdendpointresults/Routeresults',
  'Operationresults/Profileresults/Customdomainresults',
  'Operationresults/Profileresults/Origingroupresults',
  'Operationresults/Profileresults/Origingroupresults/Originresults',
  'Operationresults/Profileresults/Rulesetresults',
  'Operationresults/Profileresults/Rulesetresults/Ruleresults',
  'Operationresults/Profileresults/Secretresults',
  'Operationresults/Profileresults/Securitypolicyresults',
  'Profiles/Policies',
  'Profiles/Networkpolicies',
  'Certificate Orders',
  'Certificate Orders/Certificates',
  'Validate Certificate Registration Information',
  'Targets',
  'Locations/Target Types',
  'Experiments',
  'Private Accesses',
  'Classic Infrastructure Resources',
  'Virtual Networks/Virtual Network Peerings',
  'Virtual Networks/Remote Virtual Network Peering Proxies',
  'Reserved Ips',
  'Gateway Supported Devices',
  'Express Route Cross Connections',
  'Express Route Cross Connections/Peerings',
  'Code Signing Accounts',
  'Code Signing Accounts/Certificate Profiles',
  'Locations/Check Sku Availability',
  'Check Domain Availability',
  'Accounts/Private Link Resources',
  'Accounts/Private Endpoint Connections',
  'Accounts/Private Endpoint Connection Proxies',
  'Locations/Resource Groups',
  'Locations/Resource Groups/Deleted Accounts',
  'Locations/Commitment Tiers',
  'Locations/Models',
  'Profiles/Securitypolicies',
  'Accounts/Network Security Perimeter Association Proxies',
  'Accounts/Encryption Scopes',
  'Commitment Plans',
  'Attestations',
  'Attestation Definitions',
  'Communication Services',
  'Communication Services/Event Grid Filters',
  'Email Services/Domains',
  'Email Services/Domains/Sender Usernames',
  'Email Services/Domains/Suppression Lists',
  'Email Services/Domains/Suppression Lists/Suppression List Addresses',
  'Community Trainings',
  'Ledgers',
  'Managed Ccfs',
  'Agreements',
  'Validations',
  'Organizations/Access/Delete Role Binding',
  'Organizations/Environments',
  'Organizations/Environments/Clusters',
  'Organizations/Environments/Schema Registry Clusters',
  'Organizations/Environments/Clusters/Create Apikey',
  'Organizations/Api Keys',
  'Organizations/List Regions',
  'Cache Nodes',
  'Enterprise Customers',
  'Isp Customers',
  'Isp Customers/Isp Cache Nodes',
  'Enterprise Mcc Customers',
  'Credentials',
  'Vcenters',
  'Resourcepools',
  'Virtualmachinetemplates',
  'Locations/Rai Content Filters',
  'Virtualmachines/Guestagents',
  'Datastores',
  'Hosts',
  'Forecasts',
  'Aggregated Cost',
  'Reservation Recommendations',
  'Reservation Recommendation Details',
  'Reservation Summaries',
  'Reservation Transactions',
  'Balances',
  'Marketplaces',
  'Pricesheets',
  'Reservation Details',
  'Budgets',
  'Cost Tags',
  'Tags',
  'Terms',
  'Usage Details',
  'Charges',
  'Lots',
  'Products',
  'Service Association Links',
  'Locations/Cached Images',
  'Locations/Validate Delete Virtual Network Or Subnets',
  'Registries',
  'Registries/Cache Rules',
  'Registries/Credential Sets',
  'Registries/Connected Registries/Deactivate',
  'Registries/Scope Maps',
  'Registries/Tokens',
  'Registries/Generate Credentials',
  'Registries/Private Endpoint Connections',
  'Registries/Private Endpoint Connection Proxies',
  'Registries/Private Endpoint Connection Proxies/Validate',
  'Registries/Private Link Resources',
  'Registries/Import Image',
  'Registries/Export Pipelines',
  'Registries/Import Pipelines',
  'Registries/Pipeline Runs',
  'Registries/List Build Source Upload Url',
  'Registries/Schedule Run',
  'Registries/Runs',
  'Registries/Task Runs',
  'Registries/Task Runs/List Details',
  'Registries/Agent Pools',
  'Registries/Agent Pools Operation Results',
  'Registries/Agent Pools/List Queue Status',
  'Registries/Runs/List Log Sas Url',
  'Registries/Runs/Cancel',
  'Registries/Tasks',
  'Registries/Replications',
  'Registries/Webhooks',
  'Registries/Webhooks/Ping',
  'Registries/Webhooks/Get Callback Config',
  'Registries/Webhooks/List Events',
  'Vcenters/Inventoryitems',
  'Registries/Regenerate Credential',
  'Registries/List Usages',
  'Registries/List Policies',
  'Registries/Update Policies',
  'Registries/Event Grid Filters',
  'Cloud Connectors',
  'Check Connector Eligibility',
  'External Billing Accounts',
  'External Billing Accounts/Dimensions',
  'External Billing Accounts/Query',
  'External Subscriptions/Dimensions',
  'External Subscriptions/Query',
  'External Subscriptions',
  'Forecast',
  'External Subscriptions/Forecast',
  'Register',
  'Dimensions',
  'External Subscriptions/Alerts',
  'External Billing Accounts/Alerts',
  'Showback Rules',
  'Cost Allocation Rules',
  'Exports',
  'Reportconfigs',
  'Views',
  'Publish',
  'Scheduled Actions',
  'Benefit Recommendations',
  'Insights',
  'Fetch Prices',
  'Fetch Microsoft Prices',
  'Fetch Marketplace Prices',
  'Calculate Cost',
  'Generate Benefit Utilization Summaries Report',
  'Benefit Utilization Summaries Operation Results',
  'Generate Reservation Details Report',
  'Reservation Details Operation Results',
  'Generate Detailed Cost Report',
  'Generate Cost Details Report',
  'Cost Details Operation Results',
  'Markup Rules',
  'Start Conversation',
  'Send Message',
  'Tenant Opted In',
  'Enable Lockbox',
  'Disable Lockbox',
  'Requests',
  'Resource Providers/Operation Results',
  'Resource Providers/Operation Statuses',
  'Associations',
  'Instances',
  'Registries/List Credentials',
  'Grafana',
  'Grafana/Private Link Resources',
  'Grafana/Managed Private Endpoints',
  'Watchers',
  'Watchers/Targets',
  'Watchers/Shared Private Link Resources',
  'Locations/Validate Address',
  'Locations/Available Skus',
  'Locations/Validate Inputs',
  'Locations/Region Configuration',
  'Jobs/Event Grid Filters',
  'Data Box Edge Devices',
  'Available Skus',
  'Access Connectors',
  'Workspaces/Virtual Network Peerings',
  'Workspaces/Db Workspaces',
  'Locations/Get Network Policies',
  'Locations/Jobs',
  'Monitors/List Api Keys',
  'Monitors/Get Default Key',
  'Monitors/Set Default Key',
  'Monitors/List Linked Resources',
  'Monitors/Refresh Set Password Link',
  'Monitors/Monitored Subscriptions',
  'Subscription Statuses',
  'Factories',
  'Factories/Integration Runtimes',
  'Factories/Private Endpoint Connection Proxies',
  'Locations/Configure Factory Repo',
  'Locations/Get Feature Value',
  'Accounts/Storage Accounts',
  'Accounts/Storage Accounts/Containers',
  'Accounts/Storage Accounts/Containers/List Sas Tokens',
  'Locations/Capability',
  'Accounts/Firewall Rules',
  'Services/Projects',
  'Migration Services',
  'Sql Migration Services',
  'Database Migrations',
  'Locations/Operation Types',
  'Locations/Sql Migration Service Operation Results',
  'Backup Vaults',
  'Resource Guards',
  'Locations/Check Feature Support',
  'Backup Instances',
  'Locations/Fetch Secondary Recovery Points',
  'Locations/Fetch Cross Region Restore Jobs',
  'Locations/Fetch Cross Region Restore Job',
  'Locations/Validate Cross Region Restore',
  'Locations/Cross Region Restore',
  'Replication Vaults',
  'Replication Fabrics',
  'Accounts/Shares',
  'Accounts/Shares/Datasets',
  'Accounts/Shares/Synchronization Settings',
  'Accounts/Shares/Invitations',
  'Accounts/Sharesubscriptions',
  'Accounts/Shares/Providersharesubscriptions',
  'Accounts/Sharesubscriptions/Datasetmappings',
  'Accounts/Sharesubscriptions/Triggers',
  'Accounts/Sharesubscriptions/Consumer Source Data Sets',
  'Listinvitations',
  'Locations/Register Email',
  'Locations/Activate Email',
  'Locations/Consumer Invitations',
  'Servers/Recoverable Servers',
  'Locations/Azure Async Operation',
  'Locations/Performance Tiers',
  'Locations/Recommended Action Sessions Azure Async Operation',
  'Product Families Metadata',
  'Locations/Recommended Action Sessions Operation Results',
  'Servers/Top Query Statistics',
  'Servers/Query Texts',
  'Servers/Private Link Resources',
  'Servers/Private Endpoint Connections',
  'Servers/Private Endpoint Connection Proxies',
  'Servers/Start',
  'Servers/Stop',
  'Flexible Servers',
  'Locations/Capability Sets',
  'Assess For Migration',
  'Get Private Dns Zone Suffix',
  'Locations/Check Virtual Network Subnet Usage',
  'Locations/List Migrations',
  'Locations/Update Migration',
  'Locations/Operation Progress',
  'Servers/Wait Statistics',
  'Servers/Reset Query Performance Insight Data',
  'Servers/Upgrade',
  'Server Groupsv2',
  'Available Engine Versions',
  'Locations/Get Cached Server Name',
  'Applicationgroups',
  'Applicationgroups/Applications',
  'Applicationgroups/Desktops',
  'Applicationgroups/Startmenuitems',
  'Hostpools',
  'Hostpools/Msixpackages',
  'Hostpools/Sessionhosts',
  'Hostpools/Usersessions',
  'Scalingplans',
  'Appattachpackages',
  'Instances/Experiments',
  'Instances/Sandboxes',
  'Instances/Sandboxes/Experiments',
  'Devcenters',
  'Devcenters/Catalogs',
  'Devcenters/Attachednetworks',
  'Devcenters/Devboxdefinitions',
  'Devcenters/Environment Types',
  'Devcenters/Galleries',
  'Devcenters/Galleries/Images/Versions',
  'Devcenters/Galleries/Images',
  'Devcenters/Images',
  'Networkconnections',
  'Projects',
  'Projects/Attachednetworks',
  'Projects/Environment Types',
  'Projects/Pools',
  'Projects/Pools/Schedules',
  'Projects/Devboxdefinitions',
  'Projects/Allowed Environment Types',
  'Networkconnections/Outbound Network Dependencies Endpoints',
  'Devcenters/Catalogs/Devboxdefinitions',
  'Devcenters/Catalogs/Environment Definitions',
  'Devcenters/Catalogs/Tasks',
  'Check Scoped Name Availability',
  'Development Cloud Pc Delegated Msis',
  'Workflows',
  'Locations/Githuboauth',
  'Check Provisioning Service Name Availability',
  'Locations/Hci Catalog',
  'Provisioning Service Operation Results',
  'Locations/Provisioning Service Operation Results',
  'Iot Hubs',
  'Iot Hubs/Event Grid Filters',
  'Iot Hubs/Failover',
  'Provisioning Services',
  'Iot Hubs/Security Settings',
  'Accounts/Instances',
  'Labs/Environments',
  'Labs',
  'Schedules',
  'Labs/Virtual Machines',
  'Labs/Service Runners',
  'Digital Twins Instances',
  'Locations/Operations Statuses',
  'Digital Twins Instances/Endpoints',
  'Digital Twins Instances/Time Series Database Connections',
  'Database Accounts',
  'Database Account Names',
  'Locations/Restorable Database Accounts',
  'Restorable Database Accounts',
  'Cassandra Clusters',
  'Database Accounts/Encryption Scopes',
  'Mongo Clusters',
  'Locations/Mongo Cluster Operation Results',
  'Locations/Mongo Cluster Azure Async Operation',
  'Locations/Check Mongo Cluster Name Availability',
  'Throughput Pools',
  'Throughput Pools/Throughput Pool Accounts',
  'Domains/Domain Ownership Identifiers',
  'Top Level Domains',
  'List Domain Recommendations',
  'Validate Domain Registration Information',
  'Generate Sso Request',
  'Workspaces/Labels',
  'Workspaces/Tasks',
  'Asset Endpoint Profiles',
  'Publishers',
  'Offers',
  'Addresses',
  'Order Items',
  'Orders',
  'Locations/Orders',
  'List Product Families',
  'List Configurations',
  'Locations/Hci Catalog/Vendors',
  'Locations/Hci Catalog/Projects',
  'Locations/Hci Flight Catalog',
  'Locations/Hci Flight Catalog/Vendors',
  'Locations/Hci Flight Catalog/Platforms',
  'Locations/Hci Flight Catalog/Projects',
  'Elastic Versions',
  'Get Organization Api Key',
  'Monitors/Open Aiintegrations',
  'Elastic Sans',
  'Elastic Sans/Volume Groups',
  'Enterprise Supports',
  'Namespaces/Authorizationrules',
  'Namespaces/Networkrulesets',
  'Namespaces/Private Endpoint Connections',
  'Namespaces/Private Endpoint Connection Proxies',
  'Namespaces/Network Security Perimeter Configurations',
  'Namespaces/Network Security Perimeter Association Proxies',
  'Namespaces/Hobo Configurations',
  'Namespaces/Eventhubs',
  'Namespaces/Eventhubs/Authorizationrules',
  'Namespaces/Eventhubs/Consumergroups',
  'Namespaces/Application Groups',
  'Check Namespace Availability',
  'Sku',
  'Namespaces/Disasterrecoveryconfigs/Check Name Availability',
  'Locations/Cluster Operation Results',
  'Locations/Namespace Operation Results',
  'Available Cluster Regions',
  'Custom Locations',
  'Custom Locations/Enabled Resource Types',
  'Capacities',
  'Features',
  'Providers',
  'Feature Providers',
  'Subscription Feature Registrations',
  'Feature Provider Namespaces',
  'Feature Configurations',
  'Fluid Relay Servers',
  'Fluid Relay Servers/Fluid Relay Containers',
  'Hana Instances',
  'Cloud Hsm Clusters',
  'Clusterpools',
  'Clusterpools/Clusters',
  'Locations/Clusterofferingversions',
  'Clusterpools/Clusters/Service Configs',
  'Clusterpools/Clusters/Instance Views',
  'Locations/Availableclusterversions',
  'Locations/Availableclusterpoolversions',
  'Clusters/Applications',
  'Clusters/Operationresults',
  'Locations/Billing Specs',
  'Locations/Azureasyncoperations',
  'Locations/Validate Create Request',
  'Health Bots',
  'Services/Private Endpoint Connections',
  'Services/Private Link Resources',
  'Services/Iomtconnectors',
  'Services/Iomtconnectors/Connections',
  'Services/Iomtconnectors/Mappings',
  'Workspaces/Private Endpoint Connection Proxies',
  'Workspaces/Private Endpoint Connections',
  'Workspaces/Private Link Resources',
  'Workspaces/Dicomservices',
  'Workspaces/Iotconnectors',
  'Workspaces/Fhirservices',
  'Validate Medtech Mappings',
  'Discovery Solutions',
  'Discover Solutions',
  'Diagnostics',
  'Solutions',
  'Simplified Solutions',
  'Troubleshooters',
  'Self Help',
  'Cloud Connections',
  'Machines',
  'Machines/Hybrid Identity Metadata',
  'Machines/Private Link Scopes',
  'Machines/Extensions',
  'Locations/Publishers/Extension Types',
  'Locations/Publishers/Extension Types/Versions',
  'Machines/Assess Patches',
  'Machines/Install Patches',
  'Locations/Update Center Operation Results',
  'Locations/Private Link Scopes',
  'Os Type',
  'Os Type/Agent Versions',
  'Os Type/Agent Versions/Latest',
  'Machines/Runcommands',
  'Machines/License Profiles',
  'Licenses',
  'Validate License',
  'Network Configurations',
  'Private Link Scopes/Network Security Perimeter Association Proxies',
  'Locations/Notify Extension',
  'Endpoints',
  'Provisioned Clusters',
  'Provisioned Clusters/Agent Pools',
  'Provisioned Clusters/Upgrade Profiles',
  'Kubernetes Versions',
  'Skus',
  'Provisioned Cluster Instances',
  'Devices',
  'Networkfunctions',
  'Network Function Vendors',
  'Network Functions/Components',
  'Sites',
  'Site Network Services',
  'Configuration Group Values',
  'Publishers/Network Function Definition Groups',
  'Publishers/Network Function Definition Groups/Network Function Definition Versions',
  'Publishers/Artifact Stores',
  'Spaces',
  'Spaces/Infrastructure Resources',
  'Spaces/Applications',
  'Spaces/Applications/Resources',
  'Spaces/Applications/Business Processes',
  'Spaces/Applications/Business Processes/Versions',
  'Subscription Internal Properties',
  'Io Tapps',
  'Check Subdomain Availability',
  'App Templates',
  'Workspaces/Firmwares',
  'Workspaces/Firmwares/Sbom Components',
  'Workspaces/Firmwares/Crypto Certificates',
  'Workspaces/Firmwares/Crypto Keys',
  'Workspaces/Firmwares/Password Hashes',
  'Workspaces/Firmwares/Cves',
  'Workspaces/Firmwares/Summaries',
  'Instances/Datasets',
  'Instances/Pipelines',
  'Mq',
  'Mq/Broker',
  'Mq/Broker/Authentication',
  'Mq/Broker/Authorization',
  'Mq/Broker/Listener',
  'Mq/Data Lake Connector',
  'Mq/Data Lake Connector/Topic Map',
  'Mq/Diagnostic Service',
  'Mq/Kafka Connector',
  'Mq/Mqtt Bridge Connector',
  'Mq/Mqtt Bridge Connector/Topic Map',
  'Defender Settings',
  'Locations/Device Groups',
  'Locations/Device Groups/Devices',
  'Locations/Endpoints',
  'Locations/Device Groups/Vulnerabilities',
  'Locations/Device Groups/Alerts',
  'Locations/Device Groups/Alerts/Pcaps',
  'Locations/Device Groups/Alerts/Learn',
  'Locations/Device Groups/Recommendations',
  'Locations/Sites',
  'Locations/Sites/Sensors',
  'Sensors',
  'On Premise Sensors',
  'License Skus',
  'Vaults/Secrets',
  'Vaults/Access Policies',
  'Deleted Vaults',
  'Locations/Deleted Vaults',
  'Vaults/Event Grid Filters',
  'Managed Hsms',
  'Deleted Managed Hsms',
  'Locations/Deleted Managed Hsms',
  'Locations/Managed Hsm Operation Results',
  'Managed Hsms/Keys',
  'Managed Hsms/Keys/Versions',
  'Check Mhsm Name Availability',
  'Vaults/Keys',
  'Vaults/Keys/Versions',
  'Connected Clusters',
  'Source Control Configurations',
  'Extensions',
  'Flux Configurations',
  'Extension Types',
  'Locations/Extension Types',
  'Storage Classes',
  'Bgp Peers',
  'Clusters/Databases',
  'Clusters/Attacheddatabaseconfigurations',
  'Clusters/Principalassignments',
  'Clusters/Databases/Eventhubconnections',
  'Clusters/Databases/Dataconnections',
  'Clusters/Databases/Principalassignments',
  'Locations/Skus',
  'Clusters/Databases/Scripts',
  'Clusters/Managed Private Endpoints',
  'Clusters/Sandbox Custom Images',
  'Labplans',
  'Labaccounts',
  'Users',
  'Loadtests',
  'Loadtests/Outbound Network Dependencies Endpoints',
  'Recommendation Types',
  'Locations/Workflows',
  'Locations/Workflow Export',
  'Integration Accounts',
  'Integration Service Environments',
  'Integration Service Environments/Managed Apis',
  'Locations/Generate Copilot Response',
  'Monitors/Single Sign On Configurations',
  'Monitors/Accounts',
  'Monitors/Accounts/Tag Rules',
  'Web Services',
  'Workspaces/Batch Endpoints',
  'Workspaces/Batch Endpoints/Deployments',
  'Locations/Registry Operations Status',
  'Workspaces/Online Endpoints',
  'Workspaces/Online Endpoints/Deployments',
  'Workspaces/Online Endpoints/Deployments/Skus',
  'Workspaces/Computes',
  'Workspaces/Jobs',
  'Workspaces/Codes',
  'Workspaces/Codes/Versions',
  'Workspaces/Components',
  'Workspaces/Components/Versions',
  'Workspaces/Environments',
  'Workspaces/Environments/Versions',
  'Workspaces/Data',
  'Workspaces/Data/Versions',
  'Workspaces/Datasets',
  'Workspaces/Services',
  'Workspaces/Models',
  'Workspaces/Models/Versions',
  'Locations/Compute Operations Status',
  'Locations/Mfe Operation Results',
  'Locations/Mfe Operations Status',
  'Locations/Workspace Operations Status',
  'Locations/Updatequotas',
  'Workspaces/Labeling Jobs',
  'Workspaces/Schedules',
  'Workspaces/Featuresets',
  'Workspaces/Serverless Endpoints',
  'Workspaces/Marketplace Subscriptions',
  'Workspaces/Inference Pools',
  'Workspaces/Inference Pools/Groups',
  'Workspaces/Inference Pools/Endpoints',
  'Workspaces/Featurestore Entities',
  'Workspaces/Featurestore Entities/Versions',
  'Workspaces/Endpoints',
  'Load Test Mappings',
  'Registries/Components',
  'Registries/Components/Versions',
  'Registries/Data',
  'Registries/Data/Versions',
  'Registries/Datareferences',
  'Registries/Datareferences/Versions',
  'Registries/Environments',
  'Registries/Environments/Versions',
  'Registries/Models',
  'Registries/Models/Versions',
  'Maintenance Configurations',
  'Updates',
  'Configuration Assignments',
  'Apply Updates',
  'Public Maintenance Configurations',
  'Network Fabrics',
  'Network Racks',
  'Network Devices',
  'Network Devices/Network Interfaces',
  'L2Isolation Domains',
  'L3Isolation Domains',
  'Accesscontrollists',
  'Route Policies',
  'L3Isolation Domains/External Networks',
  'L3Isolation Domains/Internal Networks',
  'Network Fabrics/Network To Network Interconnects',
  'Ip Extended Communities',
  'Ip Communities',
  'Ipprefixes',
  'Internet Gateways',
  'Internetgatewayrules',
  'Networkpacketbrokers',
  'Networktaps',
  'Networktaprules',
  'Neighborgroups',
  'Registration Definitions',
  'Registration Assignments',
  'Management Groups',
  'Get Entities',
  'Management Groups/Settings',
  'Operation Results/Async Operation',
  'Tenant Backfill Status',
  'Start Tenant Backfill',
  'Accounts/Creators',
  'Accounts/Event Grid Filters',
  'Privategalleryitems',
  'Macc',
  'Offer Types',
  'Offer Types/Publishers/Offers',
  'Offer Types/Publishers/Offers/Plans',
  'Offer Types/Publishers/Offers/Plans/Configs',
  'Offer Types/Publishers/Offers/Plans/Configs/Import Image',
  'Offer Types/Publishers/Offers/Plans/Agreements',
  'Registries/Codes/Versions',
  'Publishers/Offers',
  'Publishers/Offers/Amendments',
  'Private Store Client',
  'Private Stores',
  'Private Stores/Offers',
  'Search',
  'Private Stores/Request Approvals/Withdraw Plan',
  'Private Stores/Request Approvals',
  'Private Stores/Query Notifications State',
  'Private Stores/Fetch All Subscriptions In Tenant',
  'Private Stores/List New Plans Notifications',
  'Private Stores/List Stop Sell Offers Plans Notifications',
  'Private Stores/List Subscriptions Context',
  'Private Stores/Offers/Acknowledge Notification',
  'Private Stores/Admin Request Approvals',
  'Private Stores/Collections',
  'Private Stores/Collections/Approve All Items',
  'Private Stores/Collections/Disable Approve All Items',
  'Private Stores/Collections/Offers',
  'Private Stores/Collections/Map Offers To Contexts',
  'Private Stores/Collections/Query Rules',
  'Private Stores/Collections/Set Rules',
  'Private Stores/Bulk Collections Action',
  'Private Stores/Collections/Transfer Offers',
  'Private Stores/Any Existing Offers In The Collections',
  'Private Stores/Query Offers',
  'Private Stores/Query User Offers',
  'Private Stores/Query User Rules',
  'Private Stores/Collections To Subscriptions Mapping',
  'Private Stores/Billing Accounts',
  'Private Stores/Query Approved Plans',
  'Locations/Edge Zones/Products',
  'Mysolutions',
  'Products/Reviews',
  'Products/Reviews/Comments',
  'Products/Reviews/Helpful',
  'Products/Usermetadata',
  'Mediaservices',
  'Mediaservices/Assets',
  'Mediaservices/Assets/Tracks',
  'Mediaservices/Assets/Tracks/Operationstatuses',
  'Mediaservices/Assets/Tracks/Operation Results',
  'Mediaservices/Content Key Policies',
  'Mediaservices/Streaming Locators',
  'Mediaservices/Event Grid Filters',
  'Mediaservices/Transforms',
  'Mediaservices/Transforms/Jobs',
  'Mediaservices/Streaming Endpoints',
  'Mediaservices/Live Events',
  'Mediaservices/Live Events/Live Outputs',
  'Mediaservices/Streaming Endpoint Operations',
  'Mediaservices/Live Event Operations',
  'Mediaservices/Live Output Operations',
  'Mediaservices/Streamingendpoints/Operationlocations',
  'Mediaservices/Liveevents/Operationlocations',
  'Mediaservices/Liveevents/Liveoutputs/Operationlocations',
  'Mediaservices/Private Endpoint Connection Proxies',
  'Mediaservices/Private Endpoint Connections',
  'Mediaservices/Private Endpoint Connection Operations',
  'Locations/Media Services Operation Statuses',
  'Locations/Media Services Operation Results',
  'Mediaservices/Assets/Asset Filters',
  'Virtual Enclaves/Endpoints',
  'Spatial Anchors Accounts',
  'Remote Rendering Accounts',
  'Object Anchors Accounts',
  'Packet Core Control Plane Versions',
  'Locations/Location Operation Statuses',
  'Investigations',
  'My Sqlsites',
  'My Sqlsites/My Sqlservers',
  'My Sqlsites/Refresh',
  'My Sqlsites/Summaries',
  'Net App Accounts',
  'Net App Accounts/Snapshot Policies',
  'Net App Accounts/Volume Groups',
  'Net App Accounts/Capacity Pools',
  'Net App Accounts/Capacity Pools/Volumes',
  'Net App Accounts/Capacity Pools/Volumes/Snapshots',
  'Net App Accounts/Capacity Pools/Volumes/Volume Quota Rules',
  'Locations/Check File Path Availability',
  'Locations/Query Network Sibling Set',
  'Locations/Update Network Sibling Set',
  'Locations/Region Info',
  'Locations/Region Infos',
  'Locations/Quota Limits',
  'Locations/Check Inventory',
  'Cluster Managers',
  'Racks',
  'Bare Metal Machines',
  'Rack Skus',
  'Cloud Services Networks',
  'L2Networks',
  'Storage Appliances',
  'Trunked Networks',
  'Virtual Machines/Consoles',
  'Clusters/Bare Metal Machine Key Sets',
  'Clusters/Bmc Key Sets',
  'Volumes',
  'Kubernetes Clusters',
  'Kubernetes Clusters/Agent Pools',
  'Azure Traffic Collectors',
  'Mesh Vpns',
  'Mesh Vpns/Connection Policies',
  'Mesh Vpns/Private Endpoint Connections',
  'Mesh Vpns/Private Endpoint Connection Proxies',
  'Namespaces/Notification Hubs',
  'Os Namespaces',
  'Vmware Sites',
  'Hyper Vsites',
  'Server Sites',
  'Master Sites',
  'Springbootsites',
  'Springbootsites/Springbootapps',
  'Springbootsites/Summaries',
  'Springbootsites/Errorsummaries',
  'Energy Services',
  'Energy Services/Private Endpoint Connections',
  'Energy Services/Private Link Resources',
  'Energy Services/Private Endpoint Connection Proxies',
  'Oraclesites',
  'Oraclesites/Oracleservers',
  'Oraclesites/Oracledatabases',
  'Oraclesites/Summaries',
  'Oraclesites/Error Summaries',
  'Contact Profiles',
  'Spacecrafts',
  'Spacecrafts/Contacts',
  'Ground Stations',
  'Global Communications Sites',
  'L2Connections',
  'Edge Sites',
  'Recurrences',
  'Clusters/Metrics Configurations',
  'Peerings',
  'Peering Locations',
  'Legacy Peerings',
  'Peer Asns',
  'Peering Services',
  'Peering Service Countries',
  'Peering Service Locations',
  'Check Service Provider Availability',
  'Looking Glass',
  'Cdn Peering Prefixes',
  'Dashboards',
  'Tenantconfigurations',
  'List Tenant Configuration Violations',
  'Consoles',
  'Locations/Consoles',
  'User Settings',
  'Locations/User Settings',
  'Workspace Collections',
  'Private Link Services For Power Bi',
  'Auto Scale Vcores',
  'Enterprise Policies',
  'Eligibility Check',
  'Gateways',
  'Open Api Gateways',
  'Open Api Gateway Offerings',
  'Operator Offerings',
  'Operator Api Plans',
  'Operator Api Connections',
  'Provider Registrations',
  'Provider Registrations/Resource Type Registrations',
  'Provider Registrations/Default Rollouts',
  'Provider Registrations/Custom Rollouts',
  'Provider Registrations/Checkinmanifest',
  'Provider Registrations/Resource Actions',
  'Available Accounts',
  'Provider Registrations/Authorized Applications',
  'Accounts/Kafka Configurations',
  'Set Default Account',
  'Remove Default Account',
  'Get Default Account',
  'Locations/List Features',
  'Locations/Offerings',
  'Quota Requests',
  'Group Quotas',
  'Group Quotas/Group Quota Limits',
  'Group Quotas/Subscriptions',
  'Group Quotas/Group Quota Requests',
  'Group Quotas/Quota Allocations',
  'Group Quotas/Subscription Requests',
  'Group Quotas/Quota Allocation Operations Status',
  'Accounts/Modeling',
  'Accounts/Service Endpoints',
  'Open Shift Clusters',
  'Locations/Openshiftversions',
  'Namespaces/Hybridconnections',
  'Namespaces/Hybridconnections/Authorizationrules',
  'Namespaces/Wcfrelays',
  'Namespaces/Wcfrelays/Authorizationrules',
  'Appliances',
  'Telemetryconfig',
  'Resources History',
  'Resource Changes',
  'Resource Change Details',
  'Subscriptions Status',
  'Queries',
  'Generate Query',
  'Mobo Brokers',
  'Deployment Scripts',
  'Deployment Scripts/Logs',
  'Locations/Deployment Script Operation Results',
  'Decompile Bicep',
  'Template Specs',
  'Template Specs/Versions',
  'Built In Template Specs',
  'Built In Template Specs/Versions',
  'Deployment Stacks',
  'Locations/Deployment Stack Operation Status',
  'Notify Resource Jobs',
  'Check Policy Compliance',
  'Checkresourcename',
  'Subscriptions',
  'Subscriptions/Resources',
  'Subscriptions/Providers',
  'Resource Groups',
  'Subscriptions/Resource Groups',
  'Subscriptions/Resourcegroups/Resources',
  'Subscriptions/Locations',
  'Subscriptions/Tagnames',
  'Subscriptions/Tag Names/Tag Values',
  'Deployments',
  'Deployments/Operations',
  'Validate Resources',
  'Links',
  'Bulk Delete',
  'Changes',
  'Data Boundaries',
  'Can Create',
  'Managed Instances/Monitored Resources',
  'Managed Instances/Managed Gateways',
  'Vmmservers',
  'Clouds',
  'Availability Sets',
  'Vmmservers/Inventory Items',
  'Search Services',
  'Resource Health Metadata',
  'Chambers',
  'Git Hub Connectors',
  'Azure Dev Ops Connectors',
  'Azure Dev Ops Connectors/Orgs',
  'Git Hub Connectors/Owners',
  'Azure Dev Ops Connectors/Orgs/Projects',
  'Git Hub Connectors/Owners/Repos',
  'Git Hub Connectors/Stats',
  'Git Hub Connectors/Repos',
  'Azure Dev Ops Connectors/Stats',
  'Azure Dev Ops Connectors/Repos',
  'Git Lab Connectors',
  'Git Hub Connectors/Git Hub Installations',
  'Git Hub Connectors/Git Hub Installations/Git Hub Repositories',
  'Git Lab Connectors/Groups',
  'Git Lab Connectors/Groups/Projects',
  'Alert Rule Templates',
  'Triggered Analytics Rule Runs',
  'Cases',
  'Bookmarks',
  'Data Connectors',
  'Data Connector Definitions',
  'Data Connectors Check Requirements',
  'Enrichment',
  'File Imports',
  'Entities',
  'Incidents',
  'Entity Queries',
  'Entity Query Templates',
  'Threat Intelligence',
  'Automation Rules',
  'Business Application Agents',
  'Source Controls',
  'Export Connections',
  'Listrepositories',
  'Watchlists',
  'Confidential Watchlists',
  'Huntsessions',
  'Hunts',
  'Onboarding States',
  'Content Packages',
  'Content Templates',
  'Content Product Packages',
  'Content Product Templates',
  'Mitre Coverage Records',
  'Overview',
  'Billing Statistics',
  'Workspace Manager Members',
  'Workspace Manager Groups',
  'Workspace Manager Assignments',
  'Security Mlanalytics Settings',
  'Contenttranslators',
  'Console Services',
  'Serial Ports',
  'Locations/Console Services',
  'Namespaces/Queues',
  'Namespaces/Queues/Authorizationrules',
  'Namespaces/Topics',
  'Namespaces/Topics/Subscriptions',
  'Namespaces/Topics/Subscriptions/Rules',
  'Premium Messaging Regions',
  'Namespaces/Eventgridfilters',
  'Namespaces/Disasterrecoveryconfigs',
  'Namespaces/Migration Configurations',
  'Clusters/Application Types',
  'Git Lab Connectors/Stats',
  'Locations/Cluster Versions',
  'Locations/Environments',
  'Locations/Unsupported Vmsizes',
  'Managedclusters/Nodetypes',
  'Managedclusters/Application Types',
  'Managedclusters/Application Types/Versions',
  'Managedclusters/Applications',
  'Managedclusters/Applications/Services',
  'Locations/Managed Cluster Operations',
  'Locations/Managed Cluster Operation Results',
  'Locations/Managed Cluster Versions',
  'Locations/Managed Unsupported Vmsizes',
  'Networks',
  'Secrets',
  'Locations/Application Operations',
  'Locations/Network Operations',
  'Locations/Volume Operations',
  'Locations/Gateway Operations',
  'Locations/Secret Operations',
  'Linkers',
  'Dryruns',
  'Locations/Connectors',
  'Locations/Dryruns',
  'Configuration Names',
  'Dapr Configurations',
  'Traffic Controllers',
  'Traffic Controllers/Associations',
  'Support Offering Entitlement',
  'Get Recommendations Content',
  'Connectors/Connector Spaces',
  'Signal R',
  'Web Pub Sub',
  'Signal R/Replicas',
  'Web Pub Sub/Replicas',
  'Signal R/Event Grid Filters',
  'Signal R/Custom Domains',
  'Web Pub Sub/Custom Domains',
  'Accounts/Storage Containers',
  'Accounts/Networks',
  'Accounts/Secrets',
  'Accounts/Group Policies',
  'Accounts/Jobs',
  'Accounts/Models',
  'Clusters/Applications/Services',
  'Hybrid Use Benefits',
  'Application Definitions',
  'Jit Requests',
  'Landing Zone Configurations',
  'Landing Zone Registrations',
  'Locations/Preview Actions',
  'Caches',
  'Caches/Storage Targets',
  'Aml Filesystems',
  'Usage Models',
  'Check Aml Fssubnets',
  'Locations/Ascoperations',
  'Storage Movers',
  'Storage Movers/Projects',
  'Storage Movers/Agents',
  'Storage Movers/Endpoints',
  'Storage Movers/Projects/Job Definitions',
  'Storage Movers/Projects/Job Definitions/Job Runs',
  'Storage Sync Services',
  'Storage Sync Services/Sync Groups',
  'Storage Sync Services/Sync Groups/Cloud Endpoints',
  'Storage Sync Services/Registered Servers',
  'Storage Sync Services/Workflows',
  'Streamingjobs',
  'Clusters/Private Endpoints',
  'Locations/Test Query',
  'Locations/Compile Query',
  'Locations/Sample Input',
  'Locations/Test Input',
  'Locations/Test Output',
  'Subscription Definitions',
  'Subscription Operations',
  'Create Subscription',
  'Cancel',
  'Validate Cancel',
  'Locations/Instance Type Series/Instance Types',
  'Aliases',
  'Accept Change Tenant',
  'Change Tenant Status',
  'Change Tenant Request',
  'Accept Ownership Status',
  'Classify Services',
  'Services/Problemclassifications',
  'Supporttickets',
  'Supporttickets/Communications',
  'Look Up Resource Id',
  'File Workspaces',
  'File Workspaces/Files',
  'Workspaces/Big Data Pools',
  'Workspaces/Sql Pools',
  'Workspaces/Sql Databases',
  'Locations/Sql Database Operation Results',
  'Workspaces/Kusto Pools',
  'Locations/Kusto Pool Operation Results',
  'Locations/Kusto Pool Check Name Availability',
  'Workspaces/Kusto Pools/Databases',
  'Workspaces/Kusto Pools/Attacheddatabaseconfigurations',
  'Workspaces/Kusto Pools/Databases/Dataconnections',
  'Locations/Sql Pool Azure Async Operation',
  'Locations/Sql Pool Operation Results',
  'Workspaces/Operation Statuses',
  'Workspaces/Operation Results',
  'Kusto Operations',
  'Private Link Hubs',
  'Workspaces/Usages',
  'Document Processors',
  'Test Base Accounts',
  'Test Base Accounts/Usages',
  'Test Base Accounts/Available Oss',
  'Test Base Accounts/Test Types',
  'Test Base Accounts/Flighting Rings',
  'Test Base Accounts/Packages',
  'Test Base Accounts/Packages/Os Updates',
  'Test Base Accounts/Test Summaries',
  'Test Base Accounts/Packages/Favorite Processes',
  'Test Base Accounts/Packages/Test Results',
  'Test Base Accounts/Packages/Test Results/Analysis Results',
  'Test Base Accounts/Email Events',
  'Test Base Accounts/Customer Events',
  'Test Base Accounts/Available Inplace Upgrade Oss',
  'Test Base Accounts/First Party Apps',
  'Test Base Accounts/Draft Packages',
  'Test Base Accounts/Action Requests',
  'Test Base Accounts/Test Configurations',
  'Test Base Accounts/Available Vmconfiguration Types',
  'Test Base Accounts/Custom Images',
  'Test Base Accounts/Vhds',
  'Test Base Accounts/Image Definitions',
  'Enable',
  'Test Base Accounts/Chat Sessions',
  'Test Base Accounts/Free Hour Balances',
  'Test Base Accounts/Credentials',
  'Test Base Accounts/Test Configurations/Test Results',
  'Environments',
  'Environments/Eventsources',
  'Environments/Reference Data Sets',
  'Environments/Access Policies',
  'Environments/Private Link Resources',
  'Environments/Private Endpoint Connections',
  'Locations/Userclassicaccounts',
  'Locations/Classicaccounts',
  'Image Templates',
  'Image Templates/Run Outputs',
  'Image Templates/Triggers',
  'Account',
  'Account/Project',
  'Account/Extension',
  'Plans',
  'Publishing Users',
  'Ishostnameavailable',
  'Isusernameavailable',
  'Generate Github Access Token For Appservice Cli',
  'Available Stacks',
  'Web App Stacks',
  'Locations/Web App Stacks',
  'Function App Stacks',
  'Locations/Function App Stacks',
  'Static Sites',
  'Locations/Preview Static Site Workflow File',
  'Static Sites/User Provided Function Apps',
  'Static Sites/Linked Backends',
  'Static Sites/Builds/Linked Backends',
  'Static Sites/Database Connections',
  'Static Sites/Builds',
  'Static Sites/Builds/User Provided Function Apps',
  'List Sites Assigned To Host Name',
  'Sites/Network Config',
  'Sites/Slots/Network Config',
  'Sites/Host Name Bindings',
  'Sites/Slots/Host Name Bindings',
  'Certificates',
  'Server Farms',
  'Sites/Slots',
  'Runtimes',
  'Test Base Accounts/Gallery Apps/Gallery App Skus',
  'Georegions',
  'Sites/Premieraddons',
  'Hosting Environments',
  'Hosting Environments/Multi Role Pools',
  'Hosting Environments/Worker Pools',
  'Kube Environments',
  'Deployment Locations',
  'Deleted Sites',
  'Ishostingenvironmentnameavailable',
  'Custom Apis',
  'Locations/List Wsdl Interfaces',
  'Locations/Extract Api Definition From Wsdl',
  'Locations/Managed Apis',
  'Locations/Runtimes',
  'Locations/Api Operations',
  'Connection Gateways',
  'Locations/Connection Gateway Installations',
  'Billing Meters',
  'Verify Hosting Environment Vnet',
  'Server Farms/Event Grid Filters',
  'Sites/Event Grid Filters',
  'Sites/Slots/Event Grid Filters',
  'Server Farms/First Party Apps',
  'Server Farms/First Party Apps/Key Vault Settings',
  'Customhostname Sites',
  'Device Services',
  'Sap Virtual Instances',
  'Sap Virtual Instances/Application Instances',
  'Sap Virtual Instances/Central Instances',
  'Sap Virtual Instances/Database Instances',
  'Monitors/Provider Instances',
  'Connectors/Acss Backups',
  'Monitors/Sap Landscape Monitor',
  'Nginx Deployments/Configurations',
  'Nginx Deployments',
  'Nginx Deployments/Certificates',
  'Cloud Exadata Infrastructures',
  'Cloud Vm Clusters',
  'Cloud Vm Clusters/Db Nodes',
  'Oracle Subscriptions',
  'Locations/Gi Versions',
  'Locations/Db System Shapes',
  'Cloud Exadata Infrastructures/Db Servers',
  'Aseregions',
  'Autonomous Databases',
  'Locations/Autonomous Database Character Sets',
  'Locations/Autonomous Db Versions',
  'Firewalls',
  'Local Rulestacks',
  'Global Rulestacks',
  'Local Rulestacks/Local Rules',
  'Local Rulestacks/Fqdnlists',
  'Global Rulestacks/Fqdnlists',
  'Global Rulestacks/Pre Rules',
  'Global Rulestacks/Post Rules',
  'Global Rulestacks/Prefixlists',
  'Local Rulestacks/Prefixlists',
  'Global Rulestacks/Certificates',
  'Local Rulestacks/Certificates',
  'Firewalls/Statuses',
  'File Systems',
  'Migrators',
  'Migrators/Targets',
  'Migrators/Live Data Migrations',
  'Migrators/Exclusion Templates',
  'Migrators/Metadata Migrations',
  'Migrators/Metadata Targets',
  'Migrators/Path Mappings',
  'Migrators/Data Transfer Agents',
  'Migrators/Verifications',
  'Policy Events',
  'Async Operation Results',
  'Domain Names/Internal Load Balancers',
  'Storage Accounts/Services/Metric Definitions',
  'Virtual Machines/Run Commands',
  'Shared Vmimages',
  'Disk Accesses',
  'Locations/Diagnostics',
  'Components/Default Work Item Config',
  'Vm Insights Onboarding Statuses',
  'Workbooktemplates',
  'Data Collection Endpoints/Scoped Private Link Proxies',
  'Components/Linkedstorageaccounts',
  'Secure Scores/Secure Score Controls',
  'Assessments/Governance Assignments',
  'Locations/Application Whitelistings',
  'Iot Security Solutions/Analytics Models/Aggregated Alerts',
  'Storage Accounts/Storage Task Assignments',
  'Locations/Dns Private Zones',
  'Application Gateway Available Server Variables',
  'Check Traffic Manager Name Availability V2',
  'Dnszones/Ptr',
  'Dns Resolvers/Inbound Endpoints',
  'Network Watchers/Connection Monitors',
  'Locations/Check Private Link Service Visibility',
  'Locations/Batch Validate Private Endpoints For Resource Move',
  'Locations/Database Encryption Protector Revalidate Azure Async Operation',
  'Servers/Administrator Operation Results',
  'Servers/Databases/Backup Short Term Retention Policies',
  'Servers/Databases/Advanced Threat Protection Settings',
  'Locations/Job Agent Private Endpoint Operation Results',
  'Servers/Databases/Top Queries/Query Text',
  'Managed Instances/Databases/Vulnerability Assessments',
  'Locations/Sql Vulnerability Assessment Azure Async Operation',
  'Locations/Managed Instance Private Endpoint Connection Proxy Azure Async Operation',
  'Locations/Advanced Threat Protection Operation Results',
  'Locations/Distributed Availability Groups Operation Results',
  'Locations/Long Term Retention Policy Operation Results',
  'Locations/Connection Policies Operation Results',
  'Reservation Orders/Calculate Refund',
  'Calculate Purchase Price',
  'Check Purchase Status',
  'Guest Configuration Assignments',
  'Sql Virtual Machine Groups/Availability Group Listeners',
  'Partner Topics',
  'Services/Event Grid Filters',
  'Api Collections/Api Collection Details',
  'Connected Environments/Certificates',
  'List In Use Storage Accounts',
  'Spring/Apps/Deployments',
  'Locations/Default Provider',
  'Policy Definitions',
  'Role Assignment Approvals',
  'Resource Management Private Links',
  'Private Clouds/Clusters/Placement Policies',
  'Ciam Directories',
  'Postgres Instances',
  'Catalogs/Products/Devicegroups/Devices',
  'Clusters/Publishers/Offers/Skus',
  'Bare Metal Storage Instances',
  'Billing Accounts/Create Billing Role Assignment',
  'Billing Accounts/Billing Profiles/Invoice Sections/Billing Role Definitions',
  'Billing Accounts/List Invoice Sections With Create Subscription Permission',
  'Billing Accounts/Billing Profiles/Departments/Billing Role Definitions',
  'Billing Accounts/Billing Profiles/Validate Delete Billing Profile Eligibility',
  'Billing Accounts/Invoice Sections/Billing Subscriptions/Transfer',
  'Billing Accounts/List Product Recommendations',
  'Incentive Schedules/Milestones',
  'Blueprints/Versions/Artifacts',
  'Profiles/Endpoints/Origingroups',
  'Operationresults/Profileresults/Policyresults',
  'Hostedpools',
  'Email Services',
  'Organizations/Access',
  'Enterprise Mcc Customers/Enterprise Mcc Cache Nodes',
  'Container Groups',
  'Registries/Connected Registries',
  'Registries/Tasks/List Details',
  'External Billing Accounts/Forecast',
  'Benefit Utilization Summaries',
  'Data Box Edge Devices/Check Name Availability',
  'Accounts/Data Lake Store Accounts',
  'Locations/Migration Service Operation Results',
  'Locations/Reject Invitation',
  'Hostpools/Sessionhosts/Usersessions',
  'Networkconnections/Healthchecks',
  'Locations/Generate Preview Artifacts',
  'Assets',
  'Digital Twins Instances/Operation Results',
  'Locations/Hci Catalog/Platforms',
  'Get Elastic Organization To Azure Subscription Mapping',
  'Clusterpools/Clusters/Jobs',
  'Services/Private Endpoint Connection Proxies',
  'Provisioned Clusters/Hybrid Identity Metadata',
  'Publishers/Artifact Stores/Artifact Manifests',
  'Publishers/Artifactstores/Artifactversions',
  'Workspaces/Firmwares/Binary Hardening Results',
  'Mq/Kafka Connector/Topic Map',
  'Alert Types',
  'Locations/Extension Types/Versions',
  'Locations/Validate Workflow Export',
  'Workspaces/Datastores',
  'Workspaces/Featuresets/Versions',
  'Registries/Codes',
  'Network Fabric Controllers',
  'Private Link Scope Operation Statuses',
  'Public Ipaddresses',
  'Managementassociations',
  'Azure Kb',
  'Offer Types/Publishers',
  'List Available Offers',
  'Private Stores/Request Approvals/Query',
  'Private Stores/Collections/Offers/Upsert Offer With Multi Context',
  'Mediaservices/Streaming Policies',
  'Mediaservices/Account Filters',
  'My Sqlsites/Error Summaries',
  'L3Networks',
  'Import Sites',
  'Springbootsites/Springbootservers',
  'Available Ground Stations',
  'Check Eligibility',
  'Peering Service Providers',
  'Operator Connections',
  'Group Quotas/Quota Allocation Requests',
  'Locations/Mobo Operation Statuses',
  'Calculate Template Hash',
  'Subscriptions/Operationresults',
  'Azure Dev Ops Connectors/Orgs/Projects/Repos',
  'Git Lab Connectors/Projects',
  'Office Consents',
  'Workspace Manager Configurations',
  'Namespaces/Topics/Authorizationrules',
  'Clusters/Application Types/Versions',
  'Locations/Environments/Managed Cluster Versions',
  'Traffic Controllers/Frontends',
  'Accounts/Account Quota Policies',
  'Locations/Instance Type Series',
  'Get Required Aml Fssubnets Size',
  'Rename',
  'Accept Ownership',
  'Locations/Sql Database Azure Async Operation',
  'Test Base Accounts/Feature Update Supported Oses',
  'Test Base Accounts/Gallery Apps',
  'Static Sites/Builds/Database Connections',
  'Locations/Deleted Sites',
  'Hosting Environments/Event Grid Filters',
  'Locations/Sap Virtual Instance Metadata',
  'Cloud Vm Clusters/Virtual Network Addresses',
  'Locations/Dns Private Views',
  'Locations/Autonomous Database National Character Sets',
  'Apollo',
  'Saasresources',
  'Sql Virtual Machine Groups',
  'Sql Virtual Machines',
  'Locations/Sql Virtual Machine Operation Results',
  'Locations/Sql Virtual Machine Group Operation Results',
  'Locations/Availability Group Listener Operation Results',
  'Locations/Register Sql Vm Candidate',
  'Billing Accounts/Billing Profiles/Patch Operations',
  'Billing Accounts/Billing Profiles/Invoice Sections/Products/Transfer',
  'Blueprint Assignments/Operations',
  'Workspaces/Iotconnectors/Fhirdestinations',
  'Private Link Scopes/Network Security Perimeter Configurations',
  'Publishers/Artifactstores/Artifacts',
  'Net App Accounts/Capacity Pools/Volumes/Mount Targets',
  'Azure Traffic Collectors/Collector Policies',
  'Group Quotas/Group Quota Operations Status',
  'Storage Sync Services/Sync Groups/Server Endpoints',
  'User Assigned Identities/Federated Identity Credentials',
  'Virtual Networks/List Network Manager Effective Connectivity Configurations',
  'Automation Accounts/Software Update Configuration Runs',
  'Profiles/Keygroups',
  'Grafana/Private Endpoint Connections',
  'Custom Locations/Resource Sync Rules',
  'Marketplace Registration Definitions',
  'Private Link Services For Power Bi/Operation Results',
  'Environments/Private Endpoint Connection Proxies',
];
export const opList1 = [
  { key: '=', value: 'equal' },
  { key: '!=', value: 'not equal' },
];
export const opList2 = [
  { key: '<', value: 'less than' },
  { key: '>', value: 'greater than' },
  { key: '=', value: 'equal' },
  { key: '!=', value: 'not equal' },
];
export const opList3 = [
  { key: '=', value: 'equal' },
  { key: '!=', value: 'not equal' },
  { key: 'Contains', value: 'contains' },
  { key: 'Not contains', value: 'not contains' },
  { key: 'Starts with', value: 'startswith' },
  { key: 'Ends with', value: 'endswith' },
];
export const opList4 = [
  { key: '<', value: 'less than' },
  { key: '>', value: 'greater than' },
];
export const TargetType = ['Cloud', 'Host', 'Local'];
export const ScriptType = [
  'Ansible Playbook',
  'Bash Script',
  'Powershell Script',
  'Python Script',
  'Terraform Script',
];
export const StatusType = ['In Progress', 'Success', 'Failed'];
