# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-03 12:18
from __future__ import unicode_literals

import app.common.func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_auto_20250808_0212'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('access_token', models.CharField(blank=True, max_length=256, null=True)),
                ('org', models.ManyToManyField(related_name='ai_agents', to='organization.Organization')),
            ],
            options={
                'verbose_name': 'AI Agent',
            },
        ),
    ]
