# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-03 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_aiagents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiagents',
            options={'verbose_name': 'AI Agents'},
        ),
        migrations.AddField(
            model_name='aiagents',
            name='queries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), default=list, size=None),
        ),
    ]
