# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-30 18:43
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_aiagents_tokens(apps, schema_editor):
    AIAgents = apps.get_model("common", "aiagents")
    for row in AIAgents.objects.all():
            row._access_token = row.access_token
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20251003_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagents',
            name='_access_token',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_aiagents_tokens),
        migrations.RemoveField(
            model_name='aiagents',
            name='access_token',
        ),
        migrations.RenameField(
            model_name='aiagents',
            old_name='_access_token',
            new_name='access_token',
        )
    ]
