# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-05 18:48
from __future__ import unicode_literals

import app.dc_cost.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CloudService', '0005_auto_20210608_0942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datacenter', '0002_auto_20210416_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatacenterBillingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cabinet_rental_model', models.CharField(choices=[('Full Cabinet', 'Full Cabinet'), ('RU', 'RU')], max_length=30)),
                ('cabinet_unit_cost', models.PositiveIntegerField()),
                ('power_circuit_cost', models.PositiveIntegerField()),
                ('redundant_power', models.BooleanField(default=False)),
                ('contract_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(app.dc_cost.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('datacenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CloudService.ColoCloud')),
                ('power_circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.PowerCircuit')),
            ],
        ),
    ]
