# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.common.func
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmpsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amps_type', models.CharField(
                    choices=[('10A', '10A'), ('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'),
                             ('50A', '50A')], default='10A', max_length=10, unique=True, verbose_name='Amps Type')),
            ],
            options={
                'db_table': 'ampstypes',
                'verbose_name': 'Power Amps Types',
                'permissions': (('view', 'Can view power amps types'),),
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, unique=True, verbose_name='Name')),
                ('model', models.CharField(max_length=128, null=True, verbose_name='Cabinet Model')),
                ('size', models.IntegerField(default=42, verbose_name='Cabinet Size')),
                ('is_allocated', models.BooleanField(default=False, verbose_name='State')),
                ('salesforce_id',
                 models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Salesforce ID')),
                ('available_size', models.CharField(blank=True, default='42U', max_length=128, null=True)),
                ('uuid',
                 models.UUIDField(blank=True, default=app.common.func.generate_uuid, null=True, verbose_name='UUID')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'cabinet',
                'verbose_name': 'Cabinet',
                'permissions': (('view', 'Can view cabinet'),),
            },
        ),
        migrations.CreateModel(
            name='CabinetModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, unique=True, verbose_name='Cabinet Model')),
                ('size', models.CharField(default='42U', max_length=128, verbose_name='Cabinet Size')),
            ],
            options={
                'ordering': ['model'],
                'db_table': 'cabinet_model',
                'verbose_name': 'Cabinets',
                'permissions': (('view', 'Can view cabinet models'),),
            },
        ),
        migrations.CreateModel(
            name='CabinetTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_type',
                 models.CharField(default='SHARED', max_length=64, unique=True, verbose_name='Cabinet Type')),
            ],
            options={
                'ordering': ['cabinet_type'],
                'db_table': 'cabinettypes',
                'verbose_name': 'Cabinet Types',
                'permissions': (('view', 'Can view cabinet types'),),
            },
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, unique=True, verbose_name='Name')),
                ('is_allocated', models.BooleanField(default=False, verbose_name='State')),
                ('salesforce_id',
                 models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Salesforce ID')),
                ('uuid',
                 models.UUIDField(blank=True, default=app.common.func.generate_uuid, null=True, verbose_name='UUID')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'cage',
                'verbose_name': 'Cage',
                'permissions': (('view', 'Can view cage'),),
            },
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='SF9', max_length=128)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'DataCenter',
                'permissions': (('view', 'Can view datacenter'),),
            },
        ),
        migrations.CreateModel(
            name='ElectricalCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Circuit Name')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'electricalcircuit',
                'verbose_name': 'Electrical Circuit',
                'permissions': (('view', 'Can view electrical circuit'),),
            },
        ),
        migrations.CreateModel(
            name='ElectricalPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('max_num_breakers', models.IntegerField(default=42)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'electricalpanel',
                'verbose_name': 'Electrical Panel',
                'permissions': (('view', 'Can view electrical panel'),),
            },
        ),
        migrations.CreateModel(
            name='ElectricalPanelBreaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'electricalpanelbreaker',
                'verbose_name': 'Electrical Panel',
                'permissions': (('view', 'Can view electrical panel breaker'),),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('latitude',
                 models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude',
                 models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Datacenter Location',
                'permissions': (('view', 'Can view location'),),
            },
        ),
        migrations.CreateModel(
            name='OutletTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_type', models.CharField(max_length=64, unique=True, verbose_name='Outlet Type')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'outlettypes',
                'verbose_name': 'Power Outlet Types',
                'permissions': (('view', 'Can view power outlet types'),),
            },
        ),
        migrations.CreateModel(
            name='PowerCircuit',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, unique=True, verbose_name='Name')),
                ('assettag', models.SlugField(blank=True, max_length=128, null=True, verbose_name='AssetTag')),
                ('is_allocated', models.BooleanField(default=False)),
                ('salesforce_id',
                 models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Salesforce ID')),
                ('ampstype',
                 models.ForeignKey(db_column='amps_type_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='datacenter.AmpsTypes')),
                ('circuit', models.ForeignKey(blank=True, db_column='circuit_id', null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              to='datacenter.ElectricalCircuit', verbose_name='Breaker')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'powercircuit',
                'verbose_name': 'Power Circuit',
                'permissions': (('view', 'Can view power circuit'),),
            },
        ),
        migrations.CreateModel(
            name='VoltageTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_type', models.CharField(
                    choices=[('50V', '50V'), ('110V', '110V'), ('160V', '160V'), ('180V', '180V'), ('220V', '220V'),
                             ('240V', '240V')], default='50V', max_length=10, unique=True,
                    verbose_name='Voltage Type')),
            ],
            options={
                'db_table': 'voltagetypes',
                'verbose_name': 'Power Voltage Types',
                'permissions': (('view', 'Can view power voltate types'),),
            },
        ),
    ]
