# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('datacenter', '0001_initial'),
        ('salesforce', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powercircuit',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='powercircuit',
            name='datacenter',
            field=models.ForeignKey(db_column='datacenter_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='datacenter.Datacenter'),
        ),
        migrations.AddField(
            model_name='powercircuit',
            name='outlettype',
            field=models.ForeignKey(db_column='outlet_type_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='datacenter.OutletTypes'),
        ),
        migrations.AddField(
            model_name='powercircuit',
            name='panel',
            field=models.ForeignKey(db_column='panel_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='datacenter.ElectricalPanel'),
        ),
        migrations.AddField(
            model_name='powercircuit',
            name='salesforce_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='salesforce.SalesforceRecord'),
        ),
        migrations.AddField(
            model_name='powercircuit',
            name='voltagetype',
            field=models.ForeignKey(db_column='voltage_type_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='datacenter.VoltageTypes'),
        ),
        migrations.AddField(
            model_name='electricalpanelbreaker',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.ElectricalCircuit'),
        ),
        migrations.AddField(
            model_name='electricalpanelbreaker',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.ElectricalPanel'),
        ),
        migrations.AddField(
            model_name='electricalcircuit',
            name='panel',
            field=models.ForeignKey(db_column='panel_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='datacenter.ElectricalPanel'),
        ),
        migrations.AddField(
            model_name='cage',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='cage',
            name='datacenter',
            field=models.ForeignKey(db_column='datacenter_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='datacenter.Datacenter'),
        ),
        migrations.AddField(
            model_name='cage',
            name='salesforce_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='salesforce.SalesforceRecord'),
        ),
        migrations.AddField(
            model_name='cabinetmodels',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='inventory.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cabinet_type',
            field=models.ForeignKey(db_column='cabinet_type_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='datacenter.CabinetTypes'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cage',
            field=models.ForeignKey(blank=True, db_column='cage_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cage'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='customers',
            field=models.ManyToManyField(related_name='cabinet_customers', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='salesforce_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='salesforce.SalesforceRecord'),
        ),
    ]
