# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-19 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_auto_20210416_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='annual_escalation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='contract_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='contract_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='renewal',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
