# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_auto_20220328_0426'),
        ('datacenter', '0003_auto_20210819_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cabinet_tags', to='inventory.Tag'),
        ),
    ]
