# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_auto_20230201_0855'),
        ('datacenter', '0004_cabinet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='co2_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='number_of_devices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='pduA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_pduA', to='inventory.PDU'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='pduB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_pduB', to='inventory.PDU'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='pduC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_pduC', to='inventory.PDU'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='pduD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_pduD', to='inventory.PDU'),
        ),
    ]
