# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-31 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_auto_20230201_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
