# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.common.func
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vlan_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4096)])),
                ('verified', models.BooleanField(default=False)),
                ('ulid', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together=set([('vlan_number', 'region')]),
        ),
    ]
