# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-06-03 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
