# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.common.func
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0002_auto_20210416_0415'),
        ('common', '0001_initial'),
        ('datacenter', '0002_auto_20210416_0415'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceDatacenterMview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'instance_datacenter_mview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CabinetCustomerMapping',
            fields=[
                ('cab_cust_map_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cabinetcustomermapping',
                'verbose_name': 'Cabinet',
            },
        ),
        migrations.CreateModel(
            name='CabinetItemMap',
            fields=[
                ('cimap_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'cabinetitemmap',
            },
        ),
        migrations.CreateModel(
            name='CabinetOption',
            fields=[
                ('cabinetoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('cabinet_options',
                 models.CharField(default='Full', max_length=128, unique=True, verbose_name='Cabinet Options')),
            ],
            options={
                'ordering': ['cabinet_options'],
                'db_table': 'cabinetoption',
                'verbose_name': 'Cabinet',
                'permissions': (('view', 'Can view cabinetoption'),),
            },
        ),
        migrations.CreateModel(
            name='CircuitOption',
            fields=[
                ('circuitoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('circuits',
                 models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Circuits')),
                ('power_type', models.CharField(default='AC', max_length=128, verbose_name='Power Type')),
                ('power_size', models.CharField(default='120V', max_length=128, verbose_name='Power Size')),
                ('power_configuration', models.CharField(max_length=128, verbose_name='Configuration')),
            ],
            options={
                'ordering': ['circuits'],
                'db_table': 'circuitoption',
                'verbose_name': 'Circuit',
                'permissions': (('view', 'Can view circuitoption'),),
            },
        ),
        migrations.CreateModel(
            name='CloudTypes',
            fields=[
                ('cloud_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloud_type', models.CharField(default='Custom', max_length=128, unique=True, verbose_name='Type')),
                ('vcpu', models.IntegerField(verbose_name='vCPU')),
                ('memorysize', models.IntegerField(null=True, verbose_name='Memory Size')),
                ('memory_measuretype',
                 models.CharField(choices=[('GB', 'GB'), ('TB', 'TB'), ('MB', 'MB')], default='GB', max_length=12,
                                  verbose_name='Type')),
                ('disksize', models.IntegerField(null=True, verbose_name='Disk Size')),
                ('disk_measuretype',
                 models.CharField(choices=[('GB', 'GB'), ('TB', 'TB'), ('MB', 'MB')], default='GB', max_length=12,
                                  verbose_name='Type')),
                ('ethports', models.IntegerField()),
            ],
            options={
                'db_table': 'cloudtypes',
                'verbose_name': 'Cloud Types',
                'permissions': (('view', 'Can view cloudtypes'),),
            },
        ),
        migrations.CreateModel(
            name='CustomerInstanceMap',
            fields=[
                ('cust_ins_map_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customerinstancemap',
                'verbose_name': 'Instance',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('addressablemodel_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      to='common.AddressableModel')),
                ('created_user', models.CharField(max_length=128)),
                ('modified_user', models.CharField(max_length=128)),
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Instance Name')),
                ('instance_type', models.CharField(blank=True,
                                                   choices=[('Hypervisor', 'Hypervisor'), ('Physical', 'Physical'),
                                                            ('SAN', 'SAN'), ('Virtual', 'Virtual')],
                                                   db_column='instance_type_id', max_length=32, null=True)),
                ('virtualization_type', models.CharField(default='None', max_length=32)),
                ('state', models.CharField(blank=True, max_length=128, null=True, verbose_name='State')),
                ('os_rootuser', models.CharField(blank=True, max_length=128, null=True, verbose_name='Root User')),
                ('os_rootpassword',
                 models.CharField(blank=True, max_length=256, null=True, verbose_name='Root Password')),
                ('os_privatekey',
                 models.CharField(blank=True, max_length=2040, null=True, verbose_name='Private Key Path')),
                ('functional_hostname',
                 models.CharField(blank=True, max_length=128, null=True, verbose_name='Functional Hostname')),
                ('is_allocated', models.BooleanField(default=False, verbose_name='Instance Allocation State')),
                ('is_vdc', models.BooleanField(default=False, verbose_name='SET VDC')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Assigned Date')),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ordered Date')),
                ('ulapi_uuid', models.UUIDField(blank=True, null=True, verbose_name='ULAPI_UUID')),
                ('uuid',
                 models.UUIDField(blank=True, default=app.common.func.generate_uuid, null=True, verbose_name='UUID')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'instance',
                'verbose_name': 'Instance',
                'permissions': (('view', 'Can View instance'),),
            },
            bases=('common.addressablemodel', models.Model),
        ),
        migrations.CreateModel(
            name='InstanceConnectionDetails',
            fields=[
                ('icd_id', models.AutoField(primary_key=True, serialize=False)),
                ('interface_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Interface')),
                ('interface_type',
                 models.CharField(blank=True, max_length=128, null=True, verbose_name='Interface Type')),
                ('nic_macaddress',
                 models.CharField(blank=True, max_length=30, null=True, verbose_name='NIC MAC Address')),
                ('nic_ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='NIC IP Address')),
                ('default_gateway',
                 models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='Default Gateway')),
                ('vlan_tag', models.CharField(blank=True, max_length=128, null=True, verbose_name='VLAN Tag')),
                ('pxeinterface', models.BooleanField(default=False, verbose_name='PXE Interface')),
                ('management_interface', models.BooleanField(default=False, verbose_name='Management Interface')),
                ('bridge_mode', models.BooleanField(default=False, verbose_name='Bridge mode')),
            ],
            options={
                'db_table': 'instanceconnectiondetails',
                'verbose_name': 'Instance connection',
                'permissions': (('view', 'Can view Instance connection details'),),
            },
        ),
        migrations.CreateModel(
            name='InstanceTypes',
            fields=[
                ('instance_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_type',
                 models.CharField(default='PHYSICAL', max_length=128, unique=True, verbose_name='Instance Type')),
            ],
            options={
                'ordering': ['instance_type'],
                'db_table': 'instancetypes',
                'permissions': (('view', 'Can view instancetypes'),),
            },
        ),
        migrations.CreateModel(
            name='MotherboardPeripheralMap',
            fields=[
                ('mb_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('peripheral_id', models.IntegerField(blank=True)),
                ('onboard_peripheral', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['mb_map_id'],
                'db_table': 'motherboardperipheralmap',
                'verbose_name': 'Motherboard',
            },
        ),
        migrations.CreateModel(
            name='ProductAdminMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
            ],
            options={
                'ordering': ['product_id'],
                'db_table': 'productadminmapping',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'producttypes',
                'permissions': (('view', 'Can view producttypes'),),
            },
        ),
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_user', models.CharField(max_length=128)),
                ('modified_user', models.CharField(max_length=128)),
                ('colocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('colocation_name', models.CharField(default='San Francisco', max_length=45)),
                ('cages', models.CharField(blank=True, max_length=45, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(blank=True, db_column='cabinet_id', null=True,
                                              on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cabinet')),
                ('cabinetoption', models.ForeignKey(blank=True, db_column='cabinetoption_id', null=True,
                                                    on_delete=django.db.models.deletion.CASCADE,
                                                    to='server.CabinetOption')),
                ('circuitoption', models.ForeignKey(blank=True, db_column='circuitoption_id', null=True,
                                                    on_delete=django.db.models.deletion.CASCADE,
                                                    to='server.CircuitOption')),
                ('customer', models.ForeignKey(blank=True, db_column='organization_id', null=True,
                                               on_delete=django.db.models.deletion.CASCADE,
                                               to='organization.Organization')),
                ('switch', models.ForeignKey(blank=True, db_column='switch_id', null=True,
                                             on_delete=django.db.models.deletion.CASCADE, to='inventory.Switch')),
            ],
            options={
                'ordering': ['colocation_id'],
                'db_table': 'colocation',
                'verbose_name': 'Racks',
                'permissions': (('view', 'Can view racks'),),
            },
        ),
        migrations.CreateModel(
            name='SystemPDUMap',
            fields=[
                ('spdu_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdu_port_number', models.IntegerField(blank=True, null=True)),
                ('pdu', models.ForeignKey(blank=True, db_column='pdu_id', null=True,
                                          on_delete=django.db.models.deletion.CASCADE, to='inventory.PDU')),
                ('system', models.ForeignKey(blank=True, db_column='system_id', null=True,
                                             on_delete=django.db.models.deletion.CASCADE, to='inventory.Server')),
                ('system_port', models.ForeignKey(blank=True, db_column='system_port_id', null=True,
                                                  on_delete=django.db.models.deletion.CASCADE,
                                                  to='inventory.SystemPowerSupplyPort')),
            ],
            options={
                'db_table': 'systempdumap',
            },
        ),
        migrations.CreateModel(
            name='SystemSwitchMap',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('interface_name', models.CharField(blank=True, max_length=128, null=True)),
                ('switch_port_number', models.IntegerField(blank=True, null=True)),
                ('switch', models.ForeignKey(blank=True, db_column='switch_id', null=True,
                                             on_delete=django.db.models.deletion.CASCADE, to='inventory.Switch')),
                ('system', models.ForeignKey(blank=True, db_column='system_id', null=True,
                                             on_delete=django.db.models.deletion.CASCADE, to='inventory.Server')),
            ],
            options={
                'db_table': 'systemswitchmap',
            },
        ),
    ]
