# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0002_auto_20210416_0415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20210416_0415'),
        ('datacenter', '0002_auto_20210416_0415'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadminmapping',
            name='admin',
            field=models.ForeignKey(blank=True, db_column='admin_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productadminmapping',
            name='product_type',
            field=models.ForeignKey(blank=True, db_column='product_type_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='server.ProductTypes'),
        ),
        migrations.AddField(
            model_name='motherboardperipheralmap',
            name='motherboard',
            field=models.ForeignKey(db_column='motherboard_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='inventory.Motherboard'),
        ),
        migrations.AddField(
            model_name='motherboardperipheralmap',
            name='peripheral_type',
            field=models.ForeignKey(blank=True, db_column='peripheral_type_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='inventory.PeripheralTypes'),
        ),
        migrations.AddField(
            model_name='instanceconnectiondetails',
            name='instance',
            field=models.ForeignKey(blank=True, db_column='instance_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='server.Instance'),
        ),
        migrations.AddField(
            model_name='instanceconnectiondetails',
            name='system',
            field=models.ForeignKey(blank=True, db_column='system_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='inventory.Server'),
        ),
        migrations.AddField(
            model_name='instance',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='instance',
            name='os',
            field=models.ForeignKey(blank=True, db_column='os_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='inventory.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='instance',
            name='system',
            field=models.OneToOneField(blank=True, db_column='system_id', null=True,
                                       on_delete=django.db.models.deletion.CASCADE, related_name='instance',
                                       to='inventory.Server'),
        ),
        migrations.AddField(
            model_name='instance',
            name='virtualsystem',
            field=models.OneToOneField(blank=True, db_column='virtualsystem_id', null=True,
                                       on_delete=django.db.models.deletion.CASCADE, related_name='instance',
                                       to='inventory.VirtualMachine', verbose_name='Virtual System'),
        ),
        migrations.AddField(
            model_name='customerinstancemap',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='customerinstancemap',
            name='instance',
            field=models.ForeignKey(blank=True, db_column='instance_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='server.Instance'),
        ),
        migrations.AddField(
            model_name='cabinetitemmap',
            name='cabinet',
            field=models.ForeignKey(blank=True, db_column='cabinet_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cabinet'),
        ),
        migrations.AddField(
            model_name='cabinetcustomermapping',
            name='cabinet',
            field=models.ForeignKey(blank=True, db_column='cabinet_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='datacenter.Cabinet'),
        ),
        migrations.AddField(
            model_name='cabinetcustomermapping',
            name='cabinet_option',
            field=models.ForeignKey(blank=True, db_column='cabinet_option_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='server.CabinetOption'),
        ),
        migrations.AddField(
            model_name='cabinetcustomermapping',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
