# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210416_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='os',
            field=models.ForeignKey(blank=True, db_column='os_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.OperatingSystem'),
        ),
    ]
