# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-29 19:17
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_instance_passwords(apps, schema_editor):
    Instance = apps.get_model("server", "instance")
    for row in Instance.objects.all():
            row._os_rootpassword = row.os_rootpassword
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20241129_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='_os_rootpassword',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_instance_passwords),
        migrations.RemoveField(
            model_name='instance',
            name='os_rootpassword',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='_os_rootpassword',
            new_name='os_rootpassword',
        )
    ]
