# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-01-08 09:14
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_key(apps, schema_editor):
    instance = apps.get_model("server", "instance")
    for row in instance.objects.all():
            row._os_privatekey = row.os_privatekey
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_instance__os_rootpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='_os_privatekey',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_key),
        migrations.RemoveField(
            model_name='instance',
            name='os_privatekey',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='_os_privatekey',
            new_name='os_privatekey',
        )
    ]
