# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ULUserSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(null=True)),
            ],
            options={
                'db_table': 'ulusersession',
                'verbose_name': 'ulsession',
                'verbose_name_plural': 'ulsessions',
            },
        ),
    ]
