# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.common.func
import app.customer_onboarding.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inet', models.CharField(max_length=25)),
                ('scan_status', models.CharField(
                    choices=[
                        (b'INITIATED', b'INITIATED'),
                        (b'COMPLETED', b'COMPLETED'),
                        (b'RESCANNING', b'RESCANNING'),
                        (b'ABORTED', b'ABORTED')
                    ],
                    max_length=20
                )),
                ('scan_results', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Network Scan',
            },
        ),
        migrations.CreateModel(
            name='OnboardingExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.FileField(upload_to=app.customer_onboarding.models.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
