# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-06-07 07:15
from __future__ import unicode_literals

import app.common.func
import app.customer_onboarding.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_auto_20220505_0535'),
        ('customer_onboarding', '0002_auto_20210416_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingExcelFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.FileField(upload_to=app.customer_onboarding.models.user_directory_path)),
                ('onb_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('onb_status', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('customer', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='customer_onboard_data',
                    to='organization.Organization'
                )),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
