# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-06-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_onboarding', '0003_onboardingexcelfiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingexcelfiledata',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_onboard_data', to='organization.Organization'),
        ),
    ]
