# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-06-03 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_onboarding', '0004_auto_20220607_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkscan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onboardingexcelfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onboardingexcelfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onboardingexcelfiledata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onboardingexcelfiledata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
