# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_user', models.CharField(max_length=128)),
                ('modified_user', models.CharField(max_length=128)),
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=128, verbose_name='Group Name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'groups',
                'permissions': (('view', 'Can view groups'),),
            },
        ),
    ]
