# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-18 05:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('service_name', models.CharField(db_index=True, max_length=255)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[(b'TRACE', b'Trace'), (b'DEBUG', b'Debug'), (b'INFO', b'Info'), (b'WARN', b'Warning'), (b'ERROR', b'Error'), (b'FATAL', b'Fatal')], db_index=True, max_length=10)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('span_id', models.CharField(blank=True, max_length=16, null=True)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resources', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=32)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('service_name', models.CharField(db_index=True, max_length=255)),
                ('root_operation', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('duration_ms', models.FloatField(db_index=True)),
                ('status_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('error_count', models.IntegerField(default=0)),
                ('http_method', models.CharField(blank=True, max_length=10, null=True)),
                ('http_route', models.CharField(blank=True, max_length=512, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('service_version', models.CharField(blank=True, max_length=50, null=True)),
                ('service_instance', models.CharField(blank=True, max_length=255, null=True)),
                ('sdk_language', models.CharField(blank=True, max_length=50, null=True)),
                ('span_count', models.IntegerField()),
                ('error_span_count', models.IntegerField(default=0)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('resources', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=[b'trace_id'], name='apm_trace_trace_i_02f0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=[b'tenant_id', b'service_name'], name='apm_trace_tenant__b0d47a_idx'),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=[b'start_time', b'end_time'], name='apm_trace_start_t_6a3651_idx'),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=[b'duration_ms'], name='apm_trace_duratio_4446e0_idx'),
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=[b'is_error'], name='apm_trace_is_erro_88cdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=[b'timestamp', b'severity'], name='apm_log_timesta_870a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=[b'service_name', b'tenant_id'], name='apm_log_service_0664eb_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=[b'trace_id'], name='apm_log_trace_i_6ab4f9_idx'),
        ),
    ]
