# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-18 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('tenant', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('labels', models.TextField()),
            ],
        ),
    ]
