# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apm', '0002_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='device_id',
        ),
        migrations.AddField(
            model_name='log',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.MonitoredApp'),
        ),
        migrations.AddField(
            model_name='metric',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.MonitoredApp'),
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='device_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='hostname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='latency',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='throughput',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trace',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.MonitoredApp'),
        ),
    ]
