# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-19 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0003_auto_20250618_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredapp',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredapp',
            name='latency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredapp',
            name='throughput',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
