# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-20 09:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0004_auto_20250619_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='APMTopology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.MonitoredApp')),
            ],
        ),
    ]
