# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-23 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0005_apmtopology'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapp',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
