# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-23 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apm', '0006_monitoredapp_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredapp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='monitoredapp',
            unique_together=set([('name', 'content_type', 'device_id')]),
        ),
    ]
