# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0007_auto_20250622_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
