# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0008_metric_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='is_created',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
