# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-07-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0009_metric_is_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('throughput', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default=b'1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(default=b'service', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default=b'1', max_length=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='apm.APMTopology')),
            ],
        ),
        migrations.AddField(
            model_name='topologyedge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='apm.TopologyNode'),
        ),
        migrations.AddField(
            model_name='topologyedge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='apm.TopologyNode'),
        ),
        migrations.AddField(
            model_name='topologyedge',
            name='topology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='apm.APMTopology'),
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='parent_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.ParentApp'),
        ),
        migrations.AlterUniqueTogether(
            name='topologynode',
            unique_together=set([('topology', 'node_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='topologyedge',
            unique_together=set([('topology', 'source', 'target')]),
        ),
    ]
