# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-07-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20240107_0332'),
        ('apm', '0010_auto_20250711_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
