# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-05 06:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0011_monitoredapp_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_app', models.CharField(choices=[(b'WEB', b'Web'), (b'MIDDLEWARE', b'Middleware'), (b'CLOUD NATIVE APPS', b'Cloud Native Apps'), (b'DATABASE & CACHE INTERACTIONS', b'Database & Cache Interactions'), (b'MICROSERVICES & APIs', b'Microservices & APIs'), (b'FATAL', b'Fatal')], max_length=50)),
                ('business_criticality', models.CharField(choices=[(b'PRODUCTION', b'Production'), (b'PRE PROD', b'Pre-Prod'), (b'STAGING', b'Staging'), (b'UAT', b'UAT'), (b'QA', b'QA'), (b'TEST', b'Test'), (b'DEV', b'Dev')], max_length=50)),
                ('env', models.CharField(choices=[(b'PRODUCTION', b'Production'), (b'PRE PROD', b'Pre-Prod'), (b'STAGING', b'Staging'), (b'UAT', b'UAT'), (b'QA', b'QA'), (b'TEST', b'Test'), (b'DEV', b'Dev')], max_length=50)),
                ('deployment_model', models.CharField(choices=[(b'AZURE', b'Azure'), (b'AWS', b'AWS'), (b'GOOGLE CLOUD', b'Google'), (b'ORACLE', b'Oracle')], max_length=50)),
                ('cloud_types', models.CharField(choices=[(b'AZURE', b'Azure'), (b'AWS', b'AWS'), (b'GOOGLE CLOUD', b'Google'), (b'ORACLE', b'Oracle')], max_length=50)),
                ('visibility', models.CharField(choices=[(b'Private', b'Private'), (b'Organization', b'Organization')], default=b'Private', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseCostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='business_service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.BusinessService'),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='license_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.LicenseCostCenter'),
        ),
    ]
