# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0012_auto_20250804_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='business_criticality',
            field=models.CharField(choices=[(b'CRITICAL', b'Critical'), (b'HIGH', b'High'), (b'MEDIUM', b'Medium'), (b'LOW', b'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='deployment_model',
            field=models.CharField(choices=[(b'ON-PREM', b'On-Prem'), (b'CLOUD', b'Cloud'), (b'HYBRID', b'Hybrid'), (b'MULTI-CLOUD', b'Multi-Cloud')], max_length=50),
        ),
    ]
