# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0013_auto_20250806_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModelLicenseCostCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_app', models.CharField(choices=[(b'WEB', b'Web'), (b'MIDDLEWARE', b'Middleware'), (b'CLOUD NATIVE APPS', b'Cloud Native Apps'), (b'DATABASE & CACHE INTERACTIONS', b'Database & Cache Interactions'), (b'MICROSERVICES & APIs', b'Microservices & APIs'), (b'FATAL', b'Fatal')], max_length=50)),
                ('business_criticality', models.CharField(choices=[(b'CRITICAL', b'Critical'), (b'HIGH', b'High'), (b'MEDIUM', b'Medium'), (b'LOW', b'Low')], max_length=50)),
                ('env', models.CharField(choices=[(b'PRODUCTION', b'Production'), (b'PRE PROD', b'Pre-Prod'), (b'STAGING', b'Staging'), (b'UAT', b'UAT'), (b'QA', b'QA'), (b'TEST', b'Test'), (b'DEV', b'Dev')], max_length=50)),
                ('deployment_model', models.CharField(choices=[(b'ON-PREM', b'On-Prem'), (b'CLOUD', b'Cloud'), (b'HYBRID', b'Hybrid'), (b'MULTI-CLOUD', b'Multi-Cloud')], max_length=50)),
                ('cloud_types', models.CharField(choices=[(b'AZURE', b'Azure'), (b'AWS', b'AWS'), (b'GOOGLE CLOUD', b'Google'), (b'ORACLE', b'Oracle')], max_length=50)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.ParentApp')),
            ],
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='business_criticality',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='cloud_types',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='deployment_model',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='env',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='license_cost_center',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='type_of_app',
        ),
        migrations.AddField(
            model_name='businessmodellicensecostcentre',
            name='business_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_model', to='apm.BusinessModel'),
        ),
    ]
