# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0015_auto_20250807_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='businessmodel_license_cost_centre',
        ),
        migrations.AddField(
            model_name='businessmodellicensecostcentre',
            name='business_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_model', to='apm.BusinessModel'),
            preserve_default=False,
        ),
    ]
