# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0016_auto_20250807_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodellicensecostcentre',
            name='business_service',
        ),
    ]
