# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0018_businessmodellicensecostcentre_business_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodellicensecostcentre',
            name='business_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_model', to='apm.BusinessModel'),
        ),
    ]
