# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0019_auto_20250807_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodellicensecostcentre',
            name='business_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_cost_centers', to='apm.BusinessModel'),
        ),
    ]
