# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 10:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0020_auto_20250807_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
