# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0021_rbacgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='rbac_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.RBACGroup'),
        ),
    ]
