# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0022_businessmodel_rbac_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodellicensecostcentre',
            name='license_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_centers_ind', to='apm.LicenseCostCenter'),
        ),
    ]
