# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-12 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apm', '0024_auto_20250811_0455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoredapp',
            unique_together=set([('name', 'content_type', 'device_id', 'parent_app')]),
        ),
    ]
