# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0025_auto_20250812_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentapp',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
