# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0026_auto_20250812_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmtopology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apmtopology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
