# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0027_auto_20250820_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='status',
            field=models.CharField(choices=[(b'ENABLE', b'Enable'), (b'DISABLE', b'Disable')], default=b'ENABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='apmtopology',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology', to='apm.MonitoredApp'),
        ),
    ]
