# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-21 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0028_auto_20250821_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='status',
        ),
    ]
