# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0029_remove_businessmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='status',
            field=models.CharField(choices=[(b'ENABLE', b'Enable'), (b'DISABLE', b'Disable')], default=b'ENABLE', max_length=10),
        ),
    ]
