# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apm', '0030_businessmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topologynode',
            name='device',
        ),
        migrations.RemoveField(
            model_name='topologynode',
            name='host',
        ),
        migrations.AddField(
            model_name='topologynode',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='topologynode',
            name='device_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
