# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-28 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0031_auto_20250827_0316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topologynode',
            unique_together=set([]),
        ),
    ]
