# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-02 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0032_auto_20250828_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbacgroup',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='rbac_group',
        ),
        migrations.DeleteModel(
            name='RBACGroup',
        ),
    ]
