# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finops', '0009_merge_20250805_1031'),
        ('apm', '0033_auto_20250902_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodellicensecostcentre',
            name='building_blocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finops.BuildingBlock'),
        ),
    ]
