# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0034_businessmodellicensecostcentre_building_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentapp',
            name='name',
            field=models.CharField(default=b'Unknown', max_length=100),
        ),
    ]
