# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-11 06:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0035_auto_20250902_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessservice',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
