# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0037_auto_20250910_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapp',
            name='type_of_app',
            field=models.CharField(choices=[(b'WEB', b'Web'), (b'MIDDLEWARE', b'Middleware'), (b'CLOUD NATIVE APPS', b'Cloud Native Apps'), (b'DATABASE & CACHE INTERACTIONS', b'Database & Cache Interactions'), (b'MICROSERVICES & APIs', b'Microservices & APIs')], default=b'WEB', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessmodellicensecostcentre',
            name='type_of_app',
            field=models.CharField(choices=[(b'WEB', b'Web'), (b'MIDDLEWARE', b'Middleware'), (b'CLOUD NATIVE APPS', b'Cloud Native Apps'), (b'DATABASE & CACHE INTERACTIONS', b'Database & Cache Interactions'), (b'MICROSERVICES & APIs', b'Microservices & APIs')], max_length=50),
        ),
    ]
