# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0038_auto_20250911_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
