# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-23 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apm', '0039_businessmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
