# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-24 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_auto_20250808_0212'),
        ('apm', '0040_businessmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentapp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
