# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-24 14:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_auto_20250808_0212'),
        ('apm', '0041_parentapp_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=50)),
                ('params', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
