# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0042_topologycache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topologycache',
            name='params',
        ),
        migrations.AddField(
            model_name='topologycache',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology_cache_data', to='apm.ParentApp'),
        ),
    ]
