# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0043_auto_20250925_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentapp',
            name='latency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parentapp',
            name='throughput',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
