# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-06 11:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_auto_20250808_0212'),
        ('apm', '0044_auto_20250926_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactAnalysisCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.ParentApp')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='impactanalysiscache',
            unique_together=set([('customer', 'app')]),
        ),
    ]
