# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0045_auto_20251006_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentapp',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
