# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-10-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0041_organization_is_rag_enabled'),
        ('apm', '0046_parentapp_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouped_graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('metrics_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.Metric')),
            ],
        ),
    ]
