# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-03-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0047_grouped_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentapp',
            name='response_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
