# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-04-01 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0047_grouped_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapp',
            name='availability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='response_time',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='monitoredapp',
            name='status_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
