# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-04-08 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0048_auto_20260401_0303'),
        ('apm', '0048_parentapp_response_time'),
    ]

    operations = [
    ]
