# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-06-16 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apm', '0049_merge_20260408_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='APMOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('deployed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], default=b'active', max_length=50)),
                ('device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('java_agent_dir', models.TextField()),
                ('java_tool_option', models.TextField()),
                ('dotnet_runtime_dir', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Application',
            },
        ),
    ]
