# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-06-16 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_auto_20260508_0039'),
        ('unity_discovery', '0078_devicelogicalsystem_resource_pool'),
        ('inventory', '0162_auto_20260518_0458'),
        ('apm', '0050_apmonboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmonboarding',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgentConfig'),
        ),
        migrations.AddField(
            model_name='apmonboarding',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='apmonboarding',
            name='log_file_path',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='apmonboarding',
            name='project_dir',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='apmonboarding',
            name='runtime',
            field=models.ManyToManyField(blank=True, related_name='_apmonboarding_runtime_+', to='apm.APMOnboarding'),
        ),
        migrations.AddField(
            model_name='apmonboarding',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='apmonboarding_tags', to='inventory.Tag'),
        ),
    ]
