# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-06-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0051_auto_20260616_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Runtime',
                'verbose_name_plural': 'Runtimes',
            },
        ),
        migrations.RemoveField(
            model_name='apmonboarding',
            name='language',
        ),
        migrations.AlterField(
            model_name='apmonboarding',
            name='runtime',
            field=models.ManyToManyField(blank=True, related_name='apmonboarding_runtimes', to='apm.Runtime'),
        ),
    ]
