# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-06-16 12:07
from __future__ import unicode_literals

from django.db import migrations

def create_initial_runtimes(apps, schema_editor):
    Runtime = apps.get_model('apm', 'Runtime')
    runtimes = ['java', 'python', 'dotnet', 'cpp', 'php']
    for runtime in runtimes:
        Runtime.objects.get_or_create(name=runtime)

class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0052_auto_20260616_0506'),
    ]

    operations = [
        migrations.RunPython(create_initial_runtimes),
    ]
