# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-07-28 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0053_auto_20260616_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apmonboarding',
            name='dotnet_runtime_dir',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='apmonboarding',
            name='java_agent_dir',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='apmonboarding',
            name='java_tool_option',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
