# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4AddressableObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IPv6Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField()),
                ('prefixlen', models.IntegerField()),
                ('description', app.common.fields.NullableCharField(blank=True, max_length=256, null=True)),
                ('name', app.common.fields.NullableCharField(blank=True, max_length=128, null=True,
                                                             verbose_name='Allocation Name')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'ipv6_allocation',
                'verbose_name': 'ipv6 allocation',
                'permissions': (('view', 'Can view ipv6 allocation'),),
            },
        ),
        migrations.CreateModel(
            name='IPv6Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField()),
                ('prefixlen', models.IntegerField()),
                ('description', app.common.fields.NullableCharField(blank=True, max_length=256, null=True)),
                ('is_allow_64', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'ipv6_assignment',
                'verbose_name': 'ipv6 assignment',
                'permissions': (('view', 'Can view ipv6 assignment'),),
            },
        ),
        migrations.CreateModel(
            name='IPv6Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField()),
                ('prefixlen', models.IntegerField()),
                ('description', app.common.fields.NullableCharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'ipv6_interface',
                'verbose_name': 'ipv6 interface',
                'permissions': (('view', 'Can view ipv6 interface'),),
            },
        ),
        migrations.CreateModel(
            name='IPv6Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField()),
                ('prefixlen', models.IntegerField()),
                ('description', app.common.fields.NullableCharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Region Name')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'ipv6_region',
                'verbose_name': 'ipv6 region',
                'permissions': (('view', 'Can view ipv6 region'),),
            },
        ),
        migrations.CreateModel(
            name='IPv6Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField()),
                ('prefixlen', models.IntegerField()),
                ('description', app.common.fields.NullableCharField(blank=True, max_length=256, null=True)),
                ('purpose', models.IntegerField(choices=[(1, 'Internal'), (2, 'Customer')])),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'ipv6_tier',
                'verbose_name': 'ipv6 tier',
                'permissions': (('view', 'Can view ipv6 tier'),),
            },
        ),
        migrations.CreateModel(
            name='PrivateIPv4Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('address_int', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ipv4_address_private',
            },
        ),
        migrations.CreateModel(
            name='PrivateIPv4Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('prefix', models.GenericIPAddressField(protocol='IPv4')),
                ('prefixlen', models.IntegerField(verbose_name='Prefix Length')),
                ('version', models.IntegerField(default=4)),
                ('network_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_str', models.CharField(blank=True, max_length=32, null=True)),
                ('splittable', models.BooleanField(default=True)),
                ('aggregatable', models.BooleanField(default=False)),
                ('num_hosts_int', models.IntegerField(blank=True, null=True)),
                ('sibling_network_int', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('network_int',),
                'db_table': 'ipv4_allocatedblock_private',
                'verbose_name': 'Private IPv4 Assignment',
                'permissions': (('view', 'Can view private IPv4 Assignments'),),
            },
        ),
        migrations.CreateModel(
            name='PrivateIPv4PrimaryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('prefix', models.GenericIPAddressField(protocol='IPv4')),
                ('prefixlen', models.IntegerField(verbose_name='Prefix Length')),
                ('version', models.IntegerField(default=4)),
                ('network_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_str', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ('network_int',),
                'db_table': 'ipv4_primaryblock_private',
                'verbose_name': 'ipv4 primary block private',
                'permissions': (('view', 'Can view private ipv4 primaryblock'),),
            },
        ),
        migrations.CreateModel(
            name='PublicIPv4Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('address_int', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ipv4_address_public',
            },
        ),
        migrations.CreateModel(
            name='PublicIPv4Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('prefix', models.GenericIPAddressField(protocol='IPv4')),
                ('prefixlen', models.IntegerField(verbose_name='Prefix Length')),
                ('version', models.IntegerField(default=4)),
                ('network_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_str', models.CharField(blank=True, max_length=32, null=True)),
                ('splittable', models.BooleanField(default=True)),
                ('aggregatable', models.BooleanField(default=False)),
                ('num_hosts_int', models.IntegerField(blank=True, null=True)),
                ('sibling_network_int', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('network_int',),
                'db_table': 'ipv4_allocatedblock',
                'verbose_name': 'Public IPv4 Assignment',
                'permissions': (('view', 'Can view public IPv4 Assignments'),),
            },
        ),
        migrations.CreateModel(
            name='PublicIPv4PrimaryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('prefix', models.GenericIPAddressField(protocol='IPv4')),
                ('prefixlen', models.IntegerField(verbose_name='Prefix Length')),
                ('version', models.IntegerField(default=4)),
                ('network_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_int', models.BigIntegerField(blank=True, null=True)),
                ('subnet_mask_str', models.CharField(blank=True, max_length=32, null=True)),
                ('arin_handle', models.CharField(max_length=128, verbose_name='ARIN Handle')),
            ],
            options={
                'ordering': ('network_int',),
                'db_table': 'ipv4_primaryblock',
                'verbose_name': 'ipv4 primary block',
                'permissions': (('view', 'Can view ipv4 primaryblock'),),
            },
        ),
        migrations.CreateModel(
            name='IPv4Instance',
            fields=[
                ('ipv4addressableobject_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='ip.IPv4AddressableObject')),
            ],
            bases=('ip.ipv4addressableobject',),
        ),
        migrations.CreateModel(
            name='IPv4PDU',
            fields=[
                ('ipv4addressableobject_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='ip.IPv4AddressableObject')),
            ],
            bases=('ip.ipv4addressableobject',),
        ),
        migrations.CreateModel(
            name='IPv4Switch',
            fields=[
                ('ipv4addressableobject_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='ip.IPv4AddressableObject')),
            ],
            bases=('ip.ipv4addressableobject',),
        ),
        migrations.CreateModel(
            name='IPv4TerminalServer',
            fields=[
                ('ipv4addressableobject_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='ip.IPv4AddressableObject')),
            ],
            bases=('ip.ipv4addressableobject',),
        ),
        migrations.CreateModel(
            name='IPv4VirtualMachine',
            fields=[
                ('ipv4addressableobject_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='ip.IPv4AddressableObject')),
            ],
            bases=('ip.ipv4addressableobject',),
        ),
    ]
