# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0002_auto_20210416_0415'),
        ('common', '0001_initial'),
        ('ip', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicipv4assignment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='publicipv4assignment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.PublicIPv4PrimaryBlock'),
        ),
        migrations.AddField(
            model_name='publicipv4address',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='addresses', to='ip.PublicIPv4Assignment'),
        ),
        migrations.AddField(
            model_name='publicipv4address',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='common.AddressableModel'),
        ),
        migrations.AddField(
            model_name='privateipv4assignment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='privateipv4assignment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.PrivateIPv4PrimaryBlock'),
        ),
        migrations.AddField(
            model_name='privateipv4address',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='addresses', to='ip.PrivateIPv4Assignment'),
        ),
        migrations.AddField(
            model_name='privateipv4address',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='common.AddressableModel'),
        ),
        migrations.AddField(
            model_name='ipv6tier',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.IPv6Region'),
        ),
        migrations.AddField(
            model_name='ipv6region',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.IPv6Allocation',
                                    verbose_name='Parent Allocation'),
        ),
        migrations.AddField(
            model_name='ipv6interface',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces',
                                    to='ip.IPv6Assignment'),
        ),
        migrations.AddField(
            model_name='ipv6interface',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='ipv6assignment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ip.IPv6Allocation', verbose_name='Parent Allocation'),
        ),
        migrations.AddField(
            model_name='ipv6assignment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='ipv6assignment',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments',
                                    to='ip.IPv6Tier'),
        ),
        migrations.AddField(
            model_name='ipv4virtualmachine',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_ipv4_addresses',
                                    to='inventory.VirtualMachine'),
        ),
        migrations.AddField(
            model_name='ipv4terminalserver',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='terminal_server_ipv4_addresses', to='inventory.TerminalServer'),
        ),
        migrations.AddField(
            model_name='ipv4switch',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_ipv4_addresses',
                                    to='inventory.Switch'),
        ),
        migrations.AddField(
            model_name='ipv4pdu',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdu_ipv4_addresses',
                                    to='inventory.PDU'),
        ),
    ]
