# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('ip', '0002_auto_20210416_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipv4instance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_ipv4_addresses',
                                    to='server.Instance'),
        ),
    ]
