# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models


def update_device_platfrom_type(apps, schema_editor):
    MobileDevices = apps.get_model('inventory', 'MobileDevice')
    for device in MobileDevices.objects.filter(platform=None):
        device.platform = 'Android'
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210416_0415'),
    ]

    operations = [
        migrations.RenameField('mobiledevice', 'device_type', 'platform'),
        migrations.RunPython(update_device_platfrom_type),
        migrations.AlterField(
            model_name='mobiledevice',
            name='platform',
            field=models.CharField(choices=[('Android', 'Android'), ('ios', 'ios')], default='Android', max_length=128),
        ),
    ]
