# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210603_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='device_type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet')], default='Smartphone', max_length=128),
        ),
    ]
