# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-03 11:15
from __future__ import unicode_literals

from django.db import migrations, models

import logging
logger = logging.getLogger(__name__)


def update_device_model_name(apps, schema_editor):
    MobileDevices = apps.get_model('inventory', 'MobileDevice')
    MobileDeviceModels = apps.get_model('inventory', 'MobileDeviceModel')
    for device in MobileDevices.objects.all():
        if(device.model):
            device.model = MobileDeviceModels.objects.get(id=device.model).name
        else:
            device.model = 'abc'
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_mobiledevice_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledevice',
            name='model',
            field=models.CharField(blank=False, max_length=128, null=False),
        ),
        migrations.RunPython(update_device_model_name),
    ]
