# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0005_auto_20210603_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='device_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
