# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-14 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210607_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macdevice',
            name='asset_tag',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
