# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-06 12:58
from __future__ import unicode_literals

import app.common.fields
import app.common.func
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('CloudService', '0005_auto_20210608_0942'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0002_auto_20210416_0415'),
        ('inventory', '0006_auto_20210607_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.PositiveIntegerField()),
                ('db_instance_name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('MySQL', 'MySQL'),
                                                      ('MySQL Server', 'MySQL Server'),
                                                      ('Oracle', 'Oracle'),
                                                      ('PostgreSQL', 'PostgreSQL')],
                                             max_length=50)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('password', app.common.fields.EncryptedPasswordField()),
                ('connection_type', models.CharField(choices=[('AGENT', 'AGENT'), ('ODBC', 'ODBC')], default='AGENT', max_length=50)),
                ('data_source_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('private_cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudService.PrivateCloud')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
