# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_databaseserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='database_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
