# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0008_databaseserver_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseserver',
            name='connection_type',
            field=models.CharField(choices=[('Agent', 'AGENT'), ('ODBC', 'ODBC')], default='Agent', max_length=50),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='db_type',
            field=models.CharField(choices=[('MySQL', 'MySQL'), ('MSSQL Server', 'MSSQL Server'),
                                            ('Oracle', 'Oracle'), ('PostgreSQL', 'PostgreSQL')],
                                   max_length=50),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='private_cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CloudService.PrivateCloud'),
        ),
    ]
