# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


def update_server_type(apps, schema_editor):
    DatabaseServer = apps.get_model('inventory', 'databaseserver')
    for db in DatabaseServer.objects.filter(server_type=None):
        if db.content_type == 'bmserver':
            db.server_type = 'BMS'
        else:
            db.server_type = 'VMS'
        db.save()


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0009_auto_20210721_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='server_type',
            field=models.CharField(choices=[('BMS', 'Bare Metal Servers'), ('VMS', 'Virtual Machines')], max_length=255, null=True),
        ),
        migrations.RunPython(update_server_type),
        migrations.AlterField(
            model_name='databaseserver',
            name='server_type',
            field=models.CharField(choices=[('BMS', 'Bare Metal Servers'), ('VMS', 'Virtual Machines')], max_length=255),
        ),
    ]
