# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-28 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210713_2127'),
        ('inventory', '0010_databaseserver_server_type'),
    ]

    operations = [
    ]
