# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 16:44
from __future__ import unicode_literals

from django.db import migrations, models


def update_mac_status(apps, schema_editor):
    MacDevice = apps.get_model('inventory', 'MacDevice')
    for mac in MacDevice.objects.all():
        mac.status = 'NA'
        mac.save()


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0011_merge_20210727_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseserver',
            name='connection_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('ODBC', 'ODBC')], default='Agent', max_length=50),
        ),
        migrations.RunPython(update_mac_status)
    ]
