# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_merge_20210727_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseserver',
            name='connection_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('ODBC', 'ODBC')], default='Agent', max_length=50),
        ),
    ]
