# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210812_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmserver',
            name='asset_tag',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bmserver',
            name='status',
            field=models.CharField(
                choices=[
                    (b'AVAILABLE', b'AVAILABLE'),
                    (b'IN_SERVICE', b'IN_SERVICE'),
                    (b'REPAIR/RMA', b'REPAIR/RMA'),
                    (b'UNKNOWN', b'UNKNOWN')
                ],
                default=b'AVAILABLE',
                max_length=255, null=True
            ),
        ),
    ]
