# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0012_auto_20210817_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customdevice',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='disk',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='san',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True)
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='terminalserver',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='virtualloadbalancer',
            name='status',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'UP', b'UP'), (b'DOWN', b'DOWN')], default=b'NA', max_length=16, null=True),
        ),
    ]
