# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-19 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210817_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='annual_escalation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
