# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-26 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210825_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmserver',
            name='asset_tag',
        ),
        migrations.RemoveField(
            model_name='bmserver',
            name='status',
        ),
    ]
