# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210819_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='snmp_version',
            field=models.CharField(choices=[(b'v1', b'v1'), (b'v2C', b'v2C'), (b'v3', b'v3')], default=b'v2c', max_length=16),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='snmp_version',
            field=models.CharField(choices=[(b'v1', b'v1'), (b'v2C', b'v2C'), (b'v3', b'v3')], default=b'v2c', max_length=16),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='snmp_version',
            field=models.CharField(choices=[(b'v1', b'v1'), (b'v2C', b'v2C'), (b'v3', b'v3')], default=b'v2c', max_length=16),
        ),
        migrations.AlterField(
            model_name='server',
            name='snmp_version',
            field=models.CharField(choices=[(b'v1', b'v1'), (b'v2C', b'v2C'), (b'v3', b'v3')], default=b'v2c', max_length=16),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='snmp_version',
            field=models.CharField(choices=[(b'v1', b'v1'), (b'v2C', b'v2C'), (b'v3', b'v3')], default=b'v2c', max_length=16),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_version',
            field=models.CharField(choices=[(b'v1', b'v1'), (b'v2C', b'v2C'), (b'v3', b'v3')], default=b'v2c', max_length=16),
        ),
    ]
