# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmserver',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='firewalls', to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='load_balancers', to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mac_devices', to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='switch',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='switches', to='inventory.Tag'),
        ),
    ]
