# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-26 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210826_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmserver',
            name='tags',
        ),
    ]
