# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_bmserver_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmserver',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.Tag'),
        ),
    ]
