# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-31 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210817_0953'),
        ('inventory', '0018_bmserver_tags'),
    ]

    operations = [
    ]
