# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-31 10:53
from __future__ import unicode_literals

import app.Utils.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_merge_20210831_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=app.Utils.utility.generate_uuid),
        ),
    ]
