# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-31 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_tag_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='uuid',
        ),
    ]
