# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-06 08:32
from __future__ import unicode_literals

import app.Utils.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_tag_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmserver',
            name='tags',
        ),
        migrations.AddField(
            model_name='server',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='servers', to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=app.Utils.utility.generate_uuid),
        ),
    ]
