# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210906_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='firewall_tags', to='inventory.Tag'),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='loadbalancer_tags', to='inventory.Tag'),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='macdevice_tags', to='inventory.Tag'),
        ),
        migrations.AlterField(
            model_name='server',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='server_tags', to='inventory.Tag'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='switch_tags', to='inventory.Tag'),
        ),
    ]
