# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-17 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210907_0415'),
        ('inventory', '0015_auto_20210912_2223'),
    ]

    operations = [
    ]
