# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_merge_20210917_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchportmap',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
