# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-11-03 03:25
from __future__ import unicode_literals

import app.common.func
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def fill_db_type(apps, schema_editor):
    DatabaseType = apps.get_model('inventory', 'DatabaseType')
    for t in ('MySQL', 'MSSQL Server', 'Oracle', 'PostgreSQL'):
        DatabaseType.objects.create(name=t)


def update_dbserver_dbtype(apps, schema_editor):
    DatabaseType = apps.get_model('inventory', 'DatabaseType')
    DbServers = apps.get_model('inventory', 'DatabaseServer')
    for db in DbServers.objects.all():
        db.db_type = DatabaseType.objects.get(name=db.db_type).id
        db.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_merge_20210917_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(fill_db_type),
        migrations.RunPython(update_dbserver_dbtype),
        migrations.AlterField(
            model_name='databaseserver',
            name='db_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.DatabaseType'),
        ),
    ]
