# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-10-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_merge_20210917_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseserver',
            name='connection_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('ODBC', 'ODBC')], max_length=50, null=True),
        ),
    ]
