# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-11-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20211029_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('SNMP', 'SNMP'), ('Agent', 'Agent')], max_length=50, null=True),
        ),
    ]
