# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-11-10 09:08
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_switch_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseserver',
            name='password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
    ]
