# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-11-12 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20211110_0108'),
        ('inventory', '0025_auto_20211102_2025'),
    ]

    operations = [
    ]
