# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-02 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_merge_20211125_2213'),
        ('inventory', '0029_auto_20211117_1051'),
    ]

    operations = [
    ]
