# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-16 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_merge_20211202_0528'),
        ('inventory', '0025_switchportmap_name'),
    ]

    operations = [
    ]
