# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_merge_20211216_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('SNMP', 'SNMP'), ('Agent', 'Agent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('SNMP', 'SNMP'), ('Agent', 'Agent')], max_length=50, null=True),
        ),
    ]
