# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-02-14 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_server_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent')], max_length=50, null=True),
        ),
    ]
