# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-02-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_pdu_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdu',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('SNMP', 'SNMP')], max_length=50, null=True),
        ),
    ]
