# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-02-25 11:30
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_auto_20220218_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA', b'SHA')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='snmp_authlevel',
            field=models.CharField(
                blank=True, choices=[(b'NoAuthNoPriv', b'NoAuthNoPriv'), (b'AuthNoPriv', b'AuthNoPriv'), (b'AuthPriv', b'AuthPriv')],
                max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name='pdu',
            name='snmp_authname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='snmp_authpass',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'AES', b'AES'), (b'DES', b'DES')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='snmp_cryptopass',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='snmp_version',
            field=models.CharField(choices=[(b'v1', b'v1'), (b'v2c', b'v2c'), (b'v3', b'v3')], default=b'v2c', max_length=16),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
