# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-04 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20220225_0330'),
        ('inventory', '0034_storagedevice_connection_type'),
    ]

    operations = [
    ]
