# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_merge_20220304_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='platform_type',
            field=models.CharField(
                blank=True,
                choices=[('ESXi', 'ESXi'), ('Hypervisor', 'Hypervisor'), ('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Nimble', 'Nimble'), ('Windows', 'Windows')],
                max_length=50,
                null=True
            ),
        ),
    ]
