# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_merge_20220304_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='virtualmachine_tags', to='inventory.Tag'),
        ),
    ]
