# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-23 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20220321_0334'),
        ('inventory', '0038_virtualmachine_tags'),
    ]

    operations = [
    ]
