# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_merge_20220323_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='m_co2_emission_vlaue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='m_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
