# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-28 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20220328_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdu',
            old_name='m_co2_emission_vlaue',
            new_name='m_co2_emission_value',
        ),
    ]
