# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-03-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_auto_20220328_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdu',
            name='m_co2_emission_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
