# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-04-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_auto_20220328_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='macdevice',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent')], max_length=50, null=True),
        ),
    ]
