# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-05-04 12:04
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_macdevice_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='connection_type',
            field=models.CharField(
                blank=True,
                choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent')],
                max_length=50,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_authalgo',
            field=models.CharField(
                blank=True,
                choices=[(b'MD5', b'MD5'), (b'SHA', b'SHA')],
                max_length=16,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_authlevel',
            field=models.CharField(
                blank=True,
                choices=[
                    (b'NoAuthNoPriv', b'NoAuthNoPriv'),
                    (b'AuthNoPriv', b'AuthNoPriv'),
                    (b'AuthPriv', b'AuthPriv')
                ],
                max_length=32,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_authname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_authpass',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_community',
            field=models.CharField(
                default=b'public',
                max_length=128,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_cryptoalgo',
            field=models.CharField(
                blank=True,
                choices=[(b'AES', b'AES'), (b'DES', b'DES')],
                max_length=16,
                null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_cryptopass',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snmp_version',
            field=models.CharField(
                choices=[(b'v1', b'v1'), (b'v2c', b'v2c'), (b'v3', b'v3')],
                default=b'v2c',
                max_length=16
            ),
        ),
    ]
