# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-05-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_macdevice_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallmodel',
            name='power_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loadbalancermodel',
            name='power_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mobiledevicemodel',
            name='power_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pdumodel',
            name='power_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='servermodel',
            name='power_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='power_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='power_consumption',
            field=models.IntegerField(null=True),
        ),
    ]
