# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-04-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_macdevice_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mobiledevice_tags', to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='storagedevice_tags', to='inventory.Tag'),
        ),
    ]
