# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-05-26 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_auto_20220428_0220'),
        ('inventory', '0044_auto_20220504_0504'),
    ]

    operations = [
    ]
