# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-05-26 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_merge_20220526_0043'),
        ('inventory', '0045_merge_20220520_0405'),
    ]

    operations = [
    ]
