# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-10-13 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_merge_20220526_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BareMetal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inventory.server',),
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inventory.server',),
        ),
    ]
