# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-14 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_baremetal_hypervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='alerts_notification_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firewall',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
