# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_baremetal_hypervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customdevice_tags', to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='databaseserver_tags', to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='pdu',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pdu_tags', to='inventory.Tag'),
        ),
    ]
