# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_auto_20221114_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewall',
            name='alerts_notification_disabled',
        ),
        migrations.AddField(
            model_name='firewall',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
