# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-16 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_auto_20221102_0531'),
        ('inventory', '0049_auto_20221114_2312'),
    ]

    operations = [
    ]
