# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-21 06:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_merge_20221116_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='pdu',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='server',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='switch',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
