# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-12-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudService', '0008_ocipublicclouddata'),
        ('inventory', '0051_auto_20221120_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmserver',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='firewall',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='firewalls',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='load_balancers',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mac_devices',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='server',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='servers',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='storage_devices',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AddField(
            model_name='switch',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='switches',
                to='CloudService.ColoCloud'
            ),
        ),
    ]
