# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-12-23 12:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20221114_0130'),
        ('inventory', '0051_auto_20221120_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborInformation',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('source_pk', models.IntegerField()),
                ('target_pk', models.IntegerField()),
                (
                    'target_info',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        null=True
                    )
                ),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='organization.Organization'
                )),
            ],
        ),
    ]
