# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-12-30 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_neighborinformation'),
        ('inventory', '0052_auto_20221206_0233'),
    ]

    operations = [
    ]
