# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-10 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_neighborinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborinformation',
            name='source_pk',
        ),
        migrations.RemoveField(
            model_name='neighborinformation',
            name='target_pk',
        ),
        migrations.AddField(
            model_name='neighborinformation',
            name='source_uuid',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='neighborinformation',
            name='target_uuid',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
