# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_neighborinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='IPsec_tunnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firewall',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='fan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='number_of_ports',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='os_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='os_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='power_socket1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='power_socket2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='power_supply1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='firewall_power_supply1',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='firewall',
            name='power_supply2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='firewall_power_supply2',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='firewall',
            name='version_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='IPsec_tunnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='fan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='number_of_ports',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='os_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='os_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='power_socket1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='power_socket2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='power_supply1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='loadbalancer_power_supply1',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='power_supply2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='loadbalancer_power_supply2',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='version_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='IPsec_tunnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='fan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='number_of_ports',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='os_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='os_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='power_socket1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='power_socket2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='power_supply1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='switch_power_supply1',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='switch',
            name='power_supply2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='switch_power_supply2',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='switch',
            name='version_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
