# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_merge_20221229_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmserver',
            name='datacenter',
        ),
        migrations.RemoveField(
            model_name='databaseserver',
            name='datacenter',
        ),
        migrations.AlterField(
            model_name='firewall',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='firewalls', to='CloudService.ColoCloud'
            ),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='load_balancers',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='mac_devices',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AlterField(
            model_name='server',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='servers',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='storage_devices',
                to='CloudService.ColoCloud'
            ),
        ),
        migrations.AlterField(
            model_name='switch',
            name='datacenter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='switches',
                to='CloudService.ColoCloud'
            ),
        ),
    ]
