# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-12 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_auto_20230110_0810'),
        ('inventory', '0053_auto_20230110_0309'),
    ]

    operations = [
    ]
