# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_merge_20230111_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='platform_type',
            field=models.CharField(
                choices=[
                    ('ESXi', 'ESXi'),
                    ('Hypervisor', 'Hypervisor'),
                    ('Linux', 'Linux'),
                    ('MacOS', 'MacOS'),
                    ('Nimble', 'Nimble'),
                    ('Windows', 'Windows')
                ],
                max_length=50
            ),
        ),
    ]
