# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-25 09:52
from __future__ import unicode_literals

import app.common.func
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_manufacturer(apps, schema_editor):
    PDUManufacturer = apps.get_model('inventory', 'PDUManufacturer')
    try:
        m = PDUManufacturer.objects.get(name='APC')
    except:
        m = PDUManufacturer(name='APC')
        m.save()
    return m.id


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_merge_20230111_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDUManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.common.func.generate_uuid)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'PDU Manufacturer',
                'permissions': (('view', 'Can view pdu manufacturer'),),
            },
        ),
        migrations.AlterModelOptions(
            name='pdu',
            options={'permissions': (('view', 'Can view pdu'),), 'verbose_name': 'PDU'},
        ),
        migrations.RenameField(
            model_name='pdu',
            old_name='pdu_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='pdu',
            old_name='hostname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pdu',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.PDUManufacturer'),
        ),
        migrations.AddField(
            model_name='pdumodel',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.PDUManufacturer'),
        ),
        migrations.RunPython(create_manufacturer),
    ]
