# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-31 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_auto_20230120_0431'),
        ('inventory', '0056_auto_20230125_0152'),
    ]

    operations = [
    ]
