# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-01 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_auto_20230110_0921'),
        ('inventory', '0057_merge_20230131_0254'),
    ]

    operations = [
    ]
