# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_merge_20230201_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewall',
            name='IPsec_tunnel',
        ),
        migrations.RemoveField(
            model_name='loadbalancer',
            name='IPsec_tunnel',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='IPsec_tunnel',
        ),
        migrations.AddField(
            model_name='firewall',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='number_of_ports',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='os_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='os_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='fan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='hypervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='logical_cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='out_of_band_management_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='out_of_band_management_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='pdu1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='server_power_supply1',
                to='inventory.PDU'),
        ),
        migrations.AddField(
            model_name='server',
            name='pdu2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='server_power_supply2',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='server',
            name='power_socket1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='power_socket2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='fan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='logical_cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='pdu1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='storagedevice_power_supply1',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='pdu2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='storagedevice_power_supply2',
                to='inventory.PDU'
            ),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='power_socket1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='power_socket2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='service_pack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='storage_capacity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='storage_used',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
