# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_auto_20230201_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
