# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-02 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_auto_20230202_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
