# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_auto_20230209_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='snmp_community',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
