# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-31 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudService', '0008_ocipublicclouddata'),
        ('inventory', '0063_auto_20230310_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevice',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CloudService.ColoCloud'),
        ),
    ]
