# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20230314_1145'),
        ('inventory', '0064_auto_20230331_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='organization.Organization'
            ),
        ),
    ]
