# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-11 12:22
from __future__ import unicode_literals

from django.db import migrations
from rest.customer.utils import GlobalSearchQuerysets
from rest.customer.tags_migration import TagsMigrqationQuerysets
from app.organization.models import Organization
from app.inventory.models import Tag


def update_tag_customer(apps, schema_editor):
    for org in Organization.objects.all():
        tags = set()
        devices_qs = TagsMigrqationQuerysets(customer=org)
        qs = devices_qs.get_queryset_chain
        for device in qs:
            if device._meta.model.__name__ == 'BMServer':
                continue
            for tag_id in device.tags.all().values_list('id', flat=True):
                tags.add(tag_id)

        for tag in tags:
            cust_tag = Tag.objects.get(id=tag)
            cust_tag.customer = org
            cust_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_auto_20230410_1004'),
    ]

    operations = [
        migrations.RunPython(update_tag_customer),
    ]
