# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-14 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20230314_1145'),
        ('inventory', '0066_auto_20230411_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('tag_name', 'customer')]),
        ),
    ]
