# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-05-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_auto_20230414_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200, null=True)),
                ('os_distribution', models.CharField(max_length=128)),
                ('os_version', models.CharField(blank=True, max_length=20, null=True)),
                ('hardware', models.CharField(blank=True, max_length=128, null=True)),
                ('zabbix_version', models.CharField(blank=True, max_length=20, null=True)),
                ('encryption', models.CharField(blank=True, max_length=128, null=True)),
                ('packaging', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
