# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-05-23 15:05
from __future__ import unicode_literals

from django.db import migrations

def update_neighbor_model(apps, schema_editor):
    PDUSocketMappings = apps.get_model('inventory', 'PDUSocketMappings')
    # NeighborInformation = apps.get_model('inventory', 'NeighborInformation')
    for pdu in PDUSocketMappings.objects.all():
        #calling save will save the date in NeighborInformation also
        pdu.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_auto_20230414_0610'),
    ]

    operations = [
        migrations.RunPython(update_neighbor_model)
    ]
