# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-05-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_auto_20230414_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='macdevice',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
