# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-05-25 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20230523_0805'),
        ('inventory', '0068_agentmap'),
    ]

    operations = [
    ]
