# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-05-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20230517_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='discovery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='dns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='first_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='hypervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualmachine_hypervisor', to='inventory.Hypervisor'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='last_rebooted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='service_pack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='snapshot_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='storage',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='vcpu_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
