# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_merge_20230525_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='macdevice',
            name='pdu1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macdevice_power_supply1', to='inventory.PDU'),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='pdu2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macdevice_power_supply2', to='inventory.PDU'),
        ),
    ]
