# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-14 12:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_auto_20230605_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
