# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-11 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20230314_1145'),
        ('inventory', '0070_auto_20230605_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='virtualmachine',
            unique_together=set([('name', 'customer')]),
        ),
    ]
