# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-20 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_auto_20230517_0306'),
        ('inventory', '0071_auto_20230714_0535'),
    ]

    operations = [
    ]
