# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-27 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_auto_20230711_0050'),
        ('inventory', '0072_merge_20230720_0500'),
    ]

    operations = [
    ]
