# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_merge_20230727_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallmodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancermodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobiledevicemodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdumodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
