# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-07-31 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_auto_20230727_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
