# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-08-09 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_auto_20230731_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
