# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-09-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_auto_20230809_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='host_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='is_cluster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
