# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_auto_20230914_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='platform_type',
            field=models.CharField(choices=[('ESXi', 'ESXi'), ('Hypervisor', 'Hypervisor'), ('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Nimble', 'Nimble'), ('Windows', 'Windows'), ('NetApp', 'NetApp')], max_length=50),
        ),
    ]
