# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-22 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_auto_20231012_0051'),
        ('inventory', '0078_auto_20231010_0011'),
    ]

    operations = [
    ]
