# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-11-29 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agentconfig_enable_vcenter'),
        ('inventory', '0080_auto_20231122_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='agent.AgentConfig'),
        ),
        migrations.AddField(
            model_name='pdu',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgentConfig'),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_devices', to='agent.AgentConfig'),
        ),
        migrations.AddField(
            model_name='switch',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='agent.AgentConfig'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgentConfig'),
        ),
    ]
