# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-11-29 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agentconfig_enable_vcenter'),
        ('inventory', '0081_auto_20231128_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='agent.AgentConfig'),
        ),
    ]
