# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-12-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agentconfig_enable_vcenter'),
        ('inventory', '0084_macdevice_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgentConfig'),
        ),
    ]
