# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-12-11 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0085_mobiledevice_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewalls', to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_balancers', to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_devices', to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='server',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_devices', to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.AgentConfig'),
        ),
    ]
