# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-12-29 10:49
from __future__ import unicode_literals

import app.Utils.utility
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0086_auto_20231211_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('url_availabilty', models.BooleanField(default=True)),
                ('login_availability', models.BooleanField(default=False)),
                ('response_availability', models.BooleanField(default=False)),
                ('string_availabilty', models.BooleanField(default=False)),
                ('login_username', models.CharField(max_length=128, null=True)),
                ('login_password', models.CharField(max_length=128, null=True)),
                ('response_status', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('string_pattern', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customdevice',
            name='is_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.CustomDevice'),
        ),
    ]
