# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-01-04 06:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0087_auto_20231229_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevice',
            name='alerts_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customdevice',
            name='notify_alerts_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
