# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-01-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_auto_20231206_0202'),
        ('inventory', '0088_auto_20240103_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevice',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.AgentConfig'),
        ),
    ]
