# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-01-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0089_customdevice_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdevice',
            name='addressablemodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='customdevice', serialize=False, to='common.AddressableModel'),
        ),
        migrations.AlterField(
            model_name='customdevice',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customdevice', to='datacenter.Cabinet'),
        ),
        migrations.AlterField(
            model_name='customdevice',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customdevice', to='agent.AgentConfig'),
        ),
        migrations.AlterField(
            model_name='customdevice',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customdevice', to='CloudService.ColoCloud'),
        ),
        migrations.AlterField(
            model_name='customdevice',
            name='observium_host',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customdevice', to='monitoring.ObserviumHost'),
        ),
    ]
