# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-01-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_auto_20240109_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevice',
            name='polling_interval_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customdevice',
            name='polling_interval_sec',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
