# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-01-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_auto_20240111_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='response_status',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
