# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-02-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0092_auto_20240113_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='connection_string',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='service_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='driver',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
