# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-03-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_auto_20240226_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
