# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-03-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0094_virtualmachine_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='cpu_speed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
