# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-04-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0095_auto_20240325_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='first_discovered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='last_discovered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
