# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-04-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0096_auto_20240408_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='fqdn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='os_build_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='server_type',
            field=models.CharField(default=b'Virtual', max_length=50),
        ),
    ]
