# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-05-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0097_auto_20240409_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='snmp_authlevel',
            field=models.CharField(blank=True, choices=[(b'noAuthNoPriv', b'noAuthNoPriv'), (b'authNoPriv', b'authNoPriv'), (b'authPriv', b'authPriv')], max_length=32, null=True),
        ),
    ]
