# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-06-10 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_auto_20240602_2018'),
        ('inventory', '0099_virtualmachine_interfaces'),
    ]

    operations = [
    ]
