# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-07-04 08:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_auto_20240502_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
