# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0099_merge_20240610_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('interface_index', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('device_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interfaces', to='contenttypes.ContentType')),
            ],
        ),
    ]
