# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0099_merge_20240610_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
