# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_auto_20240813_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu_speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
