# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-19 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_auto_20240813_1046'),
        ('inventory', '0100_interface'),
    ]

    operations = [
    ]
