# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_auto_20240813_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
