# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_merge_20240819_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='uuid',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
