# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-29 10:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_auto_20240821_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='interfaces',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
