# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-09-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0103_pdu_interfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API')], max_length=50, null=True),
        ),
    ]
