# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-19 13:17
from __future__ import unicode_literals

import app.Utils.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0104_auto_20240819_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='uuid',
            field=models.UUIDField(blank=True, default=app.Utils.utility.generate_uuid, null=True, verbose_name='UUID'),
        ),
    ]
