# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-09-26 15:06
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity_discovery', '0042_deviceinterfaceremotedata_networkdevicebgppeerdata'),
        ('inventory', '0104_auto_20240913_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='device_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='enable_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='device_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_balancers', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='enable_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='device_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='switch',
            name='enable_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
    ]
