# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-09-19 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0103_pdu_interfaces'),
        ('inventory', '0105_auto_20240819_0617'),
    ]

    operations = [
    ]
