# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-10-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0105_auto_20240926_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
