# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-10-16 05:54
from __future__ import unicode_literals

import app.Utils.utility
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20240107_0332'),
        ('inventory', '0106_auto_20241007_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('device_status_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('device_manufacturer_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('device_models_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('device_type_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
