# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-10-25 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity_discovery', '0042_deviceinterfaceremotedata_networkdevicebgppeerdata'),
        ('inventory', '0107_infrastructuredata'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='server',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
