# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-10-29 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_infrastructuredata'),
        ('inventory', '0106_merge_20240919_0336'),
    ]

    operations = [
    ]
