# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-22 06:04
from __future__ import unicode_literals

import app.Utils.utility
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_auto_20241025_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypervisorFirewalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('key', models.TextField(blank=True, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('allowed_ip_addresses', models.TextField(blank=True, null=True)),
                ('rule', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HypervisorPhysicalAdapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('key', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('configured_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('wake_on_LAN_supported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HypervisorStorageAdapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('key', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('targets', models.IntegerField(default=0)),
                ('devices', models.IntegerField(default=0)),
                ('paths', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HypervisorStorageDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('key', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('capacity', models.BigIntegerField(default=0)),
                ('operational_state', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HypervisorVirtualSwitches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('key', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_adapter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('portgroup', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='HypervisorVMkernelAdapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('key', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('network_label', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_usage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='server',
            name='memory_usage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='server',
            name='storage_usage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
