# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-12 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_merge_20241029_0414'),
        ('inventory', '0108_auto_20241025_0451'),
    ]

    operations = [
    ]
