# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-22 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0109_auto_20241121_2204'),
        ('vmware', '0013_auto_20241121_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='vmware_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_hosts', to='vmware.VmwareVcenterCluster'),
        ),
        migrations.AlterField(
            model_name='server',
            name='private_cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='CloudService.PrivateCloud'),
        ),
        migrations.AddField(
            model_name='hypervisorvmkerneladapters',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Server'),
        ),
        migrations.AddField(
            model_name='hypervisorvmkerneladapters',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.HypervisorVirtualSwitches'),
        ),
        migrations.AddField(
            model_name='hypervisorvirtualswitches',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Server'),
        ),
        migrations.AddField(
            model_name='hypervisorstoragedevices',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Server'),
        ),
        migrations.AddField(
            model_name='hypervisorstorageadapters',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Server'),
        ),
        migrations.AddField(
            model_name='hypervisorphysicaladapters',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Server'),
        ),
        migrations.AddField(
            model_name='hypervisorphysicaladapters',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.HypervisorVirtualSwitches'),
        ),
        migrations.AddField(
            model_name='hypervisorfirewalls',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Server'),
        ),
    ]
