# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-11-22 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0109_merge_20241112_0535'),
        ('inventory', '0110_auto_20241121_2204'),
    ]

    operations = [
    ]
