# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-12-09 13:52
from __future__ import unicode_literals

import app.Utils.utility
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20240107_0332'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0111_merge_20241122_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=128, null=True)),
                ('value_type', models.CharField(blank=True, choices=[('Boolean', 'Boolean'), ('Char', 'Char'), ('Choice', 'Choice'), ('Integer', 'Integer')], max_length=128, null=True)),
                ('choice_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, null=True, size=None)),
                ('default_value', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_attribute_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_attribute_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customdevice',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
