# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-01-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0112_auto_20241209_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='is_root_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='is_root_device',
            field=models.BooleanField(default=False),
        ),
    ]
