# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-01-10 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0112_auto_20241209_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='is_purity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='purity_api_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='purity_api_version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
