# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-01-29 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0113_auto_20250115_0304'),
        ('inventory', '0113_auto_20250110_0613'),
    ]

    operations = [
    ]
