# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-01-31 13:02
from __future__ import unicode_literals

from django.db import migrations, models
from django.db import migrations, connection


def drop_unique_constraint(apps, schema_editor):
    with connection.cursor() as cursor:
        indexes = {
            "inventory_memory": "memory_serial_number_idx",
            "inventory_server": "inventory_server_serial_number_uniq",
            "inventory_switch": "switch_sno_uniq",
        }

        for table, index in indexes.items():
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = '{}' AND indexname = '{}';
            """.format(table, index))
            if cursor.fetchone():  # If index exists, drop it
                cursor.execute("DROP INDEX {};".format(index))




class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0113_auto_20250110_0613'),
    ]

    operations = [
        migrations.RunPython(drop_unique_constraint),
        migrations.AlterField(
            model_name='memory',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='san',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customdevice',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='terminalserver',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='virtualloadbalancer',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        )
    ]
