# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-02-20 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0114_auto_20250202_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='snmp_authalgo',
            field=models.CharField(blank=True, choices=[(b'MD5', b'MD5'), (b'SHA1', b'SHA1'), (b'SHA224', b'SHA224'), (b'SHA256', b'SHA256'), (b'SHA384', b'SHA384'), (b'SHA512', b'SHA512')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='snmp_cryptoalgo',
            field=models.CharField(blank=True, choices=[(b'DES', b'DES'), (b'AES128', b'AES128'), (b'AES192', b'AES192'), (b'AES256', b'AES256'), (b'AES192C', b'AES192C'), (b'AES256C', b'AES256C')], max_length=16, null=True),
        ),
    ]
