# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-02-07 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0114_merge_20250129_0134'),
        ('inventory', '0114_auto_20250202_2231'),
    ]

    operations = [
    ]
