# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-02-21 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0115_auto_20250219_2350'),
        ('inventory', '0115_merge_20250206_2207'),
    ]

    operations = [
    ]
