# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-02-21 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0116_merge_20250220_2319'),
        ('inventory', '0116_merge_20250220_2226'),
    ]

    operations = [
    ]
