# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-03 17:07
from __future__ import unicode_literals

import app.Utils.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20240107_0332'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0117_merge_20250221_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigurationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid, editable=False, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=128, null=True)),
                ('device_id', models.PositiveIntegerField(blank=True, null=True)),
                ('config_file', models.CharField(blank=True, max_length=128, null=True)),
                ('is_startup_config', models.BooleanField(default=False)),
                ('is_golden_config', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevicesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='firewall',
            old_name='enable_password',
            new_name='enable_mode_password',
        ),
        migrations.RenameField(
            model_name='loadbalancer',
            old_name='enable_password',
            new_name='enable_mode_password',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='enable_password',
            new_name='enable_mode_password',
        ),
        migrations.AddField(
            model_name='firewall',
            name='config_device_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='is_ncm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='config_device_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='is_ncm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='config_device_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='is_ncm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='device_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewalls', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='device_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_balancers', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='device_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='networkdevicesgroup',
            name='firewalls',
            field=models.ManyToManyField(blank=True, to='inventory.Firewall'),
        ),
        migrations.AddField(
            model_name='networkdevicesgroup',
            name='load_balancers',
            field=models.ManyToManyField(blank=True, to='inventory.LoadBalancer'),
        ),
        migrations.AddField(
            model_name='networkdevicesgroup',
            name='switches',
            field=models.ManyToManyField(blank=True, to='inventory.Switch'),
        ),
    ]
