# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-07 06:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0118_auto_20250303_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
