# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0119_databaseserver_custom_attribute_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfigurationdata',
            name='config_file',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
