# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0120_auto_20250310_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='system_object_oid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='system_object_oid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='system_object_oid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='system_object_oid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='system_object_oid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='system_object_oid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='system_object_oid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
