# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models

from integ.monitoring.utils import get_model_obj


def add_config_file_types(apps, schema_editor):
    DEVICE_FILE_TYPE_MAP = {
        'cisco_ios': 'cfg',
        'cisco_ftd': 'encrypted package',
        'cisco_nxos': 'cfg',
        'f5_ltm': 'ucs',
        'fortinet': 'conf',
        'paloalto_panos': 'tgz'
    }
    DeviceConfigurationData = apps.get_model('inventory', 'DeviceConfigurationData')
    for data in DeviceConfigurationData.objects.all():
        device_model = get_model_obj(data.device_type)
        device_obj = device_model.objects.get(id=data.device_id)
        if device_obj.config_device_type:
            config_device_type = device_obj.config_device_type
            file_type = DEVICE_FILE_TYPE_MAP.get(config_device_type, None)
            device_obj.config_file_type = file_type
            device_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0121_auto_20250313_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='config_file_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='config_file_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='config_file_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(add_config_file_types)
    ]
