# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0122_auto_20250318_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_index',
            field=models.PositiveIntegerField(),
        ),
    ]
