# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0122_auto_20250318_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallmodel',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancermodel',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobiledevicemodel',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdumodel',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermodel',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='end_of_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
