# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0124_auto_20250321_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='os_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
