# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-24 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0125_virtualmachine_os_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='platform_type',
            field=models.CharField(choices=[('ESXi', 'ESXi'), ('Hypervisor', 'Hypervisor'), ('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Nimble', 'Nimble'), ('Windows', 'Windows'), ('NetApp', 'NetApp'), ('NX-OS', 'NX-OS'), ('IOS-XE', 'IOS-XE'), ('TMOS (F5)', 'TMOS (F5)'), ('FTD (Firepower Threat Defense)', 'FTD (Firepower Threat Defense)'), ('Firepower', 'Firepower'), ('PAN-OS', 'PAN-OS'), ('Embedded Linux', 'Embedded Linux'), ('FortiOS', 'FortiOS')], max_length=50),
        ),
    ]
