# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-25 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0127_auto_20250324_2243'),
        ('inventory', '0123_auto_20250321_0518'),
    ]

    operations = [
    ]
