# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models

def update_domain_fields(apps, schema_editor):
    model_names = [
        'Switch',
        'MacDevice',
        'StorageDevice',
        'DatabaseServer',
        'MobileDevice',
        'Server',
        'Firewall',
        'CustomDevice',
        'LoadBalancer',
        'PDU',
        'BMServer',
        'VirtualMachine'
    ]

    def extract_domain(fqdn):
        """Extracts the domain from a fully qualified domain name (FQDN)."""
        if fqdn:
            parts = fqdn.split('.')
            if len(parts) > 1:
                return '.'.join(parts[-2:])
        return None

    for model_name in model_names:
        Model = apps.get_model('inventory', model_name)  # Get model dynamically
        for instance in Model.objects.all():
            fqdn = getattr(instance, 'name', None)# or getattr(instance, 'dns_name', None)
            if fqdn:
                if not extract_domain(fqdn):
                    fqdn = getattr(instance, 'dns_name', None)
                    if fqdn:
                        instance.domain = extract_domain(fqdn)
                        instance.save(update_fields=['domain'])
                else:
                    instance.domain = extract_domain(fqdn)
                    instance.save(update_fields=['domain'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0128_auto_20250326_0023'),
    ]

    operations = [
        migrations.RunPython(update_domain_fields),
    ]
