# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-03-27 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0129_auto_20250326_0023'),
        ('inventory', '0128_merge_20250325_0549'),
    ]

    operations = [
    ]
