# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-04-16 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_add_connections_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0130_merge_20250327_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevicesgroup',
            name='email_notify_groups',
            field=models.ManyToManyField(blank=True, to='rbac.RBACUserGroup'),
        ),
        migrations.AddField(
            model_name='networkdevicesgroup',
            name='email_notify_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkdevicesgroup',
            name='sync_failure_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkdevicesgroup',
            name='sync_success_notify',
            field=models.BooleanField(default=False),
        ),
    ]
