# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-04-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0131_auto_20250416_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='os_architecture',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
