# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-04-28 05:53
from __future__ import unicode_literals

import app.common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0132_operatingsystem_os_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfigurationdata',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceconfigurationdata',
            name='file_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='default_encryption_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='default_encryption_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='default_encryption_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
    ]
