# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-05-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity_discovery', '0056_auto_20250415_0736'),
        ('inventory', '0133_auto_20250427_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewall',
            old_name='device_credentials',
            new_name='credentials',
        ),
        migrations.RenameField(
            model_name='loadbalancer',
            old_name='device_credentials',
            new_name='credentials',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='device_credentials',
            new_name='credentials',
        ),
        migrations.AddField(
            model_name='firewall',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switchs', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewalls', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loadbalancers', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='databaseservers', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macdevices', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storagedevices', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='credentials_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtualmachines', to='unity_discovery.DiscoveryCredential'),
        )
    ]