# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-05-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0134_auto_20250515_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os_build_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
