# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-12 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity_discovery', '0057_auto_20250521_0513'),
        ('inventory', '0135_server_os_build_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='databaseserver_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='firewall_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='loadbalancer_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='macdevice_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='server',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='server_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='storagedevice_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='switch',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='switch_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='credentials_m2m',
            field=models.ManyToManyField(blank=True, related_name='virtualmachine_credentials', to='unity_discovery.DiscoveryCredential'),
        ),
    ]
