# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-12 05:13
from __future__ import unicode_literals

from django.db import migrations

def migrate_credentials(apps, schema_editor):
    model_names = [
        'Switch',
        'Firewall',
        'LoadBalancer',
        'MacDevice',
        'Server',
        'StorageDevice',
        'DatabaseServer',
        'VirtualMachine'
    ]

    for model_name in model_names:
        Model = apps.get_model('inventory', model_name)
        for obj in Model.objects.all():
            if obj.credentials:
                obj.credentials_m2m.add(obj.credentials)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0136_auto_20250611_2211'),
    ]

    operations = [
        migrations.RunPython(migrate_credentials),
    ]
