# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-12 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0137_auto_20250611_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewall',
            old_name='credentials',
            new_name='ncm_credentials',
        ),
        migrations.RenameField(
            model_name='loadbalancer',
            old_name='credentials',
            new_name='ncm_credentials',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='credentials',
            new_name='ncm_credentials',
        ),
    ]
