# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0138_auto_20250611_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='redfish',
            field=models.BooleanField(default=False),
        ),
    ]
