# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0139_server_redfish'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='redfish',
            field=models.BooleanField(default=False),
        ),
    ]
