# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-17 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0140_switch_redfish'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='redfish',
            field=models.BooleanField(default=False),
        ),
    ]
