# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-06-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0139_auto_20250625_0721'),
        ('inventory', '0141_storagedevice_redfish'),
    ]

    operations = [
    ]
