# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-13 13:57
from __future__ import unicode_literals

import app.Utils.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0143_auto_20250812_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=app.Utils.utility.generate_uuid, null=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('discovery_method', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('database_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='inventory.DatabaseServer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
