# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-08-27 11:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0144_databaseentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseentity',
            name='custom_attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
