# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0145_databaseentity_custom_attribute_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='end_of_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='market_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
