# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-06 16:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0146_auto_20250903_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='boot_rom_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='capability_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='chassis_bootup_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='configuration_options',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='data_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='dhcp_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='disk_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='expansion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='flash_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='input_current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='integrity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='max_consumption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='number_of_slots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='physical_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='ports_per_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='primary_capability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='reset_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='reset_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='system_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='thermal_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firewallmodel',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewallmodel',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='boot_rom_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='capability_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='chassis_bootup_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='configuration_options',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='data_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='dhcp_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='disk_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='expansion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='flash_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='input_current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='integrity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='max_consumption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='number_of_slots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='physical_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='ports_per_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='primary_capability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='reset_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='reset_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='system_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='thermal_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancermodel',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancermodel',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobiledevicemodel',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobiledevicemodel',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdumodel',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdumodel',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='admin_password_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='boot_rom_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='capability_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='chassis_bootup_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='configuration_options',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='data_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='dhcp_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='disk_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='flash_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='fqdn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='input_current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='max_consumption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='media_supported',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='number_of_slots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='os_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='other_capability_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ports_per_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='primary_capability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='reset_capability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='reset_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='reset_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(default=b'Virtual', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='service_pack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='snapshot_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='system_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servermodel',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermodel',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='boot_rom_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='capability_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='chassis_bootup_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='configuration_options',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='data_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='dhcp_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='disk_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='expansion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='flash_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='input_current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='integrity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='max_consumption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='number_of_slots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='physical_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='ports_per_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='primary_capability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='reset_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='reset_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='system_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='thermal_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switchmodel',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='admin_password_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='boot_rom_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='capability_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='chassis_bootup_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='configuration_options',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='data_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='dhcp_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='end_of_extended_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='end_of_security_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='end_of_support',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='flash_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='input_current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='max_consumption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='media_supported',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='number_of_slots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='other_capability_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='physical_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ports_per_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='primary_capability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='reset_capability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='reset_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='reset_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='system_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
