# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-09 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0147_auto_20250906_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='rack_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='rack_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
