# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-29 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0148_auto_20250909_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='service_pack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
