# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0149_databaseserver_service_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmserver',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseentity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firewall',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
