# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0150_auto_20251201_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmserver',
            name='life_cycle_stage',
            field=models.CharField(blank=True, choices=[(b'Defective', b'Defective'), (b'Deploy', b'Deploy'), (b'End of Life', b'End of Life'), (b'End of Operation', b'End of Operation'), (b'Inventory', b'Inventory'), (b'Missing', b'Missing'), (b'Operational', b'Operational'), (b'Purchase', b'Purchase')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bmserver',
            name='life_cycle_stage_status',
            field=models.CharField(blank=True, choices=[(b'Buy Out', b'Buy Out'), (b'Disposed', b'Disposed'), (b'Donated', b'Donated'), (b'In Transit', b'In Transit'), (b'Lease Return', b'Lease Return'), (b'Pending Certificate', b'Pending Certificate'), (b'Pending Disposal', b'Pending Disposal'), (b'Retired', b'Retired'), (b'RMA', b'RMA'), (b'Sold', b'Sold'), (b'Vendor Credit', b'Vendor Credit'), (b'In Stock', b'In Stock'), (b'Pending Transfer', b'Pending Transfer'), (b'Reserved', b'Reserved'), (b'Test', b'Test')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='life_cycle_stage',
            field=models.CharField(blank=True, choices=[(b'Defective', b'Defective'), (b'Deploy', b'Deploy'), (b'End of Life', b'End of Life'), (b'End of Operation', b'End of Operation'), (b'Inventory', b'Inventory'), (b'Missing', b'Missing'), (b'Operational', b'Operational'), (b'Purchase', b'Purchase')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='life_cycle_stage_status',
            field=models.CharField(blank=True, choices=[(b'Buy Out', b'Buy Out'), (b'Disposed', b'Disposed'), (b'Donated', b'Donated'), (b'In Transit', b'In Transit'), (b'Lease Return', b'Lease Return'), (b'Pending Certificate', b'Pending Certificate'), (b'Pending Disposal', b'Pending Disposal'), (b'Retired', b'Retired'), (b'RMA', b'RMA'), (b'Sold', b'Sold'), (b'Vendor Credit', b'Vendor Credit'), (b'In Stock', b'In Stock'), (b'Pending Transfer', b'Pending Transfer'), (b'Reserved', b'Reserved'), (b'Test', b'Test')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='life_cycle_stage',
            field=models.CharField(blank=True, choices=[(b'Defective', b'Defective'), (b'Deploy', b'Deploy'), (b'End of Life', b'End of Life'), (b'End of Operation', b'End of Operation'), (b'Inventory', b'Inventory'), (b'Missing', b'Missing'), (b'Operational', b'Operational'), (b'Purchase', b'Purchase')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='life_cycle_stage_status',
            field=models.CharField(blank=True, choices=[(b'Buy Out', b'Buy Out'), (b'Disposed', b'Disposed'), (b'Donated', b'Donated'), (b'In Transit', b'In Transit'), (b'Lease Return', b'Lease Return'), (b'Pending Certificate', b'Pending Certificate'), (b'Pending Disposal', b'Pending Disposal'), (b'Retired', b'Retired'), (b'RMA', b'RMA'), (b'Sold', b'Sold'), (b'Vendor Credit', b'Vendor Credit'), (b'In Stock', b'In Stock'), (b'Pending Transfer', b'Pending Transfer'), (b'Reserved', b'Reserved'), (b'Test', b'Test')], max_length=50, null=True),
        ),
    ]
