# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0151_auto_20251203_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bmserver',
            name='life_cycle_stage_status',
            field=models.CharField(blank=True, choices=[(b'Buy Out', b'Buy Out'), (b'Disposed', b'Disposed'), (b'Donated', b'Donated'), (b'In Transit', b'In Transit'), (b'Lease Return', b'Lease Return'), (b'Pending Certificate', b'Pending Certificate'), (b'Pending Disposal', b'Pending Disposal'), (b'Retired', b'Retired'), (b'RMA', b'RMA'), (b'Sold', b'Sold'), (b'Vendor Credit', b'Vendor Credit'), (b'In Stock', b'In Stock'), (b'Pending Transfer', b'Pending Transfer'), (b'Reserved', b'Reserved'), (b'Test', b'Test'), (b'In Use', b'In Use'), (b'Pending Retirement', b'Pending Retirement')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='life_cycle_stage_status',
            field=models.CharField(blank=True, choices=[(b'Buy Out', b'Buy Out'), (b'Disposed', b'Disposed'), (b'Donated', b'Donated'), (b'In Transit', b'In Transit'), (b'Lease Return', b'Lease Return'), (b'Pending Certificate', b'Pending Certificate'), (b'Pending Disposal', b'Pending Disposal'), (b'Retired', b'Retired'), (b'RMA', b'RMA'), (b'Sold', b'Sold'), (b'Vendor Credit', b'Vendor Credit'), (b'In Stock', b'In Stock'), (b'Pending Transfer', b'Pending Transfer'), (b'Reserved', b'Reserved'), (b'Test', b'Test'), (b'In Use', b'In Use'), (b'Pending Retirement', b'Pending Retirement')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='life_cycle_stage_status',
            field=models.CharField(blank=True, choices=[(b'Buy Out', b'Buy Out'), (b'Disposed', b'Disposed'), (b'Donated', b'Donated'), (b'In Transit', b'In Transit'), (b'Lease Return', b'Lease Return'), (b'Pending Certificate', b'Pending Certificate'), (b'Pending Disposal', b'Pending Disposal'), (b'Retired', b'Retired'), (b'RMA', b'RMA'), (b'Sold', b'Sold'), (b'Vendor Credit', b'Vendor Credit'), (b'In Stock', b'In Stock'), (b'Pending Transfer', b'Pending Transfer'), (b'Reserved', b'Reserved'), (b'Test', b'Test'), (b'In Use', b'In Use'), (b'Pending Retirement', b'Pending Retirement')], max_length=50, null=True),
        ),
    ]
