# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-24 18:43
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_url_passwords(apps, schema_editor):
    URL = apps.get_model("inventory", "url")
    for row in URL.objects.all():
            row._login_password = row.login_password
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0152_auto_20251215_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='_login_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_url_passwords),
        migrations.RemoveField(
            model_name='url',
            name='login_password',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='_login_password',
            new_name='login_password',
        ),
    ]
