# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-29 09:52
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_f5apiportal_passwords(apps, schema_editor):
    F5APIPortal = apps.get_model("inventory", "f5apiportal")
    for row in F5APIPortal.objects.all():
            row._password = row.password
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0153_auto_20251224_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5apiportal',
            name='_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_f5apiportal_passwords),
        migrations.RemoveField(
            model_name='f5apiportal',
            name='password',
        ),
        migrations.RenameField(
            model_name='f5apiportal',
            old_name='_password',
            new_name='password',
        ),

    ]
