# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-29 10:10
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_storagedevice_passwords(apps, schema_editor):
    StorageDevice = apps.get_model("inventory", "storagedevice")
    for row in StorageDevice.objects.all():
            row._password = row.password
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0154_auto_20251229_0152'),
    ]

    operations = [

        migrations.AddField(
            model_name='storagedevice',
            name='_password',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_storagedevice_passwords),
        migrations.RemoveField(
            model_name='storagedevice',
            name='password',
        ),
        migrations.RenameField(
            model_name='storagedevice',
            old_name='_password',
            new_name='password',
        )
    ]
