# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-29 10:10
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_storagedevice_tokens(apps, schema_editor):
    StorageDevice = apps.get_model("inventory", "storagedevice")
    for row in StorageDevice.objects.all():
            row._purity_api_token = row.purity_api_token
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0155_auto_20251229_0210'),
    ]

    operations = [
        # purity aip token 
        migrations.AddField(
            model_name='storagedevice',
            name='_purity_api_token',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_storagedevice_tokens),
        migrations.RemoveField(
            model_name='storagedevice',
            name='purity_api_token',
        ),
        migrations.RenameField(
            model_name='storagedevice',
            old_name='_purity_api_token',
            new_name='purity_api_token',
        ),
    ]
