# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-29 18:23
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_PDU_passwords(apps, schema_editor):
    PDU = apps.get_model("inventory", "pdu")
    for row in PDU.objects.all():
            row._password = row.password
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0156_auto_20251229_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='_password',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_PDU_passwords),
        migrations.RemoveField(
            model_name='pdu',
            name='password',
        ),
        migrations.RenameField(
            model_name='pdu',
            old_name='_password',
            new_name='password',
        )
    ]
