# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-12-29 18:53
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_ipmiattributes_passwords(apps, schema_editor):
    Ipmiattributes = apps.get_model("inventory", "ipmiattributes")
    for row in Ipmiattributes.objects.all():
            row._ipmi_password = row.ipmi_password
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0157_pdu__password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmiattributes',
            name='_ipmi_password',
            field=app.common.fields.EncryptedPasswordField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_ipmiattributes_passwords),
        migrations.RemoveField(
            model_name='ipmiattributes',
            name='ipmi_password',
        ),
        migrations.RenameField(
            model_name='ipmiattributes',
            old_name='_ipmi_password',
            new_name='ipmi_password',
        )
    ]
