# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-01-07 11:04
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_firewall_community(apps, schema_editor):
    firewall = apps.get_model("inventory", "firewall")
    for row in firewall.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_loadbalancer_community(apps, schema_editor):
    loadbalancer = apps.get_model("inventory", "loadbalancer")
    for row in loadbalancer.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_macdevice_community(apps, schema_editor):
    macdevice = apps.get_model("inventory", "macdevice")
    for row in macdevice.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_pdu_community(apps, schema_editor):
    pdu = apps.get_model("inventory", "pdu")
    for row in pdu.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_rfidreader_community(apps, schema_editor):
    rfidreader = apps.get_model("inventory", "rfidreader")
    for row in rfidreader.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_sensor_community(apps, schema_editor):
    sensor = apps.get_model("inventory", "sensor")
    for row in sensor.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_server_community(apps, schema_editor):
    server = apps.get_model("inventory", "server")
    for row in server.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_smartpdu_community(apps, schema_editor):
    smartpdu = apps.get_model("inventory", "smartpdu")
    for row in smartpdu.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_storagedevice_community(apps, schema_editor):
    storagedevice = apps.get_model("inventory", "storagedevice")
    for row in storagedevice.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_switch_community(apps, schema_editor):
    switch = apps.get_model("inventory", "switch")
    for row in switch.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_virtualmachine_community(apps, schema_editor):
    virtualmachine = apps.get_model("inventory", "virtualmachine")
    for row in virtualmachine.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0158_ipmiattributes__ipmi_password'),
    ]

    operations = [
        #firewall
        migrations.AddField(
            model_name='firewall',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_firewall_community),
        migrations.RemoveField(
            model_name='firewall',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='firewall',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        # loadbalancer
        migrations.AddField(
            model_name='loadbalancer',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_loadbalancer_community),
        migrations.RemoveField(
            model_name='loadbalancer',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='loadbalancer',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #macdevice 
        migrations.AddField(
            model_name='macdevice',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_macdevice_community),
        migrations.RemoveField(
            model_name='macdevice',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='macdevice',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #pdu
        migrations.AddField(
            model_name='pdu',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_pdu_community),
        migrations.RemoveField(
            model_name='pdu',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='pdu',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #rfidreader 
        migrations.AddField(
            model_name='rfidreader',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_rfidreader_community),
        migrations.RemoveField(
            model_name='rfidreader',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='rfidreader',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #sensor
        migrations.AddField(
            model_name='sensor',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_sensor_community),
        migrations.RemoveField(
            model_name='sensor',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #server
        migrations.AddField(
            model_name='server',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_server_community),
        migrations.RemoveField(
            model_name='server',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #smartpdu
        migrations.AddField(
            model_name='smartpdu',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_smartpdu_community),
        migrations.RemoveField(
            model_name='smartpdu',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='smartpdu',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #storagedevice
        migrations.AddField(
            model_name='storagedevice',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_storagedevice_community),
        migrations.RemoveField(
            model_name='storagedevice',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='storagedevice',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #switch
        migrations.AddField(
            model_name='switch',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_switch_community),
        migrations.RemoveField(
            model_name='switch',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #virtualmachine
        migrations.AddField(
            model_name='virtualmachine',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_virtualmachine_community),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),
    ]
