# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-01-08 07:28
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations

def encrypt_customdevice_community(apps, schema_editor):
    customdevice = apps.get_model("inventory", "customdevice")
    for row in customdevice.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_san_community(apps, schema_editor):
    san = apps.get_model("inventory", "san")
    for row in san.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_terminalserver_community(apps, schema_editor):
    terminalserver = apps.get_model("inventory", "terminalserver")
    for row in terminalserver.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

def encrypt_virtualloadbalancer_community(apps, schema_editor):
    virtualloadbalancer = apps.get_model("inventory", "virtualloadbalancer")
    for row in virtualloadbalancer.objects.all():
            row._snmp_community = row.snmp_community
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0159_auto_20260107_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevice',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_customdevice_community),
        migrations.RemoveField(
            model_name='customdevice',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='customdevice',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #SAN
        migrations.AddField(
            model_name='san',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_san_community),
        migrations.RemoveField(
            model_name='san',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='san',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #terminal server
        migrations.AddField(
            model_name='terminalserver',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_terminalserver_community),
        migrations.RemoveField(
            model_name='terminalserver',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='terminalserver',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),

        #virtualloadbalancer
        migrations.AddField(
            model_name='virtualloadbalancer',
            name='_snmp_community',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.RunPython(encrypt_virtualloadbalancer_community),
        migrations.RemoveField(
            model_name='virtualloadbalancer',
            name='snmp_community',
        ),
        migrations.RenameField(
            model_name='virtualloadbalancer',
            old_name='_snmp_community',
            new_name='snmp_community',
        ),
    ]
