# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-05-18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0160_auto_20260107_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseserver',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
