# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2026-05-18 11:58
from __future__ import unicode_literals

import app.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0161_databaseserver_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewall',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadbalancer',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macdevice',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdu',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='smartpdu',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartpdu',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartpdu',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smartpdu',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='smartpdu',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartpdu',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mon_connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mon_credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mon_credential_mode',
            field=models.CharField(blank=True, choices=[(b'local', b'Local'), (b'my_cred', b'My Credentials')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mon_password',
            field=app.common.fields.EncryptedPasswordField(null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='mon_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='firewall',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loadbalancer',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='macdevice',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfidreader',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smartpdu',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='connection_type',
            field=models.CharField(blank=True, choices=[(b'SNMP', b'SNMP'), (b'Agent', b'Agent'), (b'HTTP', b'HTTP'), (b'API', b'API'), (b'SSH', b'SSH'), (b'WinRM', b'WinRM')], max_length=50, null=True),
        ),
    ]
