# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.Utils.utility
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSInstancePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('instance_type', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=40)),
                ('ram', models.DecimalField(decimal_places=3, max_digits=7)),
                ('cpu', models.IntegerField()),
                ('storage_inbuilt', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('nw_performance', models.CharField(max_length=25)),
                ('purchase_option', models.CharField(max_length=40)),
                ('lease_contract_length', models.CharField(default=b'Oyr', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AzureStoragePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('offer_id', models.CharField(default=b'MS-AZR-0003P', max_length=20)),
                ('meter_name', models.CharField(max_length=40)),
                ('disk_size', models.IntegerField()),
                ('region', models.CharField(max_length=40)),
                ('meter_category', models.CharField(max_length=50)),
                ('meter_sub_category', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AzureVMPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('offer_id', models.CharField(default=b'MS-AZR-0003P', max_length=20)),
                ('tier', models.CharField(max_length=50)),
                ('meter_name', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=40)),
                ('meter_category', models.CharField(max_length=50)),
                ('meter_sub_category', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AzureVMSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('ram_in_mb', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('os_disk_size_mb', models.IntegerField()),
                ('resource_disk_size_mb', models.IntegerField()),
                ('data_disk_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GCPMachineTypePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('description', models.CharField(max_length=100)),
                ('usage_type', models.CharField(default=b'OnDemand', max_length=20)),
                ('commitment', models.CharField(default=b'0yr', max_length=10)),
                ('cpu_or_ram', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=40)),
                ('machine_class', models.CharField(max_length=40)),
                ('machine_type', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='GCPStoragePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=app.Utils.utility.generate_uuid)),
                ('description', models.CharField(max_length=100)),
                ('usage_type', models.CharField(default=b'OnDemand', max_length=20)),
                ('region', models.CharField(max_length=40)),
                ('storage_type', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='azurevmpricing',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azure_vm_size', to='cost_calculator.AzureVMSize'),
        ),
    ]
