# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-11-25 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurevmpricing',
            name='commitment',
            field=models.CharField(default=b'0yr', max_length=10),
        ),
    ]
