# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-16 11:15
from __future__ import unicode_literals

import app.Utils.utility
import app.user2.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('salesforce', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='Designates whether the user can log into this admin site.',
                                                 verbose_name='staff status')),
                ('is_customer_admin',
                 models.BooleanField(default=False, help_text='This defines special customer privileges',
                                     verbose_name='customer admin role')),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                    verbose_name='active')
                 ),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('timezone', models.CharField(blank=True, default='US/Pacific', max_length=30, verbose_name='timezone')),
                ('is_terminated', models.BooleanField(default=False, verbose_name='terminated')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('salesforce_id', models.CharField(blank=True, max_length=128, null=True)),
                ('uuid',
                 models.UUIDField(blank=True, default=app.Utils.utility.generate_uuid, null=True, verbose_name='UUID')),
                ('welcome_page', models.BooleanField(default=True)),
                ('ticket_group', models.CharField(max_length=200, null=True, validators=[
                    django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid',
                                                          message='Enter only digits separated by commas.')])),
                ('eula_version', models.FloatField(default=0)),
                ('trial_account', models.BooleanField(default=False)),
                ('trial_account_end_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', app.user2.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'accesslist',
            },
        ),
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='DemoTrialRequestToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=128)),
                ('pending', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('account_type',
                 models.CharField(choices=[('DEMO', 'DEMO'), ('TRIAL', 'TRIAL')], default='DEMO', max_length=64)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('uuid',
                 models.UUIDField(blank=True, default=app.Utils.utility.generate_uuid, null=True, verbose_name='UUID')),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_groups',
                                   to='organization.Organization')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            managers=[
                ('objects', app.user2.models.OrganizationGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', related_query_name='role',
                                                       to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ULDBUserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=128)),
                ('pending', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user2.Role', verbose_name='roles'),
        ),
        migrations.AddField(
            model_name='user',
            name='access_types',
            field=models.ManyToManyField(related_name='users', to='user2.AccessType'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True,
                                         help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                         related_name='users', related_query_name='user', to='user2.OrganizationGroup',
                                         verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users',
                                    to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='salesforce_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='salesforce.SalesforceRecord'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                         related_name='users', related_query_name='user', to='user2.Role',
                                         verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationgroup',
            unique_together=set([('organization', 'name')]),
        ),
    ]
