# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-13 18:45
from __future__ import unicode_literals

from django.db import migrations


def set_role(apps, schema_editor):
    Role = apps.get_model('user2', 'Role')
    role_list = [Role(name='Administrator'), Role(name='Global Read-Only'), Role(name='Dashboard user')]
    for role in role_list:
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_role)
    ]
