# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-02-20 15:51
from __future__ import unicode_literals

from django.db import migrations


def update_role_exsisting_user(apps, schema_editor):
    Role = apps.get_model('user2', 'Role')
    User = apps.get_model('user2', 'User')
    admin = Role.objects.get(name='Administrator')
    readonly = Role.objects.get(name='Global Read-Only')
    users = User.objects.all()
    for user in users:
        if user.is_customer_admin is True:
            print user.first_name, 'admin....'
            user.user_roles.add(admin)
        elif user.is_customer_admin is False:
            print user.first_name, 'readonly....'
            user.user_roles.add(readonly)


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0002_auto_20230213_1045'),
    ]

    operations = [
        migrations.RunPython(update_role_exsisting_user)
    ]
