# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-07 13:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0003_auto_20230220_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarrierList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=256)),
                ('sms_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=None)),
            ],
            options={
                'db_table': 'usercarrierlist',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be of 10 digits.',
                        regex='^(\\d{10})$'
                    )
                ]
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user2.UserCarrierList'),
        ),
    ]
