# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0005_auto_20230307_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(default='Tenant', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Tenant', max_length=10),
        ),
    ]
