# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-12 13:18
from __future__ import unicode_literals

from django.db import migrations


def update_role(apps, schema_editor):
    Role = apps.get_model('user2', 'Role')
    new_role_list = ['Read-Only', 'Super Admin', 'Tenant Admin']
    for role in new_role_list:
        Role.objects.get_or_create(name=role, role_type="MSP")


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0006_auto_20231012_0127'),
    ]

    operations = [
        migrations.RunPython(update_role, migrations.RunPython.noop),
    ]
