# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-10-27 12:02
from __future__ import unicode_literals

import app.Utils.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0007_auto_20231012_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(default=app.Utils.utility.generate_uuid, verbose_name='UUID'),
        ),
    ]
