# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-08-27 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0008_role_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
