# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-09-17 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20240808_0915'),
        ('user2', '0009_user_azure_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_inclusion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rbac_roles',
            field=models.ManyToManyField(blank=True, related_name='user_rbac_roles', to='rbac.RBACRole'),
        ),
    ]
