# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-09-17 06:08
from __future__ import unicode_literals

from django.db import migrations


def migrate_user_roles_to_rbac_roles(apps, schema_editor):
    User = apps.get_model('user2', 'User')
    Role = apps.get_model('user2', 'Role')
    RBACRole = apps.get_model('rbac', 'RBACRole')

    role_names = list(Role.objects.all().values_list('name', flat=True))

    rbac_roles_map = {}

    for role_name in role_names:
        try:
            rbac_roles_map[role_name] = RBACRole.objects.get(name=role_name)
        except RBACRole.DoesNotExist:
            pass

    for user in User.objects.all():
        user.group_inclusion = "none"
        user.save()
        user_roles = user.user_roles.filter(name__in=role_names)
        for user_role in user_roles:
            rbac_role = rbac_roles_map.get(user_role.name)
            if rbac_role:
                user.rbac_roles.add(rbac_role)


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0010_auto_20240916_2307'),
    ]

    operations = [
        migrations.RunPython(migrate_user_roles_to_rbac_roles)
    ]
