# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2024-10-24 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_user', '0005_populate_ldap_job_schedule'),
        ('user2', '0011_auto_20240916_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ldap_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ldap_user.LDAPConfig'),
        ),
        migrations.AddField(
            model_name='user',
            name='ldap_user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
