# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_widget', '0016_auto_20250915_0138'),
        ('user2', '0012_auto_20241024_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_dashboard', to='custom_widget.Dashboard'),
        ),
    ]
