# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2025-09-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0013_user_default_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_widget.Dashboard'),
        ),
    ]
